import fs from 'node:fs';
import { expandCatalog } from './catalog-expansion.mjs';
const inventory=JSON.parse(fs.readFileSync('sources/anatomy/z-inventory.json'));
const available=new Set(inventory.filter(x=>x.faces!==0&&!/\.[jgeo]$/.test(x.name)).map(x=>x.name));
const plan=[];const missing=[];
const source='https://openstax.org/books/anatomy-and-physiology-2e/pages/1-2-structural-organization-of-the-human-body';
function add(id,name,names,layer,system,region,definition,fn,options={}) {
 const found=names.filter(n=>available.has(n));if(!found.length){missing.push(name+': '+names.join(', '));return;}
 plan.push({id,nameId:name,anatomicalName:names[0].replace(/\.[lr]$/,''),sourceNames:found,layer,systemIds:[system],regionId:region,definitionSimple:definition,definitionDetailed:definition+' '+fn,functions:[fn],locationText:options.location||'Di wilayah '+({head:'kepala',neck:'leher',thorax:'dada',abdomen:'perut',pelvis:'panggul',shoulder:'bahu',arm:'lengan atas',forearm:'lengan bawah',hand:'tangan',thigh:'paha',leg:'tungkai bawah',foot:'kaki',knee:'lutut',wrist:'pergelangan tangan',ankle:'pergelangan kaki'}[region]||region)+'.',aliases:options.aliases||[],laterality:options.side||'none',parentId:options.parent||null,assetId:options.pack||layer,sources:[{title:system==='cardiovascular'?'NHLBI — anatomi dan aliran jantung':'OpenStax — Anatomy and Physiology 2e',url:system==='cardiovascular'?'https://www.nhlbi.nih.gov/health/heart/blood-flow':source}],reviewStatus:'pending',reviewedAt:null,...options});
}
const organs=[
 ['liver','Hati',['Liver'],'digestive','abdomen','Organ yang mengolah zat dari makanan dan menghasilkan empedu.','Empedu membantu pencernaan lemak; hati juga menyimpan dan mengolah zat gizi.'],
 ['stomach','Lambung',['Stomach'],'digestive','abdomen','Kantong berotot yang mencampur makanan dengan cairan pencernaan.','Mengaduk makanan dan memulai pencernaan protein.'],
 ['pancreas','Pankreas',['Pancreas'],'digestive','abdomen','Kelenjar yang membantu pencernaan dan pengaturan gula darah.','Menghasilkan enzim pencernaan serta hormon seperti insulin.'],
 ['gallbladder','Kantong empedu',['Gallbladder'],'digestive','abdomen','Kantong kecil penyimpan empedu dari hati.','Melepaskan empedu ke usus halus saat dibutuhkan.'],
 ['esophagus','Kerongkongan',['Oesophagus'],'digestive','thorax','Saluran berotot yang membawa makanan menuju lambung.','Gerak peristaltik mendorong makanan setelah ditelan.'],
 ['tongue','Lidah',['Tongue'],'digestive','head','Organ berotot di mulut yang membantu mengecap dan menggerakkan makanan.','Membantu mengunyah, menelan, dan berbicara.'],
 ['duodenum','Usus dua belas jari',['Duodenum'],'digestive','abdomen','Bagian pertama usus halus setelah lambung.','Menerima empedu dan cairan pankreas untuk melanjutkan pencernaan.'],
 ['jejunum','Usus kosong',['Jejunum'],'digestive','abdomen','Bagian tengah usus halus yang menyerap banyak zat gizi.','Menyerap hasil pencernaan ke peredaran darah dan limfa.'],
 ['colon_ascending','Kolon asendens',['Ascending colon'],'digestive','abdomen','Bagian usus besar yang naik di sisi kanan tubuh.','Menyerap air dan membantu membawa sisa makanan.'],
 ['colon_transverse','Kolon transversum',['Transverse colon'],'digestive','abdomen','Bagian usus besar yang melintang di perut.','Membawa isi usus sambil menyerap air.'],
 ['colon_descending','Kolon desendens',['Descending colon'],'digestive','abdomen','Bagian usus besar yang turun di sisi kiri tubuh.','Membawa sisa pencernaan menuju kolon sigmoid.'],
 ['colon_sigmoid','Kolon sigmoid',['Sigmoid colon'],'digestive','pelvis','Bagian usus besar yang melengkung sebelum rektum.','Membawa feses menuju rektum.'],
 ['bladder','Kandung kemih',['Urinary bladder'],'urinary','pelvis','Kantong berotot yang menampung urine.','Menyimpan urine sebelum dikeluarkan melalui uretra.'],
 ['spleen','Limpa',['Spleen'],'lymphatic','abdomen','Organ limfatik yang menyaring darah.','Membantu pertahanan tubuh dan mengolah sel darah yang sudah tua.'],
 ['thyroid','Kelenjar tiroid',['Thyroid gland'],'endocrine','neck','Kelenjar di bagian depan leher yang menghasilkan hormon tiroid.','Hormon tiroid membantu mengatur penggunaan energi tubuh.'],
 ['pituitary','Kelenjar hipofisis',['Adenohypophysis','Neurohypophysis'],'endocrine','head','Kelenjar kecil di dasar otak yang terhubung dengan hipotalamus.','Melepas hormon yang berperan dalam pertumbuhan dan pengaturan kelenjar lain.'],
 ['prostate','Prostat',['Prostate'],'reproductive','pelvis','Kelenjar pada variasi anatomi laki-laki, di bawah kandung kemih.','Menyumbang cairan penyusun semen.'],
 ['trachea','Batang tenggorok',['Trachea'],'respiratory','neck','Saluran udara dengan penyangga tulang rawan.','Mengalirkan udara dari laring menuju bronkus.'],
];
for (const [id,n,ns,sys,reg,d,f] of organs) add(id,n,ns,'organ',sys,reg,d,f);
const sides=[['l','kiri','left'],['r','kanan','right']];
for(const [suffix,label,side] of sides){
 const sideTitle=side==='left'?'Left':'Right';
 add('lung_'+suffix,'Paru-paru '+label,[(side==='left'?'Superior lobe of left lung':'Superior lobe of right lung'),...(side==='right'?['Middle lobe of right lung']:[]),(side==='left'?'Inferior lobe of left lung':'Inferior lobe of right lung')],'organ','respiratory','thorax','Organ pernapasan di sisi '+label+' dada.','Pertukaran oksigen dan karbon dioksida berlangsung di alveolus.',{side,aliases:['pulmo','paru']});
 add('adrenal_'+suffix,'Kelenjar adrenal '+label,['Suprarenal gland.'+suffix],'organ','endocrine','abdomen','Kelenjar penghasil hormon di atas ginjal '+label+'.','Hormon adrenal berperan dalam respons stres dan keseimbangan garam.',{side});
 add('thymus_'+suffix,'Lobus timus '+label,[sideTitle+' lobe of thymus'],'organ','lymphatic','thorax','Bagian '+label+' timus, organ tempat pematangan sel T.','Mendukung perkembangan sistem kekebalan tubuh.',{side});
 add('testis_'+suffix,'Testis '+label,['Testis.'+suffix],'organ','reproductive','pelvis','Organ reproduksi pada variasi anatomi laki-laki.','Menghasilkan sperma dan hormon testosteron.',{side,pack:'reproductive'});
 add('seminal_'+suffix,'Vesikula seminalis '+label,['Seminal gland.'+suffix],'organ','reproductive','pelvis','Kelenjar reproduksi di belakang kandung kemih.','Menghasilkan sebagian cairan semen.',{side,pack:'reproductive'});
 add('eye_'+suffix,'Mata '+label,['Sclera.'+suffix],'organ','nervous','head','Organ penglihatan; model ini memperlihatkan selubung sklera.','Melindungi bagian dalam mata dan mempertahankan bentuknya.',{side,aliases:['oculus','sklera']});
 const cortex=inventory.filter(x=>x.collections.includes('Neo-cortex')&&x.name.endsWith('.'+suffix)&&x.faces>0).map(x=>x.name);
 add('brain_'+suffix,'Korteks otak '+label,cortex,'nerve','nervous','head','Lapisan luar belahan otak besar '+label+'.','Berperan dalam pengolahan indra, gerakan sadar, bahasa, dan pemikiran.',{side,aliases:['otak','cerebrum','cortex'],anatomicalName:'Cerebral cortex'});
 add('sciatic_'+suffix,'Saraf skiatik '+label,['Sciatic nerve.'+suffix],'nerve','nervous','thigh','Saraf besar yang menuju bagian belakang paha.','Membawa sinyal menuju dan dari bagian tungkai serta kaki.',{side});
 add('optic_'+suffix,'Saraf optik '+label,['Optic nerve (II).'+suffix],'nerve','nervous','head','Saraf yang membawa informasi visual dari retina.','Menghubungkan retina dengan jalur penglihatan di otak.',{side});
 const muscles=[['pectoralis','Otot dada besar',['Clavicular head of pectoralis major muscle','Sternocostal head of pectoralis major muscle','(Abdominal part of pectoralis major muscle)'],'thorax','Membantu membawa lengan mendekati tubuh dan memutar lengan ke dalam.'],['deltoid','Otot deltoid',['Acromial part of deltoid muscle','Clavicular part of deltoid muscle','Scapular spinal part of deltoid muscle'],'shoulder','Membantu mengangkat dan menggerakkan lengan di sendi bahu.'],['biceps','Otot bisep',['Long head of biceps brachii','Short head of biceps brachii'],'arm','Membantu menekuk siku dan memutar telapak tangan ke atas.'],['rectus_abdominis','Otot perut lurus',['Rectus abdominis muscle'],'abdomen','Membantu menekuk batang tubuh dan menyangga isi perut.'],['rectus_femoris','Otot paha depan',['Rectus femoris muscle'],'thigh','Membantu meluruskan lutut dan menekuk panggul.'],['gastrocnemius','Otot betis',['Lateral head of gastrocnemius','Medial head of gastrocnemius'],'leg','Membantu mengangkat tumit dan menekuk lutut.'],['gluteus','Otot bokong besar',['Gluteus maximus muscle'],'pelvis','Membantu meluruskan panggul saat berdiri dan menaiki tangga.']];
 for(const [id,n,ns,reg,fn] of muscles)add(id+'_'+suffix,n+' '+label,ns.map(n=>n+'.'+suffix),'muscle','muscular',reg,'Otot rangka di sisi '+label+' tubuh.',fn,{side});
}
add('brainstem','Batang otak',['Pons.l','Pons.r','Medulla oblongata.l','Medulla oblongata.r'],'nerve','nervous','head','Bagian penghubung otak dengan sumsum tulang belakang.','Berperan dalam fungsi dasar seperti pernapasan; model ini mencakup pons dan medula.');
// Shell and chamber walls are partitioned from the same evaluated tissue, never duplicated.
add('heart','Jantung',['Right atrium','Left atrium','Right ventricle','Left ventricle'],'organ','cardiovascular','thorax','Organ berotot yang memompa darah ke seluruh tubuh.','Menggerakkan darah melalui sirkulasi paru dan sirkulasi tubuh.',{pack:'heart',special:'heart-shell',aliases:['cor','jantung'],location:'Di antara paru-paru; sebagian besar massanya mengarah ke kiri tubuh.'});
for(const [id,n,ns,d,f] of [
 ['atrium_r','Serambi kanan',['Right atrium'],'Ruang atas kanan yang menerima darah kembali dari tubuh.','Meneruskan darah melalui katup trikuspid menuju bilik kanan.'],
 ['atrium_l','Serambi kiri',['Left atrium'],'Ruang atas kiri yang menerima darah dari paru-paru.','Meneruskan darah melalui katup mitral menuju bilik kiri.'],
 ['ventricle_r','Bilik kanan',['Right ventricle'],'Ruang bawah kanan yang memompa darah ke paru-paru.','Mengalirkan darah melewati katup pulmonal menuju trunkus pulmonalis.'],
 ['ventricle_l','Bilik kiri',['Left ventricle'],'Ruang bawah kiri yang memompa darah ke seluruh tubuh.','Mengalirkan darah melalui katup aorta; dindingnya lebih tebal daripada bilik kanan.'],
 ['valve_tricuspid','Katup trikuspid',['Inferior leaflet of right atrioventricular valve','Septal leaflet of right atrioventricular valve'],'Katup di antara serambi kanan dan bilik kanan.','Membantu mencegah aliran balik ke serambi kanan.'],
 ['valve_mitral','Katup mitral',['Posterior leaflet of left atrioventricular valve'],'Katup di antara serambi kiri dan bilik kiri.','Membantu mencegah aliran balik ke serambi kiri.'],
 ['valve_pulmonary','Katup pulmonal',['Anterior semilunar leaflet of pulmonary valve','Left semilunar leaflet of pulmonary valve','Right semilunar leaflet of pulmonary valve'],'Katup pada jalan keluar bilik kanan.','Membantu mencegah darah kembali dari trunkus pulmonalis ke bilik kanan.'],
 ['valve_aortic','Katup aorta',['Left coronary leaflet','Right coronary leaflet','Non-coronary leaflet'],'Katup pada jalan keluar bilik kiri menuju aorta.','Membantu mencegah aliran balik dari aorta ke bilik kiri.'],
 ])add(id,n,ns,'organ','cardiovascular','thorax',d,f,{pack:'heart',parent:'heart',special:/atrium|ventricle/.test(id)?'chamber-wall':undefined,side:id.endsWith('_r')?'right':id.endsWith('_l')?'left':'none',aliases:[id.startsWith('atrium')?'atrium':id.startsWith('ventricle')?'ventrikel':'valvula'],definitionDetailed:d+' '+f+(/atrium|ventricle/.test(id)?' Sorotan menandai jaringan dinding yang membatasi ruang; rongganya bukan benda padat.':'')});
for(const [id,n,ns,fn] of [
 ['aorta','Aorta',['Ascending aorta','Aortic arch'],'Membawa darah keluar dari bilik kiri menuju sirkulasi tubuh.'],
 ['pulmonary_trunk','Trunkus pulmonalis',['Pulmonary trunk','Bifurcation of pulmonary trunk'],'Membawa darah dari bilik kanan menuju arteri paru.'],
 ['pulmonary_artery_r','Arteri pulmonalis kanan',['Right pulmonary artery'],'Membawa darah menuju paru kanan.'],
 ['pulmonary_artery_l','Arteri pulmonalis kiri',['Left pulmonary artery'],'Membawa darah menuju paru kiri.'],
 ['pulmonary_vein_r','Vena pulmonalis kanan',['Right inferior pulmonary vein','Right superior pulmonary vein'],'Mengembalikan darah dari paru kanan ke serambi kiri.'],
 ['pulmonary_vein_l','Vena pulmonalis kiri',['Left inferior pulmonary vein','Left superior pulmonary vein'],'Mengembalikan darah dari paru kiri ke serambi kiri.'],
 ['vena_cava_superior','Vena kava superior',['Superior vena cava'],'Mengembalikan darah dari bagian atas tubuh ke serambi kanan.'],
 ['vena_cava_inferior','Vena kava inferior',['Inferior vena cava (thoracic part)'],'Mengembalikan darah dari bagian bawah tubuh ke serambi kanan.'],
 ['coronary_r','Arteri koroner kanan',['Right coronary artery'],'Memasok jaringan otot jantung.'],
 ['coronary_l','Arteri koroner kiri',['Left coronary artery'],'Memasok jaringan otot jantung.'],
 ])add(id,n,ns,'vessel','cardiovascular','thorax','Pembuluh darah yang terhubung dengan jantung.',fn,{pack:'heart',parent:'heart',side:id.endsWith('_r')?'right':id.endsWith('_l')?'left':'none'});
// Surface vessels follow authored anatomy; never invent decorative vascular paths.
for(const [id,name,source,fn] of [
 ['coronary_lad','Arteri interventrikular anterior','Anterior interventricular artery','Memasok bagian depan dinding bilik dan septum jantung.'],
 ['coronary_circumflex','Arteri sirkumfleksa','Circumflex artery of heart','Memasok bagian lateral dan sebagian belakang jantung.'],
 ['coronary_margin_r','Cabang inferolateral koroner kanan','Right inferolateral branch of right coronary artery','Memasok sisi kanan otot jantung.'],
 ['cardiac_vein_great','Vena jantung besar','Great cardiac vein','Mengalirkan darah dari otot jantung menuju sinus koroner.'],
 ['cardiac_vein_middle','Vena jantung tengah','Middle cardiac vein','Mengalirkan darah dari bagian belakang otot jantung.'],
 ['coronary_sinus','Sinus koroner','Coronary sinus','Mengumpulkan darah vena jantung sebelum menuju serambi kanan.'],
 ['cardiac_vein_inferior','Vena inferior bilik kiri','Inferior vein of left ventricle','Mengalirkan darah dari permukaan inferior bilik kiri.'],
])add(id,name,[source],'vessel','cardiovascular','thorax','Pembuluh pada permukaan jantung.',fn,{pack:'heart',parent:'heart',side:'none'});
// Individually named bones: retain semantic separation including fingers and toes.
const boneWords={'Frontal bone':'Tulang dahi','Occipital bone':'Tulang belakang tengkorak','Parietal bone':'Tulang ubun-ubun','Temporal bone':'Tulang pelipis','Sphenoid bone':'Tulang baji','Ethmoid bone':'Tulang tapis','Mandible':'Rahang bawah','Maxilla':'Rahang atas','Zygomatic bone':'Tulang pipi','Nasal bone':'Tulang hidung','Lacrimal bone':'Tulang air mata','Palatine bone':'Tulang langit-langit','Vomer':'Tulang vomer','Hyoid bone':'Tulang hioid','Clavicle':'Tulang selangka','Scapula':'Tulang belikat','Humerus':'Tulang lengan atas','Radius':'Tulang pengumpil','Ulna':'Tulang hasta','Femur':'Tulang paha','Tibia':'Tulang kering','Fibula':'Tulang betis','Patella':'Tempurung lutut','Hip bone':'Tulang panggul','Sacrum':'Tulang kelangkang','Coccyx':'Tulang ekor','Body of sternum':'Badan tulang dada','Manubrium of sternum':'Hulu tulang dada','Xiphoid process':'Taju pedang','Atlas (C1)':'Atlas (C1)','Axis (C2)':'Aksis (C2)','Calcaneus':'Tulang tumit','Talus':'Talus','Navicular bone':'Tulang navikular','Cuboid bone':'Tulang kuboid','Scaphoid bone':'Tulang skafoid','Lunate bone':'Tulang lunatum','Triquetrum bone':'Tulang triquetrum','Pisiform bone':'Tulang pisiform','Trapezium bone':'Tulang trapezium','Trapezoid bone':'Tulang trapezoid','Capitate bone':'Tulang kapitatum','Hamate bone':'Tulang hamatum','Medial cuneiform bone':'Tulang kuneiform medial','Intermediate cuneiform bone':'Tulang kuneiform tengah','Lateral cuneiform bone':'Tulang kuneiform lateral'};
const ord={First:1,Second:2,Third:3,Fourth:4,Fifth:5,Sixth:6,Seventh:7,Eighth:8,Ninth:9,Tenth:10,Eleventh:11,Twelfth:12};
for(const o of inventory.filter(x=>x.collections.includes('1: Skeletal system')&&x.faces>0)){
 const base=o.name.replace(/\.[lr]$/,''),side=o.name.endsWith('.l')?'left':o.name.endsWith('.r')?'right':'none',suffix=side==='left'?' kiri':side==='right'?' kanan':'';
 let name=boneWords[base], region='head',fn='Menyangga dan melindungi struktur kepala.';
 if(/^Vertebra /.test(base)) { name='Ruas tulang belakang '+base.split(' ')[1];region=base.includes('C')?'neck':base.includes('T')?'thorax':'abdomen';fn='Menyangga batang tubuh dan melindungi sumsum tulang belakang.'; }
 const rib=base.match(/^(\w+) rib$/);if(rib&&ord[rib[1]]){name='Rusuk ke-'+ord[rib[1]];region='thorax';fn='Membantu melindungi organ dada dan mendukung gerak pernapasan.';}
 const long=base.match(/^(\w+) (metacarpal|metatarsal) bone$/);if(long&&ord[long[1]]){name='Tulang '+(long[2]==='metacarpal'?'telapak tangan':'telapak kaki')+' ke-'+ord[long[1]];region=long[2]==='metacarpal'?'hand':'foot';fn='Menyangga telapak dan membantu gerakan jari.';}
 const ph=base.match(/^(Proximal|Middle|Distal) phalanx of (\w+) finger of (hand|foot)$/);if(ph){name='Ruas '+({Proximal:'pangkal',Middle:'tengah',Distal:'ujung'}[ph[1]])+' jari '+ord[ph[2][0].toUpperCase()+ph[2].slice(1)]+' '+(ph[3]==='hand'?'tangan':'kaki');region=ph[3]==='hand'?'hand':'foot';fn='Menyangga jari dan membentuk sendi untuk gerakan jari.';}
 if(!name)continue;
 for(const [re,r,f] of [[/Clavicle|Scapula/,'shoulder','Menghubungkan lengan dengan batang tubuh.'],[/Humerus/,'arm','Menyangga lengan atas dan membentuk sendi bahu serta siku.'],[/Radius|Ulna/,'forearm','Menyangga lengan bawah dan mendukung putaran tangan.'],[/Femur/,'thigh','Menopang berat badan dan membentuk sendi panggul serta lutut.'],[/Tibia|Fibula/,'leg','Menyangga tungkai bawah.'],[/Patella/,'knee','Melindungi bagian depan sendi lutut.'],[/Hip bone|Sacrum|Coccyx/,'pelvis','Menyangga panggul dan melindungi organ di dalamnya.'],[/sternum|Xiphoid/,'thorax','Membentuk dinding depan rangka dada.'],[/Atlas|Axis|Hyoid/,'neck','Menopang struktur leher.'],[/Calcaneus|Talus|Navicular|Cuboid|cuneiform/,'ankle','Menyangga kaki dan mendukung pergerakan pergelangan kaki.'],[/Scaphoid|Lunate|Triquetrum|Pisiform|Trapezi|Capitate|Hamate/,'wrist','Membentuk rangka pergelangan tangan.']])if(re.test(base)){region=r;fn=f;}
 add('bone_'+o.name.toLowerCase().replace(/[^a-z0-9]+/g,'_'),name+suffix,[o.name],'bone','skeletal',region,'Bagian rangka: '+name.toLowerCase()+suffix+'.',fn,{side});
}
// External patches come from the source surface, grouped by region and side; no invented mannequin.
for(const [suffix,label,side] of sides) for(const [region,terms] of Object.entries({head:['Frontal region','Parietal region','Occipital region','Temporal region','Buccal region','Nasal region','Mental region','Orbital region','Zygomatic region','Auricular region','Oral region','Parotideomasseteric region','Mastoid region'],neck:['Posterior region of neck','Lateral region of neck','Muscular triangle','Sternocleidomastoid region','Submandibular triangle','Submental triangle','Carotid triangle'],thorax:['Pectoral region','Mammary region','Presternal region','Inframammary region','Lateral region of thorax','Scapular region','Interscapular region','Infrascapular region','Infraclavicular fossa','Greater supraclavicular fossa','Deltopectoral triangle'],abdomen:['Epigastric region','Hypochondriac region','Umbilical region','Lateral region of abdomen','Hypogastric region','Lumbar region'],pelvis:['Gluteal region','Hip region','Sacral region','Inguinal region'],shoulder:['Deltoid region'],arm:['Anterior region of arm','Posterior region of arm'],elbow:['Anterior region of elbow','Posterior region of elbow','Cubital fossa'],forearm:['Anterior region of forearm','Posterior region of forearm'],wrist:['Anterior region of wrist','Posterior region of wrist'],hand:['Dorsum of hand','Palm','Palmar surfaces of digits of hand','Dorsal surfaces of digits of hand'],thigh:['Anterior region of thigh','Posterior region of thigh','Femoral triangle'],knee:['Anterior region of knee','Posterior region of knee','Popliteal fossa'],leg:['Anterior region of leg','Posterior region of leg'],ankle:['Anterior region of ankle','Lateral malleolus','Medial malleolus'],foot:['Dorsum of foot','Sole','Heel region','Dorsal surfaces of digits of foot','Plantar surfaces of digits of foot']})){
 add('skin_'+region+'_'+suffix,'Permukaan '+({head:'kepala',neck:'leher',thorax:'dada',abdomen:'perut',pelvis:'panggul',shoulder:'bahu',arm:'lengan atas',elbow:'siku',forearm:'lengan bawah',wrist:'pergelangan tangan',hand:'tangan',thigh:'paha',knee:'lutut',leg:'tungkai',ankle:'pergelangan kaki',foot:'kaki'}[region])+' '+label,terms.map(n=>n+'.'+suffix),'skin','integument',region,'Permukaan luar tubuh di sisi '+label+'.','Kulit membantu melindungi tubuh, menerima rangsangan, dan mengatur suhu.',{side,definitionDetailed:'Model ini menunjukkan permukaan luar wilayah tubuh, bukan penampang epidermis atau dermis. Jaringan di bawah kulit berbeda dari lapisan kulit.'});
}
expandCatalog(plan,inventory,add);
fs.writeFileSync('sources/anatomy/export-plan.json',JSON.stringify(plan,null,2));fs.writeFileSync('sources/anatomy/missing-source.json',JSON.stringify(missing,null,2));console.log(plan.length+' structures',missing);
