export type FruitShape = 'apple' | 'round' | 'oval' | 'mango' | 'banana' | 'pineapple' | 'papaya' | 'watermelon' | 'melon' | 'grapes' | 'strawberry' | 'avocado' | 'coconut' | 'durian' | 'rambutan' | 'mangosteen' | 'salak' | 'guava' | 'waxapple' | 'starfruit' | 'soursop' | 'jackfruit' | 'dragonfruit' | 'custard' | 'citrus' | 'pear' | 'kiwi' | 'date' | 'pomegranate' | 'persimmon' | 'lychee' | 'peach' | 'cherries' | 'gooseberry';
export type FruitGroup = 'sehari' | 'nusantara' | 'toko';
export interface Fruit {
  id: string; name: string; english: string; group: FruitGroup; shape: FruitShape;
  color: string; accent: string; description: string; skin: string; flesh: string; taste: string; seed: string; fact: string;
}
export const FRUIT_TOOL_ID = 'edukasi-buah';
export const FRUIT_GROUPS = [{id:'all',name:'Semua buah'},{id:'sehari',name:'Sehari-hari'},{id:'nusantara',name:'Pilihan Nusantara'},{id:'toko',name:'Di toko buah'}] as const;

// Descriptions introduce visible characteristics, not nutritional or medical claims.
// Grouping is for discovery, not a claim about geographic origin or availability everywhere.
const rows: [string,string,string,FruitGroup,FruitShape,string,string,string,string,string,string,string,string][] = [
  ['pisang','Pisang','Banana','sehari','banana','#efc63b','#81632d','Pisang tumbuh berkelompok dalam satu tandan. Bentuknya panjang dan melengkung.','Kuning atau hijau','Putih kekuningan','Manis saat matang','Pada pisang yang biasa dimakan, bijinya sangat kecil.','Sekelompok pisang dalam tandan disebut sisir.'],
  ['mangga','Mangga','Mango','sehari','mango','#d8a136','#8baf43','Mangga beraroma harum saat matang. Bentuk dan warnanya beragam, bergantung pada jenisnya.','Hijau, kuning, atau kemerahan','Kuning hingga jingga','Manis atau asam','Satu biji besar dan pipih di tengah.','Mangga memiliki banyak varietas, misalnya arumanis dan gedong.'],
  ['jeruk','Jeruk','Orange','sehari','citrus','#ef8d17','#dca62c','Jeruk memiliki kulit berpori dan daging buah yang terbagi menjadi beberapa siung.','Jingga, kuning, atau hijau','Kuning hingga jingga','Manis dan sedikit asam','Biji kecil dapat ditemukan di dalam siungnya.','Setiap siung jeruk berisi kantong-kantong sari buah.'],
  ['apel','Apel','Apple','sehari','apple','#b92b37','#e5b761','Apel berbentuk membulat dengan lekukan di bagian tangkainya. Daging buahnya terasa renyah.','Merah, hijau, atau kuning','Putih kekuningan','Manis hingga asam','Biji cokelat tersimpan di bagian tengah.','Apel merah dan apel hijau adalah contoh variasi warna apel.'],
  ['semangka','Semangka','Watermelon','sehari','watermelon','#368345','#b9cb58','Semangka memiliki kulit tebal dan daging buah yang berair. Ukurannya dapat cukup besar.','Hijau, sering bergaris','Merah atau kuning','Manis','Biji dapat berwarna hitam, cokelat, atau putih.','Ada semangka berdaging merah dan ada yang berdaging kuning.'],
  ['melon','Melon','Melon','sehari','melon','#a8a261','#ddd5a3','Melon berbentuk bulat atau lonjong. Sebagian jenisnya memiliki pola seperti jaring pada kulit.','Hijau atau kuning kecokelatan','Hijau muda, putih, atau jingga','Manis saat matang','Banyak biji berkumpul di rongga tengah.','Tidak semua melon memiliki kulit berjaring.'],
  ['pepaya','Pepaya','Papaya','sehari','papaya','#dba32e','#84a241','Pepaya memiliki bentuk lonjong. Saat dibelah, terlihat rongga dengan banyak biji kecil.','Hijau yang berubah kuning saat matang','Jingga hingga kemerahan','Manis saat matang','Banyak biji bulat berwarna hitam.','Biji pepaya menempel di dinding rongga bagian dalam.'],
  ['nanas','Nanas','Pineapple','sehari','pineapple','#be9230','#5a8739','Nanas mudah dikenali dari kulit berpola dan mahkota daun di atasnya.','Kuning kecokelatan atau hijau','Kuning','Manis dan asam','Biji biasanya tidak terlihat pada nanas yang dijual.','Nanas terbentuk dari kumpulan bunga yang menyatu menjadi satu buah.'],
  ['anggur','Anggur','Grape','sehari','grapes','#57315d','#a26a92','Anggur tumbuh berkelompok dalam satu rangkaian. Buahnya kecil dan berkulit tipis.','Ungu, merah, atau hijau','Bening kehijauan','Manis hingga asam','Ada anggur berbiji dan ada yang tanpa biji.','Anggur yang dikeringkan disebut kismis.'],
  ['stroberi','Stroberi','Strawberry','sehari','strawberry','#c82e31','#edc875','Stroberi berwarna merah saat matang dan permukaannya dipenuhi bintik-bintik kecil.','Merah berbintik','Merah dan putih','Manis dan asam','Bintik kecil di permukaan menyimpan bijinya.','Stroberi memiliki kelopak daun hijau di bagian atas.'],
  ['alpukat','Alpukat','Avocado','sehari','avocado','#456c36','#709049','Alpukat memiliki daging buah yang lembut. Bentuknya bisa membulat atau menyerupai buah pir.','Hijau hingga ungu gelap','Kuning kehijauan','Gurih dan lembut','Satu biji besar dan bulat.','Daging alpukat di dekat kulit biasanya lebih hijau.'],
  ['kelapa','Kelapa','Coconut','sehari','coconut','#58894b','#a0a55e','Kelapa memiliki lapisan sabut dan tempurung keras. Di dalamnya terdapat air serta daging buah.','Hijau atau kuning; sabut tua kecokelatan','Putih','Airnya ringan dan agak manis','Buah kelapa memiliki satu biji besar.','Sabut berada di luar tempurung kelapa.'],
  ['durian','Durian','Durian','nusantara','durian','#8b922c','#c3ba56','Durian memiliki kulit berduri tajam dan aroma yang kuat. Daging buahnya berada dalam beberapa ruang.','Hijau hingga cokelat kekuningan','Kuning pucat atau krem','Manis dan kaya rasa','Biji besar berada di dalam daging buah.','Minta bantuan orang dewasa untuk membuka kulit durian.'],
  ['rambutan','Rambutan','Rambutan','nusantara','rambutan','#b42e24','#d8a551','Rambutan memiliki kulit dengan rambut-rambut lentur. Di balik kulitnya terdapat daging buah berair.','Merah atau kuning','Putih bening','Manis, kadang sedikit asam','Satu biji di tengah.','Namanya mengingatkan kita pada rambut di kulit buahnya.'],
  ['manggis','Manggis','Mangosteen','nusantara','mangosteen','#4b2144','#7c3b55','Manggis memiliki kulit tebal berwarna ungu gelap. Daging buahnya tersusun menjadi beberapa bagian putih.','Ungu gelap','Putih','Manis dan sedikit asam','Sebagian bagian dagingnya mengandung biji.','Bagian hijau di atas manggis adalah kelopak yang tetap menempel.'],
  ['salak','Salak','Snake fruit','nusantara','salak','#713d24','#ba7842','Salak memiliki kulit bersisik dan ujung meruncing. Dagingnya terbagi menjadi beberapa bagian.','Cokelat bersisik','Putih krem hingga kekuningan','Manis, asam, atau sedikit sepat','Biji keras berwarna cokelat gelap.','Pola kulit salak sering dibandingkan dengan sisik ular.'],
  ['duku','Duku','Duku','nusantara','round','#c0a062','#e0c78c','Duku kecil dan membulat. Kulitnya dikupas untuk menemukan daging buah yang terbagi dalam beberapa bagian.','Kuning kecokelatan','Putih bening','Manis saat matang','Sebagian bagian buah berisi biji.','Duku dan langsat berkerabat dekat, tetapi penampilannya tidak persis sama.'],
  ['lengkeng','Lengkeng','Longan','nusantara','round','#a9814e','#c5a87e','Lengkeng berbentuk bulat kecil dengan kulit tipis yang agak kaku.','Cokelat muda','Putih bening','Manis','Satu biji bulat mengilap berwarna gelap.','Lengkeng juga sering disebut kelengkeng.'],
  ['jambu-biji','Jambu Biji','Guava','sehari','guava','#a1b849','#d3cb6d','Jambu biji berbentuk bulat atau agak lonjong. Daging buahnya bisa putih atau merah muda.','Hijau hingga kuning','Putih atau merah muda','Manis hingga asam','Biji-biji kecil terkumpul di bagian tengah.','Ada jenis jambu biji dengan jumlah biji yang lebih sedikit.'],
  ['jambu-air','Jambu Air','Water apple','nusantara','waxapple','#d83e4c','#f0a18f','Jambu air memiliki bentuk menyerupai lonceng. Daging buahnya renyah dan berair.','Merah, merah muda, atau hijau','Putih atau kemerahan','Segar, sedikit manis','Dapat memiliki biji di rongga tengah.','Bagian bawah jambu air lebih lebar daripada bagian tangkainya.'],
  ['belimbing','Belimbing','Star fruit','nusantara','starfruit','#e2c333','#86a144','Belimbing memiliki rusuk memanjang yang membuat bentuknya khas.','Hijau hingga kuning','Kuning bening','Manis dan asam','Biji pipih berada di bagian tengah.','Irisan melintang belimbing tampak seperti bintang.'],
  ['sawo','Sawo','Sapodilla','nusantara','oval','#987049','#caa47a','Sawo berkulit cokelat dengan daging buah yang lembut saat matang.','Cokelat','Cokelat muda','Manis saat matang','Biji mengilap berwarna cokelat gelap atau hitam.','Sawo matang memiliki tekstur halus yang sedikit berbutir.'],
  ['sirsak','Sirsak','Soursop','nusantara','soursop','#5b8e48','#a4b875','Sirsak berbentuk tidak selalu simetris. Kulitnya hijau dengan tonjolan seperti duri yang pendek.','Hijau','Putih','Manis dan asam','Banyak biji berwarna gelap.','Daging sirsak tersusun dalam serat-serat yang lembut.'],
  ['nangka','Nangka','Jackfruit','nusantara','jackfruit','#809239','#c2b055','Nangka dapat tumbuh sangat besar. Di dalam kulitnya terdapat banyak bagian daging buah.','Hijau hingga kuning kecokelatan','Kuning saat matang','Manis saat matang','Setiap bagian daging biasanya membungkus satu biji.','Buah nangka dapat tumbuh pada batang dan cabang yang besar.'],
  ['buah-naga','Buah Naga','Dragon fruit','sehari','dragonfruit','#d33865','#8ba44f','Buah naga memiliki kulit cerah dengan sisik seperti daun. Daging buahnya penuh bintik biji kecil.','Merah muda atau kuning','Putih atau merah keunguan','Manis ringan','Banyak biji hitam yang sangat kecil.','Buah naga tumbuh pada tanaman kaktus.'],
  ['markisa','Markisa','Passion fruit','nusantara','round','#78506c','#b49352','Markisa memiliki kulit yang cukup keras. Isinya berupa biji yang terbungkus sari buah.','Ungu atau kuning','Kuning jingga di sekitar biji','Asam hingga manis','Banyak biji hitam terbungkus lapisan berair.','Kulit beberapa jenis markisa menjadi berkerut saat matang.'],
  ['srikaya','Srikaya','Sugar apple','nusantara','custard','#90a760','#c4cb8d','Srikaya memiliki kulit dengan bagian-bagian menonjol seperti sisik besar.','Hijau','Putih krem','Manis','Biji gelap berada di antara daging buah.','Bagian kulit srikaya tampak seperti tersusun dari banyak kepingan.'],
  ['kedondong','Kedondong','Ambarella','nusantara','oval','#95a641','#d0c45a','Kedondong berbentuk lonjong. Daging buahnya renyah dengan biji berserat di dalamnya.','Hijau hingga kuning','Putih kekuningan','Asam, kadang manis saat matang','Satu biji besar dengan serat-serat.','Kedondong sering dijumpai sebagai salah satu buah dalam rujak.'],
  ['jeruk-bali','Jeruk Bali','Pomelo','nusantara','pear','#acc84f','#cbd67a','Jeruk bali adalah jenis jeruk berukuran besar dengan kulit yang tebal.','Hijau atau kuning','Putih atau merah muda','Manis, asam, kadang sedikit pahit','Biji dapat ditemukan di dalam siung.','Lapisan putih di bawah kulitnya jauh lebih tebal daripada jeruk kecil.'],
  ['jeruk-nipis','Jeruk Nipis','Lime','sehari','citrus','#5b9d39','#a4c44f','Jeruk nipis berbentuk kecil membulat. Kulit dan air buahnya memiliki aroma yang khas.','Hijau hingga kuning','Kuning kehijauan','Asam','Biji kecil di dalam siung.','Jeruk nipis sering digunakan untuk memberi rasa pada makanan dan minuman.'],
  ['lemon','Lemon','Lemon','toko','oval','#e6c833','#f8e064','Lemon memiliki bentuk lonjong dengan ujung sedikit menonjol.','Kuning','Kuning pucat','Asam','Biji kecil di dalam siung.','Aroma lemon juga terdapat pada bagian kulitnya.'],
  ['pir','Pir','Pear','toko','pear','#bdbe58','#d8c987','Pir memiliki banyak bentuk, dari membulat sampai berleher ramping.','Hijau, kuning, atau cokelat muda','Putih krem','Manis','Biji kecil berwarna cokelat di tengah.','Sebagian pir renyah, sementara jenis lain lebih lembut saat matang.'],
  ['kiwi','Kiwi','Kiwifruit','toko','kiwi','#8b7145','#c5a37b','Kiwi berkulit cokelat, biasanya dengan rambut halus. Bagian dalamnya berwarna cerah.','Cokelat','Hijau atau kuning','Manis dan asam','Biji kecil hitam mengelilingi bagian tengah.','Daging kiwi tampak berpola memancar dari pusat buah.'],
  ['kurma','Kurma','Date','toko','date','#86502d','#b57a43','Kurma memiliki bentuk lonjong. Kurma yang matang atau dikeringkan dapat terasa lembut dan lengket.','Kuning, merah, atau cokelat sesuai tahap kematangan','Cokelat kekuningan','Manis','Satu biji memanjang di tengah.','Kurma tumbuh pada pohon palem kurma.'],
  ['delima','Delima','Pomegranate','toko','pomegranate','#b43f35','#ddb15f','Delima memiliki kulit tebal dan bagian atas seperti mahkota kecil.','Merah, merah muda, atau kuning','Butiran bening hingga merah','Manis dan asam','Setiap butiran berair membungkus biji.','Di dalam delima ada sekat-sekat putih yang memisahkan kelompok bijinya.'],
  ['kesemek','Kesemek','Persimmon','toko','persimmon','#e18a26','#d8b457','Kesemek tampak membulat dan agak pipih. Kelopak besar tetap melekat di atasnya.','Kuning hingga jingga','Kuning jingga','Manis saat siap dimakan; dapat sepat jika belum siap','Sebagian buah memiliki biji, sebagian tidak.','Lapisan putih pada sebagian kesemek di pasar berasal dari pengolahan, bukan warna kulit aslinya.'],
  ['leci','Leci','Lychee','toko','lychee','#c75157','#edae98','Leci berukuran kecil dengan kulit kasar. Daging buahnya putih bening setelah kulit dikupas.','Merah atau merah muda','Putih bening','Manis','Satu biji cokelat di tengah.','Leci, lengkeng, dan rambutan termasuk keluarga tumbuhan yang sama.'],
  ['plum','Plum','Plum','toko','oval','#4c325b','#9c6994','Plum memiliki kulit halus dan daging buah yang berair. Warnanya beragam.','Ungu, merah, atau kuning','Kuning, merah, atau jingga','Manis dan asam','Satu biji keras di tengah.','Lapisan tipis seperti bedak pada kulit beberapa plum merupakan lapisan lilin alami.'],
  ['persik','Persik','Peach','toko','peach','#e5a058','#cc5960','Persik berbentuk membulat dengan satu alur di permukaannya. Kulitnya memiliki rambut sangat halus.','Kuning dan kemerahan','Kuning atau putih','Manis dan sedikit asam','Satu biji keras berlekuk di tengah.','Rambut halus membedakan kulit persik dari nektarin yang licin.'],
  ['cempedak','Cempedak','Cempedak','nusantara','jackfruit','#a59139','#c9ac55','Cempedak berkerabat dengan nangka. Bentuknya memanjang dan aromanya kuat saat matang.','Hijau hingga kuning kecokelatan','Kuning sampai jingga','Manis','Satu biji pada setiap bagian daging buah.','Daging cempedak matang biasanya lebih lembut daripada daging nangka.'],
  ['langsat','Langsat','Langsat','nusantara','oval','#c4ac70','#e7d6a8','Langsat memiliki kulit tipis dan sering tumbuh dalam rangkaian yang rapat.','Kuning pucat','Putih bening','Manis dan asam','Biji berada pada beberapa bagian daging buah.','Langsat biasanya lebih lonjong daripada duku.'],
  ['matoa','Matoa','Matoa','nusantara','oval','#8d5b40','#b99359','Matoa memiliki kulit agak keras dengan daging buah bening yang menyelimuti biji.','Hijau, merah kecokelatan, atau gelap','Putih bening','Manis','Satu biji besar di tengah.','Matoa dikenal sebagai salah satu buah khas Papua.'],
  ['blewah','Blewah','Cantaloupe','nusantara','melon','#d2ae66','#99a256','Blewah berkerabat dengan melon. Kulitnya sering memiliki alur memanjang.','Kuning jingga dengan alur','Jingga pucat','Manis ringan dan harum','Banyak biji di rongga tengah.','Daging blewah sering diserut untuk campuran minuman.'],
  ['terong-belanda','Terong Belanda','Tamarillo','nusantara','oval','#a44031','#dd804d','Terong belanda memiliki bentuk seperti telur. Daging dan bijinya berada di balik kulit yang halus.','Merah, jingga, atau kuning','Jingga kemerahan','Asam dan sedikit manis','Biji-biji kecil di dalam daging berair.','Buah ini juga dikenal dengan nama tamarillo.'],
  ['ceri','Ceri','Cherry','toko','cherries','#a52037','#e35859','Ceri berukuran kecil, membulat, dan sering memiliki tangkai yang panjang.','Merah hingga merah gelap','Merah atau kekuningan','Manis atau asam','Satu biji keras di tengah.','Tangkai ceri jauh lebih panjang daripada ukuran buahnya.'],
  ['cermai','Cermai','Star gooseberry','nusantara','gooseberry','#c6cb68','#e6df99','Cermai berbentuk kecil dan beralur. Buahnya sering tumbuh bergerombol di cabang.','Hijau pucat hingga kuning','Kuning pucat','Asam','Biji berada di bagian tengah yang keras.','Cermai sering diolah menjadi manisan.'],
  ['jamblang','Jamblang','Java plum','nusantara','oval','#30203e','#755377','Jamblang berbentuk lonjong kecil dan berwarna gelap saat matang.','Ungu sangat gelap','Putih keunguan','Manis, asam, dan sepat','Satu biji di tengah.','Jamblang juga dikenal dengan nama duwet.'],
  ['jambu-bol','Jambu Bol','Malay apple','nusantara','waxapple','#983047','#d86676','Jambu bol memiliki bentuk membulat sampai agak lonjong. Dagingnya lebih tebal daripada jambu air.','Merah hingga merah tua','Putih','Manis ringan','Biasanya terdapat biji besar di tengah.','Jambu bol memiliki aroma yang khas ketika matang.'],
];
export const FRUITS: Fruit[] = rows.map(([id,name,english,group,shape,color,accent,description,skin,flesh,taste,seed,fact]) => ({id,name,english,group,shape,color,accent,description,skin,flesh,taste,seed,fact}));
export const FRUIT_BY_ID = new Map(FRUITS.map(f=>[f.id,f]));
export const fruitMatches = (f: Fruit, query: string) => `${f.name} ${f.english} ${f.id} ${f.id==='lengkeng'?'kelengkeng':''} ${f.id==='jamblang'?'duwet':''}`.toLowerCase().includes(query.trim().toLowerCase());
export const FRUIT_SOURCES = [
  {name:'Kementerian Pertanian · Buah Nusantara',url:'https://www.pertanian.go.id/home/?act=view&id=1838&show=news'},
  {name:'Royal Horticultural Society · Buah-buahan',url:'https://www.rhs.org.uk/fruit'},
];
