// Soal game "Jurus · Dojo Ninja (konsep: fungsi)" — 100 soal (10 Level × 10 coding) untuk usia 3–8 tahun.
// DIBUAT OTOMATIS oleh scripts/gen-prog.ts (lihat src/lib/koding/gen-prog.ts); jangan diedit manual.

import type { JurusLevel } from './worlds';

export const JURUS: JurusLevel[] = [{"id":"j1","world":0,"palette":["pukul","tendang","jurus"],"best":5,"limit":5,"hint":"Blok baru: JURUS ⚡! Susun gerakan di kotak Jurus, lalu panggil jurus di program utama.","solution":{"main":[{"id":"b1","t":"call"},
{"id":"b2","t":"call"}],"jurus":[{"id":"b3","t":"act","a":"tendang"},
{"id":"b4","t":"act","a":"tendang"},
{"id":"b5","t":"act","a":"pukul"}]},"target":["tendang","tendang","pukul","tendang","tendang","pukul"]},
{"id":"j2","world":0,"palette":["pukul","tendang","jurus"],"best":5,"limit":5,"hint":"Sensei mengulang gerakan yang sama. Jadikan jurus!","solution":{"main":[{"id":"b1","t":"call"},
{"id":"b2","t":"call"}],"jurus":[{"id":"b3","t":"act","a":"tendang"},
{"id":"b4","t":"act","a":"pukul"},
{"id":"b5","t":"act","a":"tendang"}]},"target":["tendang","pukul","tendang","tendang","pukul","tendang"]},
{"id":"j3","world":0,"palette":["pukul","tendang","jurus"],"best":5,"limit":5,"hint":"Sensei mengulang gerakan yang sama. Jadikan jurus!","solution":{"main":[{"id":"b1","t":"call"},
{"id":"b2","t":"call"}],"jurus":[{"id":"b3","t":"act","a":"tendang"},
{"id":"b4","t":"act","a":"pukul"},
{"id":"b5","t":"act","a":"pukul"}]},"target":["tendang","pukul","pukul","tendang","pukul","pukul"]},
{"id":"j4","world":0,"palette":["pukul","tendang","jurus"],"best":6,"limit":7,"hint":"Sensei mengulang gerakan yang sama. Jadikan jurus!","solution":{"main":[{"id":"b1","t":"call"},
{"id":"b2","t":"call"},
{"id":"b3","t":"call"}],"jurus":[{"id":"b4","t":"act","a":"pukul"},
{"id":"b5","t":"act","a":"pukul"},
{"id":"b6","t":"act","a":"tendang"}]},"target":["pukul","pukul","tendang","pukul","pukul","tendang","pukul","pukul","tendang"]},
{"id":"j5","world":0,"palette":["pukul","tendang","jurus"],"best":6,"limit":7,"hint":"Sensei mengulang gerakan yang sama. Jadikan jurus!","solution":{"main":[{"id":"b1","t":"call"},
{"id":"b2","t":"call"},
{"id":"b3","t":"call"}],"jurus":[{"id":"b4","t":"act","a":"tendang"},
{"id":"b5","t":"act","a":"pukul"},
{"id":"b6","t":"act","a":"tendang"}]},"target":["tendang","pukul","tendang","tendang","pukul","tendang","tendang","pukul","tendang"]},
{"id":"j6","world":0,"palette":["pukul","tendang","jurus"],"best":6,"limit":7,"hint":"Sensei mengulang gerakan yang sama. Jadikan jurus!","solution":{"main":[{"id":"b1","t":"call"},
{"id":"b2","t":"call"}],"jurus":[{"id":"b3","t":"act","a":"pukul"},
{"id":"b4","t":"act","a":"tendang"},
{"id":"b5","t":"act","a":"pukul"},
{"id":"b6","t":"act","a":"tendang"}]},"target":["pukul","tendang","pukul","tendang","pukul","tendang","pukul","tendang"]},
{"id":"j7","world":0,"palette":["pukul","tendang","jurus"],"best":6,"limit":7,"hint":"Sensei mengulang gerakan yang sama. Jadikan jurus!","solution":{"main":[{"id":"b1","t":"call"},
{"id":"b2","t":"call"}],"jurus":[{"id":"b3","t":"act","a":"pukul"},
{"id":"b4","t":"act","a":"pukul"},
{"id":"b5","t":"act","a":"tendang"},
{"id":"b6","t":"act","a":"tendang"}]},"target":["pukul","pukul","tendang","tendang","pukul","pukul","tendang","tendang"]},
{"id":"j8","world":0,"palette":["pukul","tendang","jurus"],"best":6,"limit":7,"hint":"Sensei mengulang gerakan yang sama. Jadikan jurus!","solution":{"main":[{"id":"b1","t":"call"},
{"id":"b2","t":"call"},
{"id":"b3","t":"call"}],"jurus":[{"id":"b4","t":"act","a":"pukul"},
{"id":"b5","t":"act","a":"tendang"},
{"id":"b6","t":"act","a":"tendang"}]},"target":["pukul","tendang","tendang","pukul","tendang","tendang","pukul","tendang","tendang"]},
{"id":"j9","world":0,"palette":["pukul","tendang","jurus"],"best":6,"limit":7,"hint":"Sensei mengulang gerakan yang sama. Jadikan jurus!","solution":{"main":[{"id":"b1","t":"call"},
{"id":"b2","t":"call"}],"jurus":[{"id":"b3","t":"act","a":"pukul"},
{"id":"b4","t":"act","a":"pukul"},
{"id":"b5","t":"act","a":"tendang"},
{"id":"b6","t":"act","a":"pukul"}]},"target":["pukul","pukul","tendang","pukul","pukul","pukul","tendang","pukul"]},
{"id":"j10","world":0,"palette":["pukul","tendang","jurus"],"best":7,"limit":8,"hint":"Sensei mengulang gerakan yang sama. Jadikan jurus!","solution":{"main":[{"id":"b1","t":"call"},
{"id":"b2","t":"call"},
{"id":"b3","t":"call"}],"jurus":[{"id":"b4","t":"act","a":"tendang"},
{"id":"b5","t":"act","a":"pukul"},
{"id":"b6","t":"act","a":"tendang"},
{"id":"b7","t":"act","a":"tendang"}]},"target":["tendang","pukul","tendang","tendang","tendang","pukul","tendang","tendang","tendang","pukul","tendang","tendang"]},
{"id":"j11","world":1,"palette":["pukul","tendang","tangkis","jurus"],"best":5,"limit":5,"hint":"Gerakan baru: tangkis! Perhatikan urutan Sensei.","solution":{"main":[{"id":"b1","t":"call"},
{"id":"b2","t":"call"}],"jurus":[{"id":"b3","t":"act","a":"pukul"},
{"id":"b4","t":"act","a":"tangkis"},
{"id":"b5","t":"act","a":"tendang"}]},"target":["pukul","tangkis","tendang","pukul","tangkis","tendang"]},
{"id":"j12","world":1,"palette":["pukul","tendang","tangkis","jurus"],"best":5,"limit":5,"hint":"Gerakan baru: tangkis! Perhatikan urutan Sensei.","solution":{"main":[{"id":"b1","t":"call"},
{"id":"b2","t":"call"}],"jurus":[{"id":"b3","t":"act","a":"tendang"},
{"id":"b4","t":"act","a":"tangkis"},
{"id":"b5","t":"act","a":"pukul"}]},"target":["tendang","tangkis","pukul","tendang","tangkis","pukul"]},
{"id":"j13","world":1,"palette":["pukul","tendang","tangkis","jurus"],"best":6,"limit":7,"hint":"Gerakan baru: tangkis! Perhatikan urutan Sensei.","solution":{"main":[{"id":"b1","t":"call"},
{"id":"b2","t":"call"},
{"id":"b3","t":"call"}],"jurus":[{"id":"b4","t":"act","a":"pukul"},
{"id":"b5","t":"act","a":"tendang"},
{"id":"b6","t":"act","a":"tangkis"}]},"target":["pukul","tendang","tangkis","pukul","tendang","tangkis","pukul","tendang","tangkis"]},
{"id":"j14","world":1,"palette":["pukul","tendang","tangkis","jurus"],"best":6,"limit":7,"hint":"Gerakan baru: tangkis! Perhatikan urutan Sensei.","solution":{"main":[{"id":"b1","t":"call"},
{"id":"b2","t":"call"}],"jurus":[{"id":"b3","t":"act","a":"pukul"},
{"id":"b4","t":"act","a":"pukul"},
{"id":"b5","t":"act","a":"tangkis"},
{"id":"b6","t":"act","a":"tendang"}]},"target":["pukul","pukul","tangkis","tendang","pukul","pukul","tangkis","tendang"]},
{"id":"j15","world":1,"palette":["pukul","tendang","tangkis","jurus"],"best":6,"limit":7,"hint":"Gerakan baru: tangkis! Perhatikan urutan Sensei.","solution":{"main":[{"id":"b1","t":"call"},
{"id":"b2","t":"call"}],"jurus":[{"id":"b3","t":"act","a":"tendang"},
{"id":"b4","t":"act","a":"pukul"},
{"id":"b5","t":"act","a":"tangkis"},
{"id":"b6","t":"act","a":"tendang"}]},"target":["tendang","pukul","tangkis","tendang","tendang","pukul","tangkis","tendang"]},
{"id":"j16","world":1,"palette":["pukul","tendang","tangkis","jurus"],"best":6,"limit":6,"hint":"Gerakan baru: tangkis! Perhatikan urutan Sensei.","solution":{"main":[{"id":"b1","t":"call"},
{"id":"b2","t":"act","a":"tangkis"},
{"id":"b3","t":"call"}],"jurus":[{"id":"b4","t":"act","a":"tendang"},
{"id":"b5","t":"act","a":"pukul"},
{"id":"b6","t":"act","a":"tangkis"}]},"target":["tendang","pukul","tangkis","tangkis","tendang","pukul","tangkis"]},
{"id":"j17","world":1,"palette":["pukul","tendang","tangkis","jurus"],"best":6,"limit":6,"hint":"Gerakan baru: tangkis! Perhatikan urutan Sensei.","solution":{"main":[{"id":"b1","t":"call"},
{"id":"b2","t":"act","a":"tendang"},
{"id":"b3","t":"call"}],"jurus":[{"id":"b4","t":"act","a":"tendang"},
{"id":"b5","t":"act","a":"tangkis"},
{"id":"b6","t":"act","a":"pukul"}]},"target":["tendang","tangkis","pukul","tendang","tendang","tangkis","pukul"]},
{"id":"j18","world":1,"palette":["pukul","tendang","tangkis","jurus"],"best":6,"limit":7,"hint":"Gerakan baru: tangkis! Perhatikan urutan Sensei.","solution":{"main":[{"id":"b1","t":"call"},
{"id":"b2","t":"call"}],"jurus":[{"id":"b3","t":"act","a":"tangkis"},
{"id":"b4","t":"act","a":"tendang"},
{"id":"b5","t":"act","a":"pukul"},
{"id":"b6","t":"act","a":"pukul"}]},"target":["tangkis","tendang","pukul","pukul","tangkis","tendang","pukul","pukul"]},
{"id":"j19","world":1,"palette":["pukul","tendang","tangkis","jurus"],"best":7,"limit":8,"hint":"Gerakan baru: tangkis! Perhatikan urutan Sensei.","solution":{"main":[{"id":"b1","t":"call"},
{"id":"b2","t":"call"},
{"id":"b3","t":"call"}],"jurus":[{"id":"b4","t":"act","a":"tendang"},
{"id":"b5","t":"act","a":"pukul"},
{"id":"b6","t":"act","a":"tangkis"},
{"id":"b7","t":"act","a":"pukul"}]},"target":["tendang","pukul","tangkis","pukul","tendang","pukul","tangkis","pukul","tendang","pukul","tangkis","pukul"]},
{"id":"j20","world":1,"palette":["pukul","tendang","tangkis","jurus"],"best":7,"limit":8,"hint":"Gerakan baru: tangkis! Perhatikan urutan Sensei.","solution":{"main":[{"id":"b1","t":"call"},
{"id":"b2","t":"act","a":"tangkis"},
{"id":"b3","t":"call"}],"jurus":[{"id":"b4","t":"act","a":"pukul"},
{"id":"b5","t":"act","a":"pukul"},
{"id":"b6","t":"act","a":"tangkis"},
{"id":"b7","t":"act","a":"tendang"}]},"target":["pukul","pukul","tangkis","tendang","tangkis","pukul","pukul","tangkis","tendang"]},
{"id":"j21","world":2,"palette":["pukul","tendang","tangkis","lompat","jurus"],"best":5,"limit":5,"hint":"Gerakan baru: lompat! Ada gerakan lain di antara jurus.","solution":{"main":[{"id":"b1","t":"call"},
{"id":"b2","t":"call"}],"jurus":[{"id":"b3","t":"act","a":"pukul"},
{"id":"b4","t":"act","a":"tendang"},
{"id":"b5","t":"act","a":"lompat"}]},"target":["pukul","tendang","lompat","pukul","tendang","lompat"]},
{"id":"j22","world":2,"palette":["pukul","tendang","tangkis","lompat","jurus"],"best":6,"limit":6,"hint":"Gerakan baru: lompat! Ada gerakan lain di antara jurus.","solution":{"main":[{"id":"b1","t":"call"},
{"id":"b2","t":"act","a":"tangkis"},
{"id":"b3","t":"call"}],"jurus":[{"id":"b4","t":"act","a":"lompat"},
{"id":"b5","t":"act","a":"tendang"},
{"id":"b6","t":"act","a":"pukul"}]},"target":["lompat","tendang","pukul","tangkis","lompat","tendang","pukul"]},
{"id":"j23","world":2,"palette":["pukul","tendang","tangkis","lompat","jurus"],"best":6,"limit":7,"hint":"Gerakan baru: lompat! Ada gerakan lain di antara jurus.","solution":{"main":[{"id":"b1","t":"call"},
{"id":"b2","t":"call"},
{"id":"b3","t":"call"}],"jurus":[{"id":"b4","t":"act","a":"pukul"},
{"id":"b5","t":"act","a":"tangkis"},
{"id":"b6","t":"act","a":"tendang"}]},"target":["pukul","tangkis","tendang","pukul","tangkis","tendang","pukul","tangkis","tendang"]},
{"id":"j24","world":2,"palette":["pukul","tendang","tangkis","lompat","jurus"],"best":6,"limit":7,"hint":"Gerakan baru: lompat! Ada gerakan lain di antara jurus.","solution":{"main":[{"id":"b1","t":"call"},
{"id":"b2","t":"call"}],"jurus":[{"id":"b3","t":"act","a":"lompat"},
{"id":"b4","t":"act","a":"tangkis"},
{"id":"b5","t":"act","a":"tendang"},
{"id":"b6","t":"act","a":"pukul"}]},"target":["lompat","tangkis","tendang","pukul","lompat","tangkis","tendang","pukul"]},
{"id":"j25","world":2,"palette":["pukul","tendang","tangkis","lompat","jurus"],"best":7,"limit":8,"hint":"Gerakan baru: lompat! Ada gerakan lain di antara jurus.","solution":{"main":[{"id":"b1","t":"call"},
{"id":"b2","t":"act","a":"lompat"},
{"id":"b3","t":"call"}],"jurus":[{"id":"b4","t":"act","a":"lompat"},
{"id":"b5","t":"act","a":"tangkis"},
{"id":"b6","t":"act","a":"pukul"},
{"id":"b7","t":"act","a":"pukul"}]},"target":["lompat","tangkis","pukul","pukul","lompat","lompat","tangkis","pukul","pukul"]},
{"id":"j26","world":2,"palette":["pukul","tendang","tangkis","lompat","jurus"],"best":6,"limit":7,"hint":"Gerakan baru: lompat! Ada gerakan lain di antara jurus.","solution":{"main":[{"id":"b1","t":"call"},
{"id":"b2","t":"call"}],"jurus":[{"id":"b3","t":"act","a":"tendang"},
{"id":"b4","t":"act","a":"tangkis"},
{"id":"b5","t":"act","a":"pukul"},
{"id":"b6","t":"act","a":"lompat"}]},"target":["tendang","tangkis","pukul","lompat","tendang","tangkis","pukul","lompat"]},
{"id":"j27","world":2,"palette":["pukul","tendang","tangkis","lompat","jurus"],"best":7,"limit":8,"hint":"Gerakan baru: lompat! Ada gerakan lain di antara jurus.","solution":{"main":[{"id":"b1","t":"call"},
{"id":"b2","t":"act","a":"lompat"},
{"id":"b3","t":"call"}],"jurus":[{"id":"b4","t":"act","a":"pukul"},
{"id":"b5","t":"act","a":"tendang"},
{"id":"b6","t":"act","a":"tangkis"},
{"id":"b7","t":"act","a":"lompat"}]},"target":["pukul","tendang","tangkis","lompat","lompat","pukul","tendang","tangkis","lompat"]},
{"id":"j28","world":2,"palette":["pukul","tendang","tangkis","lompat","jurus"],"best":6,"limit":7,"hint":"Gerakan baru: lompat! Ada gerakan lain di antara jurus.","solution":{"main":[{"id":"b1","t":"call"},
{"id":"b2","t":"call"}],"jurus":[{"id":"b3","t":"act","a":"tangkis"},
{"id":"b4","t":"act","a":"tangkis"},
{"id":"b5","t":"act","a":"lompat"},
{"id":"b6","t":"act","a":"pukul"}]},"target":["tangkis","tangkis","lompat","pukul","tangkis","tangkis","lompat","pukul"]},
{"id":"j29","world":2,"palette":["pukul","tendang","tangkis","lompat","jurus"],"best":7,"limit":8,"hint":"Gerakan baru: lompat! Ada gerakan lain di antara jurus.","solution":{"main":[{"id":"b1","t":"call"},
{"id":"b2","t":"call"},
{"id":"b3","t":"call"}],"jurus":[{"id":"b4","t":"act","a":"pukul"},
{"id":"b5","t":"act","a":"tendang"},
{"id":"b6","t":"act","a":"tangkis"},
{"id":"b7","t":"act","a":"lompat"}]},"target":["pukul","tendang","tangkis","lompat","pukul","tendang","tangkis","lompat","pukul","tendang","tangkis","lompat"]},
{"id":"j30","world":2,"palette":["pukul","tendang","tangkis","lompat","jurus"],"best":8,"limit":9,"hint":"Gerakan baru: lompat! Ada gerakan lain di antara jurus.","solution":{"main":[{"id":"b1","t":"call"},
{"id":"b2","t":"act","a":"tendang"},
{"id":"b3","t":"call"},
{"id":"b4","t":"act","a":"pukul"}],"jurus":[{"id":"b5","t":"act","a":"lompat"},
{"id":"b6","t":"act","a":"tangkis"},
{"id":"b7","t":"act","a":"tendang"},
{"id":"b8","t":"act","a":"pukul"}]},"target":["lompat","tangkis","tendang","pukul","tendang","lompat","tangkis","tendang","pukul","pukul"]},
{"id":"j31","world":3,"palette":["pukul","tendang","tangkis","lompat","putar","jurus"],"best":5,"limit":5,"hint":"Gerakan baru: putar! Lima gerakan ninja lengkap.","solution":{"main":[{"id":"b1","t":"call"},
{"id":"b2","t":"call"}],"jurus":[{"id":"b3","t":"act","a":"tendang"},
{"id":"b4","t":"act","a":"pukul"},
{"id":"b5","t":"act","a":"tangkis"}]},"target":["tendang","pukul","tangkis","tendang","pukul","tangkis"]},
{"id":"j32","world":3,"palette":["pukul","tendang","tangkis","lompat","putar","jurus"],"best":6,"limit":7,"hint":"Gerakan baru: putar! Lima gerakan ninja lengkap.","solution":{"main":[{"id":"b1","t":"call"},
{"id":"b2","t":"call"},
{"id":"b3","t":"call"}],"jurus":[{"id":"b4","t":"act","a":"pukul"},
{"id":"b5","t":"act","a":"putar"},
{"id":"b6","t":"act","a":"lompat"}]},"target":["pukul","putar","lompat","pukul","putar","lompat","pukul","putar","lompat"]},
{"id":"j33","world":3,"palette":["pukul","tendang","tangkis","lompat","putar","jurus"],"best":6,"limit":6,"hint":"Gerakan baru: putar! Lima gerakan ninja lengkap.","solution":{"main":[{"id":"b1","t":"call"},
{"id":"b2","t":"act","a":"tangkis"},
{"id":"b3","t":"call"}],"jurus":[{"id":"b4","t":"act","a":"pukul"},
{"id":"b5","t":"act","a":"tendang"},
{"id":"b6","t":"act","a":"lompat"}]},"target":["pukul","tendang","lompat","tangkis","pukul","tendang","lompat"]},
{"id":"j34","world":3,"palette":["pukul","tendang","tangkis","lompat","putar","jurus"],"best":6,"limit":7,"hint":"Gerakan baru: putar! Lima gerakan ninja lengkap.","solution":{"main":[{"id":"b1","t":"call"},
{"id":"b2","t":"call"}],"jurus":[{"id":"b3","t":"act","a":"pukul"},
{"id":"b4","t":"act","a":"lompat"},
{"id":"b5","t":"act","a":"tangkis"},
{"id":"b6","t":"act","a":"tendang"}]},"target":["pukul","lompat","tangkis","tendang","pukul","lompat","tangkis","tendang"]},
{"id":"j35","world":3,"palette":["pukul","tendang","tangkis","lompat","putar","jurus"],"best":6,"limit":7,"hint":"Gerakan baru: putar! Lima gerakan ninja lengkap.","solution":{"main":[{"id":"b1","t":"call"},
{"id":"b2","t":"call"}],"jurus":[{"id":"b3","t":"act","a":"putar"},
{"id":"b4","t":"act","a":"tangkis"},
{"id":"b5","t":"act","a":"lompat"},
{"id":"b6","t":"act","a":"pukul"}]},"target":["putar","tangkis","lompat","pukul","putar","tangkis","lompat","pukul"]},
{"id":"j36","world":3,"palette":["pukul","tendang","tangkis","lompat","putar","jurus"],"best":7,"limit":8,"hint":"Gerakan baru: putar! Lima gerakan ninja lengkap.","solution":{"main":[{"id":"b1","t":"call"},
{"id":"b2","t":"act","a":"tendang"},
{"id":"b3","t":"call"}],"jurus":[{"id":"b4","t":"act","a":"tangkis"},
{"id":"b5","t":"act","a":"putar"},
{"id":"b6","t":"act","a":"pukul"},
{"id":"b7","t":"act","a":"tendang"}]},"target":["tangkis","putar","pukul","tendang","tendang","tangkis","putar","pukul","tendang"]},
{"id":"j37","world":3,"palette":["pukul","tendang","tangkis","lompat","putar","jurus"],"best":6,"limit":7,"hint":"Gerakan baru: putar! Lima gerakan ninja lengkap.","solution":{"main":[{"id":"b1","t":"call"},
{"id":"b2","t":"call"}],"jurus":[{"id":"b3","t":"act","a":"pukul"},
{"id":"b4","t":"act","a":"lompat"},
{"id":"b5","t":"act","a":"lompat"},
{"id":"b6","t":"act","a":"putar"}]},"target":["pukul","lompat","lompat","putar","pukul","lompat","lompat","putar"]},
{"id":"j38","world":3,"palette":["pukul","tendang","tangkis","lompat","putar","jurus"],"best":7,"limit":8,"hint":"Gerakan baru: putar! Lima gerakan ninja lengkap.","solution":{"main":[{"id":"b1","t":"call"},
{"id":"b2","t":"call"}],"jurus":[{"id":"b3","t":"act","a":"pukul"},
{"id":"b4","t":"act","a":"putar"},
{"id":"b5","t":"act","a":"lompat"},
{"id":"b6","t":"act","a":"tangkis"},
{"id":"b7","t":"act","a":"tendang"}]},"target":["pukul","putar","lompat","tangkis","tendang","pukul","putar","lompat","tangkis","tendang"]},
{"id":"j39","world":3,"palette":["pukul","tendang","tangkis","lompat","putar","jurus"],"best":8,"limit":9,"hint":"Gerakan baru: putar! Lima gerakan ninja lengkap.","solution":{"main":[{"id":"b1","t":"call"},
{"id":"b2","t":"act","a":"tangkis"},
{"id":"b3","t":"call"},
{"id":"b4","t":"act","a":"pukul"}],"jurus":[{"id":"b5","t":"act","a":"tendang"},
{"id":"b6","t":"act","a":"putar"},
{"id":"b7","t":"act","a":"lompat"},
{"id":"b8","t":"act","a":"pukul"}]},"target":["tendang","putar","lompat","pukul","tangkis","tendang","putar","lompat","pukul","pukul"]},
{"id":"j40","world":3,"palette":["pukul","tendang","tangkis","lompat","putar","jurus"],"best":8,"limit":9,"hint":"Gerakan baru: putar! Lima gerakan ninja lengkap.","solution":{"main":[{"id":"b1","t":"call"},
{"id":"b2","t":"act","a":"lompat"},
{"id":"b3","t":"call"}],"jurus":[{"id":"b4","t":"act","a":"lompat"},
{"id":"b5","t":"act","a":"pukul"},
{"id":"b6","t":"act","a":"tangkis"},
{"id":"b7","t":"act","a":"putar"},
{"id":"b8","t":"act","a":"tendang"}]},"target":["lompat","pukul","tangkis","putar","tendang","lompat","lompat","pukul","tangkis","putar","tendang"]},
{"id":"j41","world":4,"palette":["pukul","tendang","tangkis","lompat","putar","jurus"],"best":7,"limit":8,"hint":"Jurusnya makin panjang. Susun sekali, pakai berkali-kali!","solution":{"main":[{"id":"b1","t":"call"},
{"id":"b2","t":"call"}],"jurus":[{"id":"b3","t":"act","a":"tangkis"},
{"id":"b4","t":"act","a":"pukul"},
{"id":"b5","t":"act","a":"tendang"},
{"id":"b6","t":"act","a":"putar"},
{"id":"b7","t":"act","a":"lompat"}]},"target":["tangkis","pukul","tendang","putar","lompat","tangkis","pukul","tendang","putar","lompat"]},
{"id":"j42","world":4,"palette":["pukul","tendang","tangkis","lompat","putar","jurus"],"best":7,"limit":8,"hint":"Jurusnya makin panjang. Susun sekali, pakai berkali-kali!","solution":{"main":[{"id":"b1","t":"call"},
{"id":"b2","t":"call"}],"jurus":[{"id":"b3","t":"act","a":"lompat"},
{"id":"b4","t":"act","a":"pukul"},
{"id":"b5","t":"act","a":"tendang"},
{"id":"b6","t":"act","a":"putar"},
{"id":"b7","t":"act","a":"tangkis"}]},"target":["lompat","pukul","tendang","putar","tangkis","lompat","pukul","tendang","putar","tangkis"]},
{"id":"j43","world":4,"palette":["pukul","tendang","tangkis","lompat","putar","jurus"],"best":7,"limit":8,"hint":"Jurusnya makin panjang. Susun sekali, pakai berkali-kali!","solution":{"main":[{"id":"b1","t":"call"},
{"id":"b2","t":"call"}],"jurus":[{"id":"b3","t":"act","a":"lompat"},
{"id":"b4","t":"act","a":"lompat"},
{"id":"b5","t":"act","a":"putar"},
{"id":"b6","t":"act","a":"putar"},
{"id":"b7","t":"act","a":"tangkis"}]},"target":["lompat","lompat","putar","putar","tangkis","lompat","lompat","putar","putar","tangkis"]},
{"id":"j44","world":4,"palette":["pukul","tendang","tangkis","lompat","putar","jurus"],"best":7,"limit":8,"hint":"Jurusnya makin panjang. Susun sekali, pakai berkali-kali!","solution":{"main":[{"id":"b1","t":"call"},
{"id":"b2","t":"call"}],"jurus":[{"id":"b3","t":"act","a":"putar"},
{"id":"b4","t":"act","a":"pukul"},
{"id":"b5","t":"act","a":"tangkis"},
{"id":"b6","t":"act","a":"putar"},
{"id":"b7","t":"act","a":"pukul"}]},"target":["putar","pukul","tangkis","putar","pukul","putar","pukul","tangkis","putar","pukul"]},
{"id":"j45","world":4,"palette":["pukul","tendang","tangkis","lompat","putar","jurus"],"best":8,"limit":9,"hint":"Jurusnya makin panjang. Susun sekali, pakai berkali-kali!","solution":{"main":[{"id":"b1","t":"call"},
{"id":"b2","t":"call"},
{"id":"b3","t":"call"}],"jurus":[{"id":"b4","t":"act","a":"tendang"},
{"id":"b5","t":"act","a":"pukul"},
{"id":"b6","t":"act","a":"lompat"},
{"id":"b7","t":"act","a":"putar"},
{"id":"b8","t":"act","a":"tangkis"}]},"target":["tendang","pukul","lompat","putar","tangkis","tendang","pukul","lompat","putar","tangkis","tendang","pukul","lompat","putar","tangkis"]},
{"id":"j46","world":4,"palette":["pukul","tendang","tangkis","lompat","putar","jurus"],"best":8,"limit":9,"hint":"Jurusnya makin panjang. Susun sekali, pakai berkali-kali!","solution":{"main":[{"id":"b1","t":"call"},
{"id":"b2","t":"act","a":"putar"},
{"id":"b3","t":"call"}],"jurus":[{"id":"b4","t":"act","a":"putar"},
{"id":"b5","t":"act","a":"pukul"},
{"id":"b6","t":"act","a":"lompat"},
{"id":"b7","t":"act","a":"tangkis"},
{"id":"b8","t":"act","a":"tendang"}]},"target":["putar","pukul","lompat","tangkis","tendang","putar","putar","pukul","lompat","tangkis","tendang"]},
{"id":"j47","world":4,"palette":["pukul","tendang","tangkis","lompat","putar","jurus"],"best":8,"limit":9,"hint":"Jurusnya makin panjang. Susun sekali, pakai berkali-kali!","solution":{"main":[{"id":"b1","t":"call"},
{"id":"b2","t":"act","a":"tangkis"},
{"id":"b3","t":"call"}],"jurus":[{"id":"b4","t":"act","a":"tendang"},
{"id":"b5","t":"act","a":"lompat"},
{"id":"b6","t":"act","a":"pukul"},
{"id":"b7","t":"act","a":"putar"},
{"id":"b8","t":"act","a":"tangkis"}]},"target":["tendang","lompat","pukul","putar","tangkis","tangkis","tendang","lompat","pukul","putar","tangkis"]},
{"id":"j48","world":4,"palette":["pukul","tendang","tangkis","lompat","putar","jurus"],"best":8,"limit":9,"hint":"Jurusnya makin panjang. Susun sekali, pakai berkali-kali!","solution":{"main":[{"id":"b1","t":"call"},
{"id":"b2","t":"call"},
{"id":"b3","t":"act","a":"lompat"}],"jurus":[{"id":"b4","t":"act","a":"putar"},
{"id":"b5","t":"act","a":"pukul"},
{"id":"b6","t":"act","a":"lompat"},
{"id":"b7","t":"act","a":"tangkis"},
{"id":"b8","t":"act","a":"tendang"}]},"target":["putar","pukul","lompat","tangkis","tendang","putar","pukul","lompat","tangkis","tendang","lompat"]},
{"id":"j49","world":4,"palette":["pukul","tendang","tangkis","lompat","putar","jurus"],"best":8,"limit":9,"hint":"Jurusnya makin panjang. Susun sekali, pakai berkali-kali!","solution":{"main":[{"id":"b1","t":"call"},
{"id":"b2","t":"call"},
{"id":"b3","t":"call"}],"jurus":[{"id":"b4","t":"act","a":"tangkis"},
{"id":"b5","t":"act","a":"lompat"},
{"id":"b6","t":"act","a":"tangkis"},
{"id":"b7","t":"act","a":"pukul"},
{"id":"b8","t":"act","a":"tendang"}]},"target":["tangkis","lompat","tangkis","pukul","tendang","tangkis","lompat","tangkis","pukul","tendang","tangkis","lompat","tangkis","pukul","tendang"]},
{"id":"j50","world":4,"palette":["pukul","tendang","tangkis","lompat","putar","jurus"],"best":9,"limit":10,"hint":"Jurusnya makin panjang. Susun sekali, pakai berkali-kali!","solution":{"main":[{"id":"b1","t":"call"},
{"id":"b2","t":"act","a":"putar"},
{"id":"b3","t":"call"},
{"id":"b4","t":"act","a":"tendang"}],"jurus":[{"id":"b5","t":"act","a":"tangkis"},
{"id":"b6","t":"act","a":"lompat"},
{"id":"b7","t":"act","a":"pukul"},
{"id":"b8","t":"act","a":"putar"},
{"id":"b9","t":"act","a":"tendang"}]},"target":["tangkis","lompat","pukul","putar","tendang","putar","tangkis","lompat","pukul","putar","tendang","tendang"]},
{"id":"j51","world":5,"palette":["pukul","tendang","tangkis","lompat","putar","ulangi","jurus"],"best":5,"limit":6,"hint":"Blok ulangi kembali! Ulangi bisa dipakai di dalam jurus.","solution":{"main":[{"id":"b1","t":"call"},
{"id":"b2","t":"call"}],"jurus":[{"id":"b3","t":"loop","n":3,"body":[{"id":"b4","t":"act","a":"tangkis"}]},
{"id":"b5","t":"act","a":"putar"}]},"target":["tangkis","tangkis","tangkis","putar","tangkis","tangkis","tangkis","putar"]},
{"id":"j52","world":5,"palette":["pukul","tendang","tangkis","lompat","putar","ulangi","jurus"],"best":6,"limit":7,"hint":"Blok ulangi kembali! Ulangi bisa dipakai di dalam jurus.","solution":{"main":[{"id":"b1","t":"call"},
{"id":"b2","t":"call"}],"jurus":[{"id":"b3","t":"loop","n":3,"body":[{"id":"b4","t":"act","a":"putar"}]},
{"id":"b5","t":"act","a":"tendang"},
{"id":"b6","t":"act","a":"tangkis"}]},"target":["putar","putar","putar","tendang","tangkis","putar","putar","putar","tendang","tangkis"]},
{"id":"j53","world":5,"palette":["pukul","tendang","tangkis","lompat","putar","ulangi","jurus"],"best":5,"limit":6,"hint":"Blok ulangi kembali! Ulangi bisa dipakai di dalam jurus.","solution":{"main":[{"id":"b1","t":"call"},
{"id":"b2","t":"call"}],"jurus":[{"id":"b3","t":"act","a":"putar"},
{"id":"b4","t":"loop","n":3,"body":[{"id":"b5","t":"act","a":"pukul"}]}]},"target":["putar","pukul","pukul","pukul","putar","pukul","pukul","pukul"]},
{"id":"j54","world":5,"palette":["pukul","tendang","tangkis","lompat","putar","ulangi","jurus"],"best":6,"limit":7,"hint":"Blok ulangi kembali! Ulangi bisa dipakai di dalam jurus.","solution":{"main":[{"id":"b1","t":"call"},
{"id":"b2","t":"call"}],"jurus":[{"id":"b3","t":"loop","n":2,"body":[{"id":"b4","t":"act","a":"tendang"},
{"id":"b5","t":"act","a":"putar"}]},
{"id":"b6","t":"act","a":"lompat"}]},"target":["tendang","putar","tendang","putar","lompat","tendang","putar","tendang","putar","lompat"]},
{"id":"j55","world":5,"palette":["pukul","tendang","tangkis","lompat","putar","ulangi","jurus"],"best":5,"limit":6,"hint":"Blok ulangi kembali! Ulangi bisa dipakai di dalam jurus.","solution":{"main":[{"id":"b1","t":"call"},
{"id":"b2","t":"call"}],"jurus":[{"id":"b3","t":"loop","n":4,"body":[{"id":"b4","t":"act","a":"putar"}]},
{"id":"b5","t":"act","a":"lompat"}]},"target":["putar","putar","putar","putar","lompat","putar","putar","putar","putar","lompat"]},
{"id":"j56","world":5,"palette":["pukul","tendang","tangkis","lompat","putar","ulangi","jurus"],"best":7,"limit":8,"hint":"Blok ulangi kembali! Ulangi bisa dipakai di dalam jurus.","solution":{"main":[{"id":"b1","t":"call"},
{"id":"b2","t":"act","a":"pukul"},
{"id":"b3","t":"call"}],"jurus":[{"id":"b4","t":"loop","n":3,"body":[{"id":"b5","t":"act","a":"lompat"}]},
{"id":"b6","t":"act","a":"tendang"},
{"id":"b7","t":"act","a":"tangkis"}]},"target":["lompat","lompat","lompat","tendang","tangkis","pukul","lompat","lompat","lompat","tendang","tangkis"]},
{"id":"j57","world":5,"palette":["pukul","tendang","tangkis","lompat","putar","ulangi","jurus"],"best":6,"limit":7,"hint":"Blok ulangi kembali! Ulangi bisa dipakai di dalam jurus.","solution":{"main":[{"id":"b1","t":"call"},
{"id":"b2","t":"call"}],"jurus":[{"id":"b3","t":"act","a":"tangkis"},
{"id":"b4","t":"loop","n":3,"body":[{"id":"b5","t":"act","a":"tendang"}]},
{"id":"b6","t":"act","a":"pukul"}]},"target":["tangkis","tendang","tendang","tendang","pukul","tangkis","tendang","tendang","tendang","pukul"]},
{"id":"j58","world":5,"palette":["pukul","tendang","tangkis","lompat","putar","ulangi","jurus"],"best":7,"limit":8,"hint":"Blok ulangi kembali! Ulangi bisa dipakai di dalam jurus.","solution":{"main":[{"id":"b1","t":"call"},
{"id":"b2","t":"call"}],"jurus":[{"id":"b3","t":"loop","n":2,"body":[{"id":"b4","t":"act","a":"pukul"},
{"id":"b5","t":"act","a":"lompat"}]},
{"id":"b6","t":"act","a":"tangkis"},
{"id":"b7","t":"act","a":"putar"}]},"target":["pukul","lompat","pukul","lompat","tangkis","putar","pukul","lompat","pukul","lompat","tangkis","putar"]},
{"id":"j59","world":5,"palette":["pukul","tendang","tangkis","lompat","putar","ulangi","jurus"],"best":6,"limit":7,"hint":"Blok ulangi kembali! Ulangi bisa dipakai di dalam jurus.","solution":{"main":[{"id":"b1","t":"call"},
{"id":"b2","t":"call"}],"jurus":[{"id":"b3","t":"loop","n":4,"body":[{"id":"b4","t":"act","a":"putar"}]},
{"id":"b5","t":"act","a":"tangkis"},
{"id":"b6","t":"act","a":"pukul"}]},"target":["putar","putar","putar","putar","tangkis","pukul","putar","putar","putar","putar","tangkis","pukul"]},
{"id":"j60","world":5,"palette":["pukul","tendang","tangkis","lompat","putar","ulangi","jurus"],"best":6,"limit":7,"hint":"Blok ulangi kembali! Ulangi bisa dipakai di dalam jurus.","solution":{"main":[{"id":"b1","t":"call"},
{"id":"b2","t":"call"}],"jurus":[{"id":"b3","t":"loop","n":3,"body":[{"id":"b4","t":"act","a":"lompat"},
{"id":"b5","t":"act","a":"tendang"}]},
{"id":"b6","t":"act","a":"putar"}]},"target":["lompat","tendang","lompat","tendang","lompat","tendang","putar","lompat","tendang","lompat","tendang","lompat","tendang","putar"]},
{"id":"j61","world":6,"palette":["pukul","tendang","tangkis","lompat","putar","ulangi","jurus"],"best":5,"limit":6,"hint":"Jurus juga bisa dipanggil di dalam ulangi!","solution":{"main":[{"id":"b1","t":"loop","n":3,"body":[{"id":"b2","t":"call"}]}],"jurus":[{"id":"b3","t":"act","a":"pukul"},
{"id":"b4","t":"act","a":"tangkis"},
{"id":"b5","t":"act","a":"putar"}]},"target":["pukul","tangkis","putar","pukul","tangkis","putar","pukul","tangkis","putar"]},
{"id":"j62","world":6,"palette":["pukul","tendang","tangkis","lompat","putar","ulangi","jurus"],"best":5,"limit":6,"hint":"Jurus juga bisa dipanggil di dalam ulangi!","solution":{"main":[{"id":"b1","t":"loop","n":3,"body":[{"id":"b2","t":"call"}]}],"jurus":[{"id":"b3","t":"act","a":"tangkis"},
{"id":"b4","t":"act","a":"putar"},
{"id":"b5","t":"act","a":"putar"}]},"target":["tangkis","putar","putar","tangkis","putar","putar","tangkis","putar","putar"]},
{"id":"j63","world":6,"palette":["pukul","tendang","tangkis","lompat","putar","ulangi","jurus"],"best":5,"limit":6,"hint":"Jurus juga bisa dipanggil di dalam ulangi!","solution":{"main":[{"id":"b1","t":"loop","n":4,"body":[{"id":"b2","t":"call"}]}],"jurus":[{"id":"b3","t":"act","a":"pukul"},
{"id":"b4","t":"act","a":"pukul"},
{"id":"b5","t":"act","a":"tendang"}]},"target":["pukul","pukul","tendang","pukul","pukul","tendang","pukul","pukul","tendang","pukul","pukul","tendang"]},
{"id":"j64","world":6,"palette":["pukul","tendang","tangkis","lompat","putar","ulangi","jurus"],"best":6,"limit":7,"hint":"Jurus juga bisa dipanggil di dalam ulangi!","solution":{"main":[{"id":"b1","t":"loop","n":3,"body":[{"id":"b2","t":"call"}]}],"jurus":[{"id":"b3","t":"act","a":"putar"},
{"id":"b4","t":"act","a":"tendang"},
{"id":"b5","t":"act","a":"lompat"},
{"id":"b6","t":"act","a":"pukul"}]},"target":["putar","tendang","lompat","pukul","putar","tendang","lompat","pukul","putar","tendang","lompat","pukul"]},
{"id":"j65","world":6,"palette":["pukul","tendang","tangkis","lompat","putar","ulangi","jurus"],"best":6,"limit":7,"hint":"Jurus juga bisa dipanggil di dalam ulangi!","solution":{"main":[{"id":"b1","t":"loop","n":3,"body":[{"id":"b2","t":"call"}]},
{"id":"b3","t":"act","a":"tangkis"}],"jurus":[{"id":"b4","t":"act","a":"lompat"},
{"id":"b5","t":"act","a":"putar"},
{"id":"b6","t":"act","a":"tendang"}]},"target":["lompat","putar","tendang","lompat","putar","tendang","lompat","putar","tendang","tangkis"]},
{"id":"j66","world":6,"palette":["pukul","tendang","tangkis","lompat","putar","ulangi","jurus"],"best":6,"limit":7,"hint":"Jurus juga bisa dipanggil di dalam ulangi!","solution":{"main":[{"id":"b1","t":"act","a":"putar"},
{"id":"b2","t":"loop","n":3,"body":[{"id":"b3","t":"call"}]}],"jurus":[{"id":"b4","t":"act","a":"pukul"},
{"id":"b5","t":"act","a":"tendang"},
{"id":"b6","t":"act","a":"tangkis"}]},"target":["putar","pukul","tendang","tangkis","pukul","tendang","tangkis","pukul","tendang","tangkis"]},
{"id":"j67","world":6,"palette":["pukul","tendang","tangkis","lompat","putar","ulangi","jurus"],"best":6,"limit":7,"hint":"Jurus juga bisa dipanggil di dalam ulangi!","solution":{"main":[{"id":"b1","t":"loop","n":3,"body":[{"id":"b2","t":"call"}]}],"jurus":[{"id":"b3","t":"act","a":"putar"},
{"id":"b4","t":"act","a":"tangkis"},
{"id":"b5","t":"act","a":"lompat"},
{"id":"b6","t":"act","a":"putar"}]},"target":["putar","tangkis","lompat","putar","putar","tangkis","lompat","putar","putar","tangkis","lompat","putar"]},
{"id":"j68","world":6,"palette":["pukul","tendang","tangkis","lompat","putar","ulangi","jurus"],"best":6,"limit":7,"hint":"Jurus juga bisa dipanggil di dalam ulangi!","solution":{"main":[{"id":"b1","t":"loop","n":4,"body":[{"id":"b2","t":"call"}]}],"jurus":[{"id":"b3","t":"act","a":"pukul"},
{"id":"b4","t":"act","a":"putar"},
{"id":"b5","t":"act","a":"tangkis"},
{"id":"b6","t":"act","a":"tendang"}]},"target":["pukul","putar","tangkis","tendang","pukul","putar","tangkis","tendang","pukul","putar","tangkis","tendang","pukul","putar","tangkis","tendang"]},
{"id":"j69","world":6,"palette":["pukul","tendang","tangkis","lompat","putar","ulangi","jurus"],"best":7,"limit":8,"hint":"Jurus juga bisa dipanggil di dalam ulangi!","solution":{"main":[{"id":"b1","t":"loop","n":3,"body":[{"id":"b2","t":"call"}]},
{"id":"b3","t":"act","a":"tendang"},
{"id":"b4","t":"act","a":"tendang"}],"jurus":[{"id":"b5","t":"act","a":"pukul"},
{"id":"b6","t":"act","a":"tangkis"},
{"id":"b7","t":"act","a":"lompat"}]},"target":["pukul","tangkis","lompat","pukul","tangkis","lompat","pukul","tangkis","lompat","tendang","tendang"]},
{"id":"j70","world":6,"palette":["pukul","tendang","tangkis","lompat","putar","ulangi","jurus"],"best":7,"limit":8,"hint":"Jurus juga bisa dipanggil di dalam ulangi!","solution":{"main":[{"id":"b1","t":"loop","n":3,"body":[{"id":"b2","t":"call"}]}],"jurus":[{"id":"b3","t":"act","a":"putar"},
{"id":"b4","t":"act","a":"lompat"},
{"id":"b5","t":"act","a":"tendang"},
{"id":"b6","t":"act","a":"pukul"},
{"id":"b7","t":"act","a":"tangkis"}]},"target":["putar","lompat","tendang","pukul","tangkis","putar","lompat","tendang","pukul","tangkis","putar","lompat","tendang","pukul","tangkis"]},
{"id":"j71","world":7,"palette":["pukul","tendang","tangkis","lompat","putar","ulangi","jurus"],"best":5,"limit":6,"hint":"Gabungkan ulangi di luar dan di dalam jurus.","solution":{"main":[{"id":"b1","t":"loop","n":2,"body":[{"id":"b2","t":"call"}]}],"jurus":[{"id":"b3","t":"loop","n":3,"body":[{"id":"b4","t":"act","a":"tendang"}]},
{"id":"b5","t":"act","a":"putar"}]},"target":["tendang","tendang","tendang","putar","tendang","tendang","tendang","putar"]},
{"id":"j72","world":7,"palette":["pukul","tendang","tangkis","lompat","putar","ulangi","jurus"],"best":6,"limit":7,"hint":"Gabungkan ulangi di luar dan di dalam jurus.","solution":{"main":[{"id":"b1","t":"loop","n":3,"body":[{"id":"b2","t":"call"}]}],"jurus":[{"id":"b3","t":"loop","n":2,"body":[{"id":"b4","t":"act","a":"putar"},
{"id":"b5","t":"act","a":"lompat"}]},
{"id":"b6","t":"act","a":"tangkis"}]},"target":["putar","lompat","putar","lompat","tangkis","putar","lompat","putar","lompat","tangkis","putar","lompat","putar","lompat","tangkis"]},
{"id":"j73","world":7,"palette":["pukul","tendang","tangkis","lompat","putar","ulangi","jurus"],"best":5,"limit":6,"hint":"Gabungkan ulangi di luar dan di dalam jurus.","solution":{"main":[{"id":"b1","t":"loop","n":3,"body":[{"id":"b2","t":"call"}]}],"jurus":[{"id":"b3","t":"act","a":"tangkis"},
{"id":"b4","t":"loop","n":3,"body":[{"id":"b5","t":"act","a":"pukul"}]}]},"target":["tangkis","pukul","pukul","pukul","tangkis","pukul","pukul","pukul","tangkis","pukul","pukul","pukul"]},
{"id":"j74","world":7,"palette":["pukul","tendang","tangkis","lompat","putar","ulangi","jurus"],"best":6,"limit":7,"hint":"Gabungkan ulangi di luar dan di dalam jurus.","solution":{"main":[{"id":"b1","t":"loop","n":3,"body":[{"id":"b2","t":"call"}]}],"jurus":[{"id":"b3","t":"loop","n":3,"body":[{"id":"b4","t":"act","a":"pukul"}]},
{"id":"b5","t":"act","a":"lompat"},
{"id":"b6","t":"act","a":"tendang"}]},"target":["pukul","pukul","pukul","lompat","tendang","pukul","pukul","pukul","lompat","tendang","pukul","pukul","pukul","lompat","tendang"]},
{"id":"j75","world":7,"palette":["pukul","tendang","tangkis","lompat","putar","ulangi","jurus"],"best":8,"limit":9,"hint":"Gabungkan ulangi di luar dan di dalam jurus.","solution":{"main":[{"id":"b1","t":"loop","n":2,"body":[{"id":"b2","t":"call"}]},
{"id":"b3","t":"act","a":"tendang"}],"jurus":[{"id":"b4","t":"loop","n":2,"body":[{"id":"b5","t":"act","a":"tangkis"},
{"id":"b6","t":"act","a":"lompat"}]},
{"id":"b7","t":"act","a":"putar"},
{"id":"b8","t":"act","a":"pukul"}]},"target":["tangkis","lompat","tangkis","lompat","putar","pukul","tangkis","lompat","tangkis","lompat","putar","pukul","tendang"]},
{"id":"j76","world":7,"palette":["pukul","tendang","tangkis","lompat","putar","ulangi","jurus"],"best":6,"limit":7,"hint":"Gabungkan ulangi di luar dan di dalam jurus.","solution":{"main":[{"id":"b1","t":"loop","n":2,"body":[{"id":"b2","t":"call"}]},
{"id":"b3","t":"act","a":"tangkis"}],"jurus":[{"id":"b4","t":"act","a":"tendang"},
{"id":"b5","t":"loop","n":4,"body":[{"id":"b6","t":"act","a":"lompat"}]}]},"target":["tendang","lompat","lompat","lompat","lompat","tendang","lompat","lompat","lompat","lompat","tangkis"]},
{"id":"j77","world":7,"palette":["pukul","tendang","tangkis","lompat","putar","ulangi","jurus"],"best":6,"limit":7,"hint":"Gabungkan ulangi di luar dan di dalam jurus.","solution":{"main":[{"id":"b1","t":"loop","n":3,"body":[{"id":"b2","t":"call"}]},
{"id":"b3","t":"act","a":"lompat"}],"jurus":[{"id":"b4","t":"loop","n":3,"body":[{"id":"b5","t":"act","a":"tendang"}]},
{"id":"b6","t":"act","a":"tangkis"}]},"target":["tendang","tendang","tendang","tangkis","tendang","tendang","tendang","tangkis","tendang","tendang","tendang","tangkis","lompat"]},
{"id":"j78","world":7,"palette":["pukul","tendang","tangkis","lompat","putar","ulangi","jurus"],"best":7,"limit":8,"hint":"Gabungkan ulangi di luar dan di dalam jurus.","solution":{"main":[{"id":"b1","t":"loop","n":3,"body":[{"id":"b2","t":"call"}]},
{"id":"b3","t":"act","a":"tangkis"}],"jurus":[{"id":"b4","t":"loop","n":2,"body":[{"id":"b5","t":"act","a":"tendang"},
{"id":"b6","t":"act","a":"pukul"}]},
{"id":"b7","t":"act","a":"lompat"}]},"target":["tendang","pukul","tendang","pukul","lompat","tendang","pukul","tendang","pukul","lompat","tendang","pukul","tendang","pukul","lompat","tangkis"]},
{"id":"j79","world":7,"palette":["pukul","tendang","tangkis","lompat","putar","ulangi","jurus"],"best":6,"limit":7,"hint":"Gabungkan ulangi di luar dan di dalam jurus.","solution":{"main":[{"id":"b1","t":"loop","n":3,"body":[{"id":"b2","t":"call"}]}],"jurus":[{"id":"b3","t":"act","a":"tangkis"},
{"id":"b4","t":"loop","n":3,"body":[{"id":"b5","t":"act","a":"tendang"}]},
{"id":"b6","t":"act","a":"pukul"}]},"target":["tangkis","tendang","tendang","tendang","pukul","tangkis","tendang","tendang","tendang","pukul","tangkis","tendang","tendang","tendang","pukul"]},
{"id":"j80","world":7,"palette":["pukul","tendang","tangkis","lompat","putar","ulangi","jurus"],"best":7,"limit":8,"hint":"Gabungkan ulangi di luar dan di dalam jurus.","solution":{"main":[{"id":"b1","t":"loop","n":3,"body":[{"id":"b2","t":"call"}]},
{"id":"b3","t":"act","a":"tendang"}],"jurus":[{"id":"b4","t":"loop","n":3,"body":[{"id":"b5","t":"act","a":"tangkis"}]},
{"id":"b6","t":"act","a":"lompat"},
{"id":"b7","t":"act","a":"pukul"}]},"target":["tangkis","tangkis","tangkis","lompat","pukul","tangkis","tangkis","tangkis","lompat","pukul","tangkis","tangkis","tangkis","lompat","pukul","tendang"]},
{"id":"j81","world":8,"palette":["pukul","tendang","tangkis","lompat","putar","ulangi","jurus"],"best":7,"limit":8,"hint":"Rangkaian Sensei panjang sekali. Cari jurus yang paling hemat!","solution":{"main":[{"id":"b1","t":"loop","n":3,"body":[{"id":"b2","t":"call"}]}],"jurus":[{"id":"b3","t":"act","a":"putar"},
{"id":"b4","t":"act","a":"tendang"},
{"id":"b5","t":"act","a":"lompat"},
{"id":"b6","t":"act","a":"pukul"},
{"id":"b7","t":"act","a":"tangkis"}]},"target":["putar","tendang","lompat","pukul","tangkis","putar","tendang","lompat","pukul","tangkis","putar","tendang","lompat","pukul","tangkis"]},
{"id":"j82","world":8,"palette":["pukul","tendang","tangkis","lompat","putar","ulangi","jurus"],"best":7,"limit":8,"hint":"Rangkaian Sensei panjang sekali. Cari jurus yang paling hemat!","solution":{"main":[{"id":"b1","t":"loop","n":3,"body":[{"id":"b2","t":"call"}]}],"jurus":[{"id":"b3","t":"act","a":"lompat"},
{"id":"b4","t":"act","a":"tendang"},
{"id":"b5","t":"loop","n":2,"body":[{"id":"b6","t":"act","a":"putar"}]},
{"id":"b7","t":"act","a":"tangkis"}]},"target":["lompat","tendang","putar","putar","tangkis","lompat","tendang","putar","putar","tangkis","lompat","tendang","putar","putar","tangkis"]},
{"id":"j83","world":8,"palette":["pukul","tendang","tangkis","lompat","putar","ulangi","jurus"],"best":8,"limit":9,"hint":"Rangkaian Sensei panjang sekali. Cari jurus yang paling hemat!","solution":{"main":[{"id":"b1","t":"loop","n":2,"body":[{"id":"b2","t":"call"}]}],"jurus":[{"id":"b3","t":"loop","n":2,"body":[{"id":"b4","t":"act","a":"lompat"},
{"id":"b5","t":"act","a":"tangkis"}]},
{"id":"b6","t":"act","a":"tendang"},
{"id":"b7","t":"act","a":"pukul"},
{"id":"b8","t":"act","a":"putar"}]},"target":["lompat","tangkis","lompat","tangkis","tendang","pukul","putar","lompat","tangkis","lompat","tangkis","tendang","pukul","putar"]},
{"id":"j84","world":8,"palette":["pukul","tendang","tangkis","lompat","putar","ulangi","jurus"],"best":9,"limit":10,"hint":"Rangkaian Sensei panjang sekali. Cari jurus yang paling hemat!","solution":{"main":[{"id":"b1","t":"call"},
{"id":"b2","t":"loop","n":2,"body":[{"id":"b3","t":"act","a":"tendang"}]},
{"id":"b4","t":"call"}],"jurus":[{"id":"b5","t":"act","a":"tendang"},
{"id":"b6","t":"act","a":"lompat"},
{"id":"b7","t":"act","a":"pukul"},
{"id":"b8","t":"act","a":"putar"},
{"id":"b9","t":"act","a":"tangkis"}]},"target":["tendang","lompat","pukul","putar","tangkis","tendang","tendang","tendang","lompat","pukul","putar","tangkis"]},
{"id":"j85","world":8,"palette":["pukul","tendang","tangkis","lompat","putar","ulangi","jurus"],"best":7,"limit":8,"hint":"Rangkaian Sensei panjang sekali. Cari jurus yang paling hemat!","solution":{"main":[{"id":"b1","t":"loop","n":3,"body":[{"id":"b2","t":"call"}]}],"jurus":[{"id":"b3","t":"act","a":"putar"},
{"id":"b4","t":"loop","n":3,"body":[{"id":"b5","t":"act","a":"tangkis"}]},
{"id":"b6","t":"act","a":"tendang"},
{"id":"b7","t":"act","a":"lompat"}]},"target":["putar","tangkis","tangkis","tangkis","tendang","lompat","putar","tangkis","tangkis","tangkis","tendang","lompat","putar","tangkis","tangkis","tangkis","tendang","lompat"]},
{"id":"j86","world":8,"palette":["pukul","tendang","tangkis","lompat","putar","ulangi","jurus"],"best":9,"limit":10,"hint":"Rangkaian Sensei panjang sekali. Cari jurus yang paling hemat!","solution":{"main":[{"id":"b1","t":"loop","n":2,"body":[{"id":"b2","t":"call"}]},
{"id":"b3","t":"act","a":"putar"},
{"id":"b4","t":"call"}],"jurus":[{"id":"b5","t":"act","a":"pukul"},
{"id":"b6","t":"act","a":"lompat"},
{"id":"b7","t":"act","a":"putar"},
{"id":"b8","t":"act","a":"tangkis"},
{"id":"b9","t":"act","a":"tendang"}]},"target":["pukul","lompat","putar","tangkis","tendang","pukul","lompat","putar","tangkis","tendang","putar","pukul","lompat","putar","tangkis","tendang"]},
{"id":"j87","world":8,"palette":["pukul","tendang","tangkis","lompat","putar","ulangi","jurus"],"best":7,"limit":8,"hint":"Rangkaian Sensei panjang sekali. Cari jurus yang paling hemat!","solution":{"main":[{"id":"b1","t":"loop","n":2,"body":[{"id":"b2","t":"call"}]}],"jurus":[{"id":"b3","t":"loop","n":2,"body":[{"id":"b4","t":"act","a":"tangkis"},
{"id":"b5","t":"act","a":"tendang"},
{"id":"b6","t":"act","a":"pukul"}]},
{"id":"b7","t":"act","a":"lompat"}]},"target":["tangkis","tendang","pukul","tangkis","tendang","pukul","lompat","tangkis","tendang","pukul","tangkis","tendang","pukul","lompat"]},
{"id":"j88","world":8,"palette":["pukul","tendang","tangkis","lompat","putar","ulangi","jurus"],"best":7,"limit":8,"hint":"Rangkaian Sensei panjang sekali. Cari jurus yang paling hemat!","solution":{"main":[{"id":"b1","t":"loop","n":3,"body":[{"id":"b2","t":"call"}]}],"jurus":[{"id":"b3","t":"act","a":"putar"},
{"id":"b4","t":"loop","n":2,"body":[{"id":"b5","t":"act","a":"pukul"},
{"id":"b6","t":"act","a":"tendang"}]},
{"id":"b7","t":"act","a":"tangkis"}]},"target":["putar","pukul","tendang","pukul","tendang","tangkis","putar","pukul","tendang","pukul","tendang","tangkis","putar","pukul","tendang","pukul","tendang","tangkis"]},
{"id":"j89","world":8,"palette":["pukul","tendang","tangkis","lompat","putar","ulangi","jurus"],"best":7,"limit":8,"hint":"Rangkaian Sensei panjang sekali. Cari jurus yang paling hemat!","solution":{"main":[{"id":"b1","t":"loop","n":4,"body":[{"id":"b2","t":"call"}]}],"jurus":[{"id":"b3","t":"act","a":"tangkis"},
{"id":"b4","t":"act","a":"lompat"},
{"id":"b5","t":"act","a":"pukul"},
{"id":"b6","t":"act","a":"putar"},
{"id":"b7","t":"act","a":"tendang"}]},"target":["tangkis","lompat","pukul","putar","tendang","tangkis","lompat","pukul","putar","tendang","tangkis","lompat","pukul","putar","tendang","tangkis","lompat","pukul","putar","tendang"]},
{"id":"j90","world":8,"palette":["pukul","tendang","tangkis","lompat","putar","ulangi","jurus"],"best":8,"limit":9,"hint":"Rangkaian Sensei panjang sekali. Cari jurus yang paling hemat!","solution":{"main":[{"id":"b1","t":"loop","n":2,"body":[{"id":"b2","t":"call"}]},
{"id":"b3","t":"act","a":"tangkis"}],"jurus":[{"id":"b4","t":"loop","n":3,"body":[{"id":"b5","t":"act","a":"lompat"},
{"id":"b6","t":"act","a":"pukul"}]},
{"id":"b7","t":"act","a":"putar"},
{"id":"b8","t":"act","a":"tendang"}]},"target":["lompat","pukul","lompat","pukul","lompat","pukul","putar","tendang","lompat","pukul","lompat","pukul","lompat","pukul","putar","tendang","tangkis"]},
{"id":"j91","world":9,"palette":["pukul","tendang","tangkis","lompat","putar","ulangi","jurus"],"best":8,"limit":9,"hint":"Ujian sabuk hitam! Tunjukkan semua jurusmu.","solution":{"main":[{"id":"b1","t":"loop","n":3,"body":[{"id":"b2","t":"call"}]}],"jurus":[{"id":"b3","t":"loop","n":2,"body":[{"id":"b4","t":"act","a":"tangkis"},
{"id":"b5","t":"act","a":"tendang"},
{"id":"b6","t":"act","a":"pukul"}]},
{"id":"b7","t":"act","a":"putar"},
{"id":"b8","t":"act","a":"lompat"}]},"target":["tangkis","tendang","pukul","tangkis","tendang","pukul","putar","lompat","tangkis","tendang","pukul","tangkis","tendang","pukul","putar","lompat","tangkis","tendang","pukul","tangkis","tendang","pukul","putar","lompat"]},
{"id":"j92","world":9,"palette":["pukul","tendang","tangkis","lompat","putar","ulangi","jurus"],"best":8,"limit":9,"hint":"Ujian sabuk hitam! Tunjukkan semua jurusmu.","solution":{"main":[{"id":"b1","t":"loop","n":3,"body":[{"id":"b2","t":"call"}]}],"jurus":[{"id":"b3","t":"act","a":"putar"},
{"id":"b4","t":"loop","n":3,"body":[{"id":"b5","t":"act","a":"pukul"}]},
{"id":"b6","t":"act","a":"tangkis"},
{"id":"b7","t":"act","a":"tendang"},
{"id":"b8","t":"act","a":"lompat"}]},"target":["putar","pukul","pukul","pukul","tangkis","tendang","lompat","putar","pukul","pukul","pukul","tangkis","tendang","lompat","putar","pukul","pukul","pukul","tangkis","tendang","lompat"]},
{"id":"j93","world":9,"palette":["pukul","tendang","tangkis","lompat","putar","ulangi","jurus"],"best":8,"limit":9,"hint":"Ujian sabuk hitam! Tunjukkan semua jurusmu.","solution":{"main":[{"id":"b1","t":"loop","n":2,"body":[{"id":"b2","t":"call"}]}],"jurus":[{"id":"b3","t":"loop","n":3,"body":[{"id":"b4","t":"act","a":"lompat"},
{"id":"b5","t":"act","a":"putar"}]},
{"id":"b6","t":"act","a":"tangkis"},
{"id":"b7","t":"act","a":"pukul"},
{"id":"b8","t":"act","a":"tendang"}]},"target":["lompat","putar","lompat","putar","lompat","putar","tangkis","pukul","tendang","lompat","putar","lompat","putar","lompat","putar","tangkis","pukul","tendang"]},
{"id":"j94","world":9,"palette":["pukul","tendang","tangkis","lompat","putar","ulangi","jurus"],"best":9,"limit":10,"hint":"Ujian sabuk hitam! Tunjukkan semua jurusmu.","solution":{"main":[{"id":"b1","t":"loop","n":3,"body":[{"id":"b2","t":"call"}]},
{"id":"b3","t":"loop","n":2,"body":[{"id":"b4","t":"act","a":"lompat"}]}],"jurus":[{"id":"b5","t":"act","a":"lompat"},
{"id":"b6","t":"act","a":"pukul"},
{"id":"b7","t":"act","a":"putar"},
{"id":"b8","t":"act","a":"tangkis"},
{"id":"b9","t":"act","a":"tendang"}]},"target":["lompat","pukul","putar","tangkis","tendang","lompat","pukul","putar","tangkis","tendang","lompat","pukul","putar","tangkis","tendang","lompat","lompat"]},
{"id":"j95","world":9,"palette":["pukul","tendang","tangkis","lompat","putar","ulangi","jurus"],"best":9,"limit":10,"hint":"Ujian sabuk hitam! Tunjukkan semua jurusmu.","solution":{"main":[{"id":"b1","t":"loop","n":2,"body":[{"id":"b2","t":"call"}]}],"jurus":[{"id":"b3","t":"loop","n":2,"body":[{"id":"b4","t":"act","a":"pukul"},
{"id":"b5","t":"act","a":"lompat"}]},
{"id":"b6","t":"loop","n":2,"body":[{"id":"b7","t":"act","a":"putar"},
{"id":"b8","t":"act","a":"tendang"}]},
{"id":"b9","t":"act","a":"tangkis"}]},"target":["pukul","lompat","pukul","lompat","putar","tendang","putar","tendang","tangkis","pukul","lompat","pukul","lompat","putar","tendang","putar","tendang","tangkis"]},
{"id":"j96","world":9,"palette":["pukul","tendang","tangkis","lompat","putar","ulangi","jurus"],"best":7,"limit":8,"hint":"Ujian sabuk hitam! Tunjukkan semua jurusmu.","solution":{"main":[{"id":"b1","t":"loop","n":3,"body":[{"id":"b2","t":"call"}]}],"jurus":[{"id":"b3","t":"act","a":"tangkis"},
{"id":"b4","t":"loop","n":4,"body":[{"id":"b5","t":"act","a":"tendang"}]},
{"id":"b6","t":"act","a":"putar"},
{"id":"b7","t":"act","a":"pukul"}]},"target":["tangkis","tendang","tendang","tendang","tendang","putar","pukul","tangkis","tendang","tendang","tendang","tendang","putar","pukul","tangkis","tendang","tendang","tendang","tendang","putar","pukul"]},
{"id":"j97","world":9,"palette":["pukul","tendang","tangkis","lompat","putar","ulangi","jurus"],"best":8,"limit":9,"hint":"Ujian sabuk hitam! Tunjukkan semua jurusmu.","solution":{"main":[{"id":"b1","t":"loop","n":3,"body":[{"id":"b2","t":"call"}]}],"jurus":[{"id":"b3","t":"loop","n":3,"body":[{"id":"b4","t":"act","a":"tendang"}]},
{"id":"b5","t":"act","a":"putar"},
{"id":"b6","t":"act","a":"tangkis"},
{"id":"b7","t":"act","a":"lompat"},
{"id":"b8","t":"act","a":"pukul"}]},"target":["tendang","tendang","tendang","putar","tangkis","lompat","pukul","tendang","tendang","tendang","putar","tangkis","lompat","pukul","tendang","tendang","tendang","putar","tangkis","lompat","pukul"]},
{"id":"j98","world":9,"palette":["pukul","tendang","tangkis","lompat","putar","ulangi","jurus"],"best":9,"limit":10,"hint":"Ujian sabuk hitam! Tunjukkan semua jurusmu.","solution":{"main":[{"id":"b1","t":"loop","n":2,"body":[{"id":"b2","t":"call"}]}],"jurus":[{"id":"b3","t":"loop","n":2,"body":[{"id":"b4","t":"act","a":"tangkis"},
{"id":"b5","t":"act","a":"tendang"},
{"id":"b6","t":"act","a":"lompat"}]},
{"id":"b7","t":"loop","n":2,"body":[{"id":"b8","t":"act","a":"pukul"},
{"id":"b9","t":"act","a":"putar"}]}]},"target":["tangkis","tendang","lompat","tangkis","tendang","lompat","pukul","putar","pukul","putar","tangkis","tendang","lompat","tangkis","tendang","lompat","pukul","putar","pukul","putar"]},
{"id":"j99","world":9,"palette":["pukul","tendang","tangkis","lompat","putar","ulangi","jurus"],"best":8,"limit":9,"hint":"Ujian sabuk hitam! Tunjukkan semua jurusmu.","solution":{"main":[{"id":"b1","t":"loop","n":4,"body":[{"id":"b2","t":"call"}]},
{"id":"b3","t":"act","a":"lompat"}],"jurus":[{"id":"b4","t":"act","a":"pukul"},
{"id":"b5","t":"act","a":"lompat"},
{"id":"b6","t":"act","a":"putar"},
{"id":"b7","t":"act","a":"tendang"},
{"id":"b8","t":"act","a":"tangkis"}]},"target":["pukul","lompat","putar","tendang","tangkis","pukul","lompat","putar","tendang","tangkis","pukul","lompat","putar","tendang","tangkis","pukul","lompat","putar","tendang","tangkis","lompat"]},
{"id":"j100","world":9,"palette":["pukul","tendang","tangkis","lompat","putar","ulangi","jurus"],"best":9,"limit":10,"hint":"Ujian sabuk hitam! Tunjukkan semua jurusmu.","solution":{"main":[{"id":"b1","t":"loop","n":3,"body":[{"id":"b2","t":"call"}]}],"jurus":[{"id":"b3","t":"loop","n":3,"body":[{"id":"b4","t":"act","a":"tangkis"},
{"id":"b5","t":"act","a":"tendang"}]},
{"id":"b6","t":"loop","n":2,"body":[{"id":"b7","t":"act","a":"pukul"},
{"id":"b8","t":"act","a":"putar"}]},
{"id":"b9","t":"act","a":"lompat"}]},"target":["tangkis","tendang","tangkis","tendang","tangkis","tendang","pukul","putar","pukul","putar","lompat","tangkis","tendang","tangkis","tendang","tangkis","tendang","pukul","putar","pukul","putar","lompat","tangkis","tendang","tangkis","tendang","tangkis","tendang","pukul","putar","pukul","putar","lompat"]}];
