// Level game "Jurus (konsep: fungsi)" — 100 soal (10 Level bertema × 10 coding) untuk usia 3–8 tahun.
// DIBUAT OTOMATIS oleh scripts/gen-prog.ts (lihat src/lib/koding/gen-prog.ts); jangan diedit manual.
// Peta: . kosong · # rintangan · ~ air/es · S mulai · G bintang. dir: 0 atas, 1 kanan, 2 bawah, 3 kiri.

import type { ProgLevel } from './prog';

export const JURUS: ProgLevel[] = [{"id":"j1","theme":"kebun","dir":1,"blocks":["maju","kiri","kanan"],"map":["....","S...",".~..","....","#.#G"],"hint":"Blok baru: JURUS ⚡! Isi jurusnya di kotak Jurus, lalu panggil jurus di program utama.","palette":["maju","kiri","kanan","jurus"],"best":6,"limit":6,"tip":"Jurus = [maju 3×]. Program: jurus, belok kanan, jurus","solution":{"main":[{"id":"b1","t":"call"},
{"id":"b2","t":"cmd","c":"kanan"},
{"id":"b3","t":"call"}],"jurus":[{"id":"b4","t":"cmd","c":"maju"},
{"id":"b5","t":"cmd","c":"maju"},
{"id":"b6","t":"cmd","c":"maju"}]}},
{"id":"j2","theme":"kebun","dir":1,"blocks":["maju","kiri","kanan"],"map":[".S...",".....",".....","....G","#...."],"hint":"Jurusnya dipakai lebih dari sekali. Susun sekali, pakai berkali-kali!","palette":["maju","kiri","kanan","jurus"],"best":6,"limit":6,"tip":"Jurus = [maju 3×]. Program: jurus, belok kanan, jurus","solution":{"main":[{"id":"b1","t":"call"},
{"id":"b2","t":"cmd","c":"kanan"},
{"id":"b3","t":"call"}],"jurus":[{"id":"b4","t":"cmd","c":"maju"},
{"id":"b5","t":"cmd","c":"maju"},
{"id":"b6","t":"cmd","c":"maju"}]}},
{"id":"j3","theme":"kebun","dir":1,"blocks":["maju","kiri","kanan"],"map":[".S....",".#....","#.....",".#....",".##..G","~#...."],"hint":"Jurusnya dipakai lebih dari sekali. Susun sekali, pakai berkali-kali!","palette":["maju","kiri","kanan","jurus"],"best":7,"limit":8,"tip":"Jurus = [maju 4×]. Program: jurus, belok kanan, jurus","solution":{"main":[{"id":"b1","t":"call"},
{"id":"b2","t":"cmd","c":"kanan"},
{"id":"b3","t":"call"}],"jurus":[{"id":"b4","t":"cmd","c":"maju"},
{"id":"b5","t":"cmd","c":"maju"},
{"id":"b6","t":"cmd","c":"maju"},
{"id":"b7","t":"cmd","c":"maju"}]}},
{"id":"j4","theme":"kebun","dir":1,"blocks":["maju","kiri","kanan"],"map":["#...#G","..#...",".#....","...~..",".S...."],"hint":"Jurusnya dipakai lebih dari sekali. Susun sekali, pakai berkali-kali!","palette":["maju","kiri","kanan","jurus"],"best":7,"limit":8,"tip":"Jurus = [maju 4×]. Program: jurus, belok kiri, jurus","solution":{"main":[{"id":"b1","t":"call"},
{"id":"b2","t":"cmd","c":"kiri"},
{"id":"b3","t":"call"}],"jurus":[{"id":"b4","t":"cmd","c":"maju"},
{"id":"b5","t":"cmd","c":"maju"},
{"id":"b6","t":"cmd","c":"maju"},
{"id":"b7","t":"cmd","c":"maju"}]}},
{"id":"j5","theme":"kebun","dir":3,"blocks":["maju","kiri","kanan"],"map":["..#.","..G.",".##.","..S#"],"hint":"Jurusnya dipakai lebih dari sekali. Susun sekali, pakai berkali-kali!","palette":["maju","kiri","kanan","jurus"],"best":7,"limit":7,"tip":"Jurus = [maju 2×]. Program: jurus, belok kanan, jurus, belok kanan, jurus","solution":{"main":[{"id":"b1","t":"call"},
{"id":"b2","t":"cmd","c":"kanan"},
{"id":"b3","t":"call"},
{"id":"b4","t":"cmd","c":"kanan"},
{"id":"b5","t":"call"}],"jurus":[{"id":"b6","t":"cmd","c":"maju"},
{"id":"b7","t":"cmd","c":"maju"}]}},
{"id":"j6","theme":"kebun","dir":0,"blocks":["maju","kiri","kanan"],"map":["....",".#..",".#..","G#.S"],"hint":"Jurusnya dipakai lebih dari sekali. Susun sekali, pakai berkali-kali!","palette":["maju","kiri","kanan","jurus"],"best":8,"limit":9,"tip":"Jurus = [maju 3×]. Program: jurus, belok kiri, jurus, belok kiri, jurus","solution":{"main":[{"id":"b1","t":"call"},
{"id":"b2","t":"cmd","c":"kiri"},
{"id":"b3","t":"call"},
{"id":"b4","t":"cmd","c":"kiri"},
{"id":"b5","t":"call"}],"jurus":[{"id":"b6","t":"cmd","c":"maju"},
{"id":"b7","t":"cmd","c":"maju"},
{"id":"b8","t":"cmd","c":"maju"}]}},
{"id":"j7","theme":"kebun","dir":2,"blocks":["maju","kiri","kanan"],"map":["....",".S#G","..#.","#..."],"hint":"Jurusnya dipakai lebih dari sekali. Susun sekali, pakai berkali-kali!","palette":["maju","kiri","kanan","jurus"],"best":7,"limit":7,"tip":"Jurus = [maju 2×]. Program: jurus, belok kiri, jurus, belok kiri, jurus","solution":{"main":[{"id":"b1","t":"call"},
{"id":"b2","t":"cmd","c":"kiri"},
{"id":"b3","t":"call"},
{"id":"b4","t":"cmd","c":"kiri"},
{"id":"b5","t":"call"}],"jurus":[{"id":"b6","t":"cmd","c":"maju"},
{"id":"b7","t":"cmd","c":"maju"}]}},
{"id":"j8","theme":"kebun","dir":0,"blocks":["maju","kiri","kanan"],"map":["G.....","......","..#..S"],"hint":"Jurusnya dipakai lebih dari sekali. Susun sekali, pakai berkali-kali!","palette":["maju","kiri","kanan","jurus"],"best":7,"limit":7,"tip":"Jurus = [maju 2×]. Program: jurus, belok kiri, jurus, maju, jurus","solution":{"main":[{"id":"b1","t":"call"},
{"id":"b2","t":"cmd","c":"kiri"},
{"id":"b3","t":"call"},
{"id":"b4","t":"cmd","c":"maju"},
{"id":"b5","t":"call"}],"jurus":[{"id":"b6","t":"cmd","c":"maju"},
{"id":"b7","t":"cmd","c":"maju"}]}},
{"id":"j9","theme":"kebun","dir":2,"blocks":["maju","kiri","kanan"],"map":["..#.#..S","...#.#..","........","G......."],"hint":"Jurusnya dipakai lebih dari sekali. Susun sekali, pakai berkali-kali!","palette":["maju","kiri","kanan","jurus"],"best":8,"limit":9,"tip":"Jurus = [maju 3×]. Program: jurus, belok kanan, jurus, maju, jurus","solution":{"main":[{"id":"b1","t":"call"},
{"id":"b2","t":"cmd","c":"kanan"},
{"id":"b3","t":"call"},
{"id":"b4","t":"cmd","c":"maju"},
{"id":"b5","t":"call"}],"jurus":[{"id":"b6","t":"cmd","c":"maju"},
{"id":"b7","t":"cmd","c":"maju"},
{"id":"b8","t":"cmd","c":"maju"}]}},
{"id":"j10","theme":"kebun","dir":0,"blocks":["maju","kiri","kanan"],"map":["........G","....~....","...~...#.","~S......."],"hint":"Jurusnya dipakai lebih dari sekali. Susun sekali, pakai berkali-kali!","palette":["maju","kiri","kanan","jurus"],"best":8,"limit":9,"tip":"Jurus = [maju 3×]. Program: jurus, belok kanan, jurus, maju, jurus","solution":{"main":[{"id":"b1","t":"call"},
{"id":"b2","t":"cmd","c":"kanan"},
{"id":"b3","t":"call"},
{"id":"b4","t":"cmd","c":"maju"},
{"id":"b5","t":"call"}],"jurus":[{"id":"b6","t":"cmd","c":"maju"},
{"id":"b7","t":"cmd","c":"maju"},
{"id":"b8","t":"cmd","c":"maju"}]}},
{"id":"j11","theme":"pantai","dir":3,"blocks":["maju","kiri","kanan"],"map":["....","...G","..~#","...S"],"hint":"Jurusnya bisa berisi belokan juga, lho.","palette":["maju","kiri","kanan","jurus"],"best":6,"limit":7,"tip":"Jurus = [maju 2×, belok kanan]. Program: jurus, jurus, jurus","solution":{"main":[{"id":"b1","t":"call"},
{"id":"b2","t":"call"},
{"id":"b3","t":"call"}],"jurus":[{"id":"b4","t":"cmd","c":"maju"},
{"id":"b5","t":"cmd","c":"maju"},
{"id":"b6","t":"cmd","c":"kanan"}]}},
{"id":"j12","theme":"pantai","dir":0,"blocks":["maju","kiri","kanan"],"map":["~...","#...","..~.",".G#S"],"hint":"Jurusnya bisa berisi belokan juga, lho.","palette":["maju","kiri","kanan","jurus"],"best":6,"limit":7,"tip":"Jurus = [maju 2×, belok kiri]. Program: jurus, jurus, jurus","solution":{"main":[{"id":"b1","t":"call"},
{"id":"b2","t":"call"},
{"id":"b3","t":"call"}],"jurus":[{"id":"b4","t":"cmd","c":"maju"},
{"id":"b5","t":"cmd","c":"maju"},
{"id":"b6","t":"cmd","c":"kiri"}]}},
{"id":"j13","theme":"pantai","dir":2,"blocks":["maju","kiri","kanan"],"map":[".S#.G","..#..","...~.","....."],"hint":"Jurusnya bisa berisi belokan juga, lho.","palette":["maju","kiri","kanan","jurus"],"best":7,"limit":8,"tip":"Jurus = [maju 3×, belok kiri]. Program: jurus, jurus, jurus","solution":{"main":[{"id":"b1","t":"call"},
{"id":"b2","t":"call"},
{"id":"b3","t":"call"}],"jurus":[{"id":"b4","t":"cmd","c":"maju"},
{"id":"b5","t":"cmd","c":"maju"},
{"id":"b6","t":"cmd","c":"maju"},
{"id":"b7","t":"cmd","c":"kiri"}]}},
{"id":"j14","theme":"pantai","dir":3,"blocks":["maju","kiri","kanan"],"map":["~...G","~....","..##~","....S"],"hint":"Jurusnya bisa berisi belokan juga, lho.","palette":["maju","kiri","kanan","jurus"],"best":7,"limit":8,"tip":"Jurus = [maju 3×, belok kanan]. Program: jurus, jurus, jurus","solution":{"main":[{"id":"b1","t":"call"},
{"id":"b2","t":"call"},
{"id":"b3","t":"call"}],"jurus":[{"id":"b4","t":"cmd","c":"maju"},
{"id":"b5","t":"cmd","c":"maju"},
{"id":"b6","t":"cmd","c":"maju"},
{"id":"b7","t":"cmd","c":"kanan"}]}},
{"id":"j15","theme":"pantai","dir":1,"blocks":["maju","kiri","kanan"],"map":[".G..",".##.",".S.."],"hint":"Jurusnya bisa berisi belokan juga, lho.","palette":["maju","kiri","kanan","jurus"],"best":6,"limit":7,"tip":"Jurus = [maju 2×, belok kiri]. Program: jurus, jurus, jurus","solution":{"main":[{"id":"b1","t":"call"},
{"id":"b2","t":"call"},
{"id":"b3","t":"call"}],"jurus":[{"id":"b4","t":"cmd","c":"maju"},
{"id":"b5","t":"cmd","c":"maju"},
{"id":"b6","t":"cmd","c":"kiri"}]}},
{"id":"j16","theme":"pantai","dir":1,"blocks":["maju","kiri","kanan"],"map":["....","G#..","#~#.","S..."],"hint":"Jurusnya bisa berisi belokan juga, lho.","palette":["maju","kiri","kanan","jurus"],"best":8,"limit":9,"tip":"Jurus = [maju 3×, belok kiri]. Program: jurus, jurus, jurus, maju","solution":{"main":[{"id":"b1","t":"call"},
{"id":"b2","t":"call"},
{"id":"b3","t":"call"},
{"id":"b4","t":"cmd","c":"maju"}],"jurus":[{"id":"b5","t":"cmd","c":"maju"},
{"id":"b6","t":"cmd","c":"maju"},
{"id":"b7","t":"cmd","c":"maju"},
{"id":"b8","t":"cmd","c":"kiri"}]}},
{"id":"j17","theme":"pantai","dir":0,"blocks":["maju","kiri","kanan"],"map":[".....",".#...","..~..",".G#S~"],"hint":"Jurusnya bisa berisi belokan juga, lho.","palette":["maju","kiri","kanan","jurus"],"best":8,"limit":9,"tip":"Jurus = [maju 3×, belok kiri]. Program: jurus, jurus, jurus, maju","solution":{"main":[{"id":"b1","t":"call"},
{"id":"b2","t":"call"},
{"id":"b3","t":"call"},
{"id":"b4","t":"cmd","c":"maju"}],"jurus":[{"id":"b5","t":"cmd","c":"maju"},
{"id":"b6","t":"cmd","c":"maju"},
{"id":"b7","t":"cmd","c":"maju"},
{"id":"b8","t":"cmd","c":"kiri"}]}},
{"id":"j18","theme":"pantai","dir":2,"blocks":["maju","kiri","kanan"],"map":[".G~S",".#..","..#.","...."],"hint":"Jurusnya bisa berisi belokan juga, lho.","palette":["maju","kiri","kanan","jurus"],"best":8,"limit":9,"tip":"Jurus = [maju 3×, belok kanan]. Program: jurus, jurus, jurus, maju","solution":{"main":[{"id":"b1","t":"call"},
{"id":"b2","t":"call"},
{"id":"b3","t":"call"},
{"id":"b4","t":"cmd","c":"maju"}],"jurus":[{"id":"b5","t":"cmd","c":"maju"},
{"id":"b6","t":"cmd","c":"maju"},
{"id":"b7","t":"cmd","c":"maju"},
{"id":"b8","t":"cmd","c":"kanan"}]}},
{"id":"j19","theme":"pantai","dir":0,"blocks":["maju","kiri","kanan"],"map":[".....","..~..","...#.",".~~..","..G~S"],"hint":"Jurusnya bisa berisi belokan juga, lho.","palette":["maju","kiri","kanan","jurus"],"best":10,"limit":11,"tip":"Jurus = [maju 4×, belok kiri]. Program: jurus, jurus, jurus, maju 2×","solution":{"main":[{"id":"b1","t":"call"},
{"id":"b2","t":"call"},
{"id":"b3","t":"call"},
{"id":"b4","t":"cmd","c":"maju"},
{"id":"b5","t":"cmd","c":"maju"}],"jurus":[{"id":"b6","t":"cmd","c":"maju"},
{"id":"b7","t":"cmd","c":"maju"},
{"id":"b8","t":"cmd","c":"maju"},
{"id":"b9","t":"cmd","c":"maju"},
{"id":"b10","t":"cmd","c":"kiri"}]}},
{"id":"j20","theme":"pantai","dir":2,"blocks":["maju","kiri","kanan"],"map":["..G~S","...~.","..~..",".~...",".....","....."],"hint":"Jurusnya bisa berisi belokan juga, lho.","palette":["maju","kiri","kanan","jurus"],"best":10,"limit":11,"tip":"Jurus = [maju 4×, belok kanan]. Program: jurus, jurus, jurus, maju 2×","solution":{"main":[{"id":"b1","t":"call"},
{"id":"b2","t":"call"},
{"id":"b3","t":"call"},
{"id":"b4","t":"cmd","c":"maju"},
{"id":"b5","t":"cmd","c":"maju"}],"jurus":[{"id":"b6","t":"cmd","c":"maju"},
{"id":"b7","t":"cmd","c":"maju"},
{"id":"b8","t":"cmd","c":"maju"},
{"id":"b9","t":"cmd","c":"maju"},
{"id":"b10","t":"cmd","c":"kanan"}]}},
{"id":"j21","theme":"hutan","dir":3,"blocks":["maju","kiri","kanan"],"map":[".~.S.","~..~.","..~..","G#...",".#.#."],"hint":"Buat jurus satu anak tangga, lalu panggil beberapa kali.","palette":["maju","kiri","kanan","jurus"],"best":7,"limit":8,"tip":"Jurus = [maju, belok kiri, maju, belok kanan]. Program: jurus, jurus, jurus","solution":{"main":[{"id":"b1","t":"call"},
{"id":"b2","t":"call"},
{"id":"b3","t":"call"}],"jurus":[{"id":"b4","t":"cmd","c":"maju"},
{"id":"b5","t":"cmd","c":"kiri"},
{"id":"b6","t":"cmd","c":"maju"},
{"id":"b7","t":"cmd","c":"kanan"}]}},
{"id":"j22","theme":"hutan","dir":2,"blocks":["maju","kiri","kanan"],"map":[".#..","#.#S",".~..","~..#","G.##"],"hint":"Buat jurus satu anak tangga, lalu panggil beberapa kali.","palette":["maju","kiri","kanan","jurus"],"best":7,"limit":8,"tip":"Jurus = [maju, belok kanan, maju, belok kiri]. Program: jurus, jurus, jurus","solution":{"main":[{"id":"b1","t":"call"},
{"id":"b2","t":"call"},
{"id":"b3","t":"call"}],"jurus":[{"id":"b4","t":"cmd","c":"maju"},
{"id":"b5","t":"cmd","c":"kanan"},
{"id":"b6","t":"cmd","c":"maju"},
{"id":"b7","t":"cmd","c":"kiri"}]}},
{"id":"j23","theme":"hutan","dir":0,"blocks":["maju","kiri","kanan"],"map":["....#","..#.G",".~..~","...#.",".S.##"],"hint":"Buat jurus satu anak tangga, lalu panggil beberapa kali.","palette":["maju","kiri","kanan","jurus"],"best":7,"limit":8,"tip":"Jurus = [maju, belok kanan, maju, belok kiri]. Program: jurus, jurus, jurus","solution":{"main":[{"id":"b1","t":"call"},
{"id":"b2","t":"call"},
{"id":"b3","t":"call"}],"jurus":[{"id":"b4","t":"cmd","c":"maju"},
{"id":"b5","t":"cmd","c":"kanan"},
{"id":"b6","t":"cmd","c":"maju"},
{"id":"b7","t":"cmd","c":"kiri"}]}},
{"id":"j24","theme":"hutan","dir":1,"blocks":["maju","kiri","kanan"],"map":[".S.#.","....#","..#..","...#G","~...#"],"hint":"Buat jurus satu anak tangga, lalu panggil beberapa kali.","palette":["maju","kiri","kanan","jurus"],"best":7,"limit":8,"tip":"Jurus = [maju, belok kanan, maju, belok kiri]. Program: jurus, jurus, jurus","solution":{"main":[{"id":"b1","t":"call"},
{"id":"b2","t":"call"},
{"id":"b3","t":"call"}],"jurus":[{"id":"b4","t":"cmd","c":"maju"},
{"id":"b5","t":"cmd","c":"kanan"},
{"id":"b6","t":"cmd","c":"maju"},
{"id":"b7","t":"cmd","c":"kiri"}]}},
{"id":"j25","theme":"hutan","dir":2,"blocks":["maju","kiri","kanan"],"map":["...S#",".#...","~..#.","G.~.."],"hint":"Buat jurus satu anak tangga, lalu panggil beberapa kali.","palette":["maju","kiri","kanan","jurus"],"best":7,"limit":8,"tip":"Jurus = [maju, belok kanan, maju, belok kiri]. Program: jurus, jurus, jurus","solution":{"main":[{"id":"b1","t":"call"},
{"id":"b2","t":"call"},
{"id":"b3","t":"call"}],"jurus":[{"id":"b4","t":"cmd","c":"maju"},
{"id":"b5","t":"cmd","c":"kanan"},
{"id":"b6","t":"cmd","c":"maju"},
{"id":"b7","t":"cmd","c":"kiri"}]}},
{"id":"j26","theme":"hutan","dir":1,"blocks":["maju","kiri","kanan"],"map":["#..#..","..~~.G",".##...","....#.","S..~.."],"hint":"Buat jurus satu anak tangga, lalu panggil beberapa kali.","palette":["maju","kiri","kanan","jurus"],"best":9,"limit":10,"tip":"Jurus = [maju, belok kiri, maju, belok kanan]. Program: maju, jurus, jurus, maju, jurus","solution":{"main":[{"id":"b1","t":"cmd","c":"maju"},
{"id":"b2","t":"call"},
{"id":"b3","t":"call"},
{"id":"b4","t":"cmd","c":"maju"},
{"id":"b5","t":"call"}],"jurus":[{"id":"b6","t":"cmd","c":"maju"},
{"id":"b7","t":"cmd","c":"kiri"},
{"id":"b8","t":"cmd","c":"maju"},
{"id":"b9","t":"cmd","c":"kanan"}]}},
{"id":"j27","theme":"hutan","dir":3,"blocks":["maju","kiri","kanan"],"map":["..#..S~","##.....","...##..","G.##~..",".#....."],"hint":"Buat jurus satu anak tangga, lalu panggil beberapa kali.","palette":["maju","kiri","kanan","jurus"],"best":9,"limit":10,"tip":"Jurus = [maju, belok kiri, maju, belok kanan]. Program: maju, jurus, jurus, maju, jurus","solution":{"main":[{"id":"b1","t":"cmd","c":"maju"},
{"id":"b2","t":"call"},
{"id":"b3","t":"call"},
{"id":"b4","t":"cmd","c":"maju"},
{"id":"b5","t":"call"}],"jurus":[{"id":"b6","t":"cmd","c":"maju"},
{"id":"b7","t":"cmd","c":"kiri"},
{"id":"b8","t":"cmd","c":"maju"},
{"id":"b9","t":"cmd","c":"kanan"}]}},
{"id":"j28","theme":"hutan","dir":2,"blocks":["maju","kiri","kanan"],"map":["S...","....","..##","#...","...~",".#.G"],"hint":"Buat jurus satu anak tangga, lalu panggil beberapa kali.","palette":["maju","kiri","kanan","jurus"],"best":9,"limit":10,"tip":"Jurus = [maju, belok kiri, maju, belok kanan]. Program: maju, jurus, jurus, maju, jurus","solution":{"main":[{"id":"b1","t":"cmd","c":"maju"},
{"id":"b2","t":"call"},
{"id":"b3","t":"call"},
{"id":"b4","t":"cmd","c":"maju"},
{"id":"b5","t":"call"}],"jurus":[{"id":"b6","t":"cmd","c":"maju"},
{"id":"b7","t":"cmd","c":"kiri"},
{"id":"b8","t":"cmd","c":"maju"},
{"id":"b9","t":"cmd","c":"kanan"}]}},
{"id":"j29","theme":"hutan","dir":3,"blocks":["maju","kiri","kanan"],"map":["..~..S.","~......","...##.#","G#.#.#."],"hint":"Buat jurus satu anak tangga, lalu panggil beberapa kali.","palette":["maju","kiri","kanan","jurus"],"best":9,"limit":10,"tip":"Jurus = [maju, belok kiri, maju, belok kanan]. Program: maju, jurus, jurus, maju, jurus","solution":{"main":[{"id":"b1","t":"cmd","c":"maju"},
{"id":"b2","t":"call"},
{"id":"b3","t":"call"},
{"id":"b4","t":"cmd","c":"maju"},
{"id":"b5","t":"call"}],"jurus":[{"id":"b6","t":"cmd","c":"maju"},
{"id":"b7","t":"cmd","c":"kiri"},
{"id":"b8","t":"cmd","c":"maju"},
{"id":"b9","t":"cmd","c":"kanan"}]}},
{"id":"j30","theme":"hutan","dir":0,"blocks":["maju","kiri","kanan"],"map":["G.#..","#.~..","...#.","##...",".....","~..S."],"hint":"Buat jurus satu anak tangga, lalu panggil beberapa kali.","palette":["maju","kiri","kanan","jurus"],"best":9,"limit":10,"tip":"Jurus = [maju, belok kiri, maju, belok kanan]. Program: maju, jurus, jurus, maju, jurus","solution":{"main":[{"id":"b1","t":"cmd","c":"maju"},
{"id":"b2","t":"call"},
{"id":"b3","t":"call"},
{"id":"b4","t":"cmd","c":"maju"},
{"id":"b5","t":"call"}],"jurus":[{"id":"b6","t":"cmd","c":"maju"},
{"id":"b7","t":"cmd","c":"kiri"},
{"id":"b8","t":"cmd","c":"maju"},
{"id":"b9","t":"cmd","c":"kanan"}]}},
{"id":"j31","theme":"sawah","dir":1,"blocks":["maju","kiri","kanan"],"map":[".~..~....","S.#...~G.","....~...."],"hint":"Jurus lompat pematang: naik, maju, lalu turun lagi.","palette":["maju","kiri","kanan","jurus"],"best":13,"limit":14,"tip":"Jurus = [belok kanan, maju, belok kiri, maju 2×, belok kiri, maju, belok kanan]. Program: maju, jurus, maju 2×, jurus","solution":{"main":[{"id":"b1","t":"cmd","c":"maju"},
{"id":"b2","t":"call"},
{"id":"b3","t":"cmd","c":"maju"},
{"id":"b4","t":"cmd","c":"maju"},
{"id":"b5","t":"call"}],"jurus":[{"id":"b6","t":"cmd","c":"kanan"},
{"id":"b7","t":"cmd","c":"maju"},
{"id":"b8","t":"cmd","c":"kiri"},
{"id":"b9","t":"cmd","c":"maju"},
{"id":"b10","t":"cmd","c":"maju"},
{"id":"b11","t":"cmd","c":"kiri"},
{"id":"b12","t":"cmd","c":"maju"},
{"id":"b13","t":"cmd","c":"kanan"}]}},
{"id":"j32","theme":"sawah","dir":3,"blocks":["maju","kiri","kanan"],"map":[".~..~..~","G#...~.S","...~...."],"hint":"Jurus lompat pematang: naik, maju, lalu turun lagi.","palette":["maju","kiri","kanan","jurus"],"best":13,"limit":14,"tip":"Jurus = [belok kiri, maju, belok kanan, maju 2×, belok kanan, maju, belok kiri]. Program: maju, jurus, maju 2×, jurus","solution":{"main":[{"id":"b1","t":"cmd","c":"maju"},
{"id":"b2","t":"call"},
{"id":"b3","t":"cmd","c":"maju"},
{"id":"b4","t":"cmd","c":"maju"},
{"id":"b5","t":"call"}],"jurus":[{"id":"b6","t":"cmd","c":"kiri"},
{"id":"b7","t":"cmd","c":"maju"},
{"id":"b8","t":"cmd","c":"kanan"},
{"id":"b9","t":"cmd","c":"maju"},
{"id":"b10","t":"cmd","c":"maju"},
{"id":"b11","t":"cmd","c":"kanan"},
{"id":"b12","t":"cmd","c":"maju"},
{"id":"b13","t":"cmd","c":"kiri"}]}},
{"id":"j33","theme":"sawah","dir":3,"blocks":["maju","kiri","kanan"],"map":["....~.~#.","~G#...#.S","....~...."],"hint":"Jurus lompat pematang: naik, maju, lalu turun lagi.","palette":["maju","kiri","kanan","jurus"],"best":13,"limit":14,"tip":"Jurus = [belok kiri, maju, belok kanan, maju 2×, belok kanan, maju, belok kiri]. Program: maju, jurus, maju 2×, jurus","solution":{"main":[{"id":"b1","t":"cmd","c":"maju"},
{"id":"b2","t":"call"},
{"id":"b3","t":"cmd","c":"maju"},
{"id":"b4","t":"cmd","c":"maju"},
{"id":"b5","t":"call"}],"jurus":[{"id":"b6","t":"cmd","c":"kiri"},
{"id":"b7","t":"cmd","c":"maju"},
{"id":"b8","t":"cmd","c":"kanan"},
{"id":"b9","t":"cmd","c":"maju"},
{"id":"b10","t":"cmd","c":"maju"},
{"id":"b11","t":"cmd","c":"kanan"},
{"id":"b12","t":"cmd","c":"maju"},
{"id":"b13","t":"cmd","c":"kiri"}]}},
{"id":"j34","theme":"sawah","dir":1,"blocks":["maju","kiri","kanan"],"map":[".....#...",".S.~...~G","....#..~."],"hint":"Jurus lompat pematang: naik, maju, lalu turun lagi.","palette":["maju","kiri","kanan","jurus"],"best":13,"limit":14,"tip":"Jurus = [belok kiri, maju, belok kanan, maju 2×, belok kanan, maju, belok kiri]. Program: maju, jurus, maju 2×, jurus","solution":{"main":[{"id":"b1","t":"cmd","c":"maju"},
{"id":"b2","t":"call"},
{"id":"b3","t":"cmd","c":"maju"},
{"id":"b4","t":"cmd","c":"maju"},
{"id":"b5","t":"call"}],"jurus":[{"id":"b6","t":"cmd","c":"kiri"},
{"id":"b7","t":"cmd","c":"maju"},
{"id":"b8","t":"cmd","c":"kanan"},
{"id":"b9","t":"cmd","c":"maju"},
{"id":"b10","t":"cmd","c":"maju"},
{"id":"b11","t":"cmd","c":"kanan"},
{"id":"b12","t":"cmd","c":"maju"},
{"id":"b13","t":"cmd","c":"kiri"}]}},
{"id":"j35","theme":"sawah","dir":3,"blocks":["maju","kiri","kanan"],"map":["...~....~","G~...~.S.",".~....~~."],"hint":"Jurus lompat pematang: naik, maju, lalu turun lagi.","palette":["maju","kiri","kanan","jurus"],"best":13,"limit":14,"tip":"Jurus = [belok kanan, maju, belok kiri, maju 2×, belok kiri, maju, belok kanan]. Program: maju, jurus, maju 2×, jurus","solution":{"main":[{"id":"b1","t":"cmd","c":"maju"},
{"id":"b2","t":"call"},
{"id":"b3","t":"cmd","c":"maju"},
{"id":"b4","t":"cmd","c":"maju"},
{"id":"b5","t":"call"}],"jurus":[{"id":"b6","t":"cmd","c":"kanan"},
{"id":"b7","t":"cmd","c":"maju"},
{"id":"b8","t":"cmd","c":"kiri"},
{"id":"b9","t":"cmd","c":"maju"},
{"id":"b10","t":"cmd","c":"maju"},
{"id":"b11","t":"cmd","c":"kiri"},
{"id":"b12","t":"cmd","c":"maju"},
{"id":"b13","t":"cmd","c":"kanan"}]}},
{"id":"j36","theme":"sawah","dir":3,"blocks":["maju","kiri","kanan"],"map":["..##....","...~....",".~.#.~.~","G#...~.S"],"hint":"Jurus lompat pematang: naik, maju, lalu turun lagi.","palette":["maju","kiri","kanan","jurus"],"best":15,"limit":16,"tip":"Jurus = [belok kanan, maju 2×, belok kiri, maju 2×, belok kiri, maju 2×, belok kanan]. Program: maju, jurus, maju 2×, jurus","solution":{"main":[{"id":"b1","t":"cmd","c":"maju"},
{"id":"b2","t":"call"},
{"id":"b3","t":"cmd","c":"maju"},
{"id":"b4","t":"cmd","c":"maju"},
{"id":"b5","t":"call"}],"jurus":[{"id":"b6","t":"cmd","c":"kanan"},
{"id":"b7","t":"cmd","c":"maju"},
{"id":"b8","t":"cmd","c":"maju"},
{"id":"b9","t":"cmd","c":"kiri"},
{"id":"b10","t":"cmd","c":"maju"},
{"id":"b11","t":"cmd","c":"maju"},
{"id":"b12","t":"cmd","c":"kiri"},
{"id":"b13","t":"cmd","c":"maju"},
{"id":"b14","t":"cmd","c":"maju"},
{"id":"b15","t":"cmd","c":"kanan"}]}},
{"id":"j37","theme":"sawah","dir":1,"blocks":["maju","kiri","kanan"],"map":["....~...","~.~.~.~.","S.~...~G"],"hint":"Jurus lompat pematang: naik, maju, lalu turun lagi.","palette":["maju","kiri","kanan","jurus"],"best":15,"limit":16,"tip":"Jurus = [belok kiri, maju 2×, belok kanan, maju 2×, belok kanan, maju 2×, belok kiri]. Program: maju, jurus, maju 2×, jurus","solution":{"main":[{"id":"b1","t":"cmd","c":"maju"},
{"id":"b2","t":"call"},
{"id":"b3","t":"cmd","c":"maju"},
{"id":"b4","t":"cmd","c":"maju"},
{"id":"b5","t":"call"}],"jurus":[{"id":"b6","t":"cmd","c":"kiri"},
{"id":"b7","t":"cmd","c":"maju"},
{"id":"b8","t":"cmd","c":"maju"},
{"id":"b9","t":"cmd","c":"kanan"},
{"id":"b10","t":"cmd","c":"maju"},
{"id":"b11","t":"cmd","c":"maju"},
{"id":"b12","t":"cmd","c":"kanan"},
{"id":"b13","t":"cmd","c":"maju"},
{"id":"b14","t":"cmd","c":"maju"},
{"id":"b15","t":"cmd","c":"kiri"}]}},
{"id":"j38","theme":"sawah","dir":3,"blocks":["maju","kiri","kanan"],"map":["G~...~.S",".~.~.~..","...~...."],"hint":"Jurus lompat pematang: naik, maju, lalu turun lagi.","palette":["maju","kiri","kanan","jurus"],"best":15,"limit":16,"tip":"Jurus = [belok kiri, maju 2×, belok kanan, maju 2×, belok kanan, maju 2×, belok kiri]. Program: maju, jurus, maju 2×, jurus","solution":{"main":[{"id":"b1","t":"cmd","c":"maju"},
{"id":"b2","t":"call"},
{"id":"b3","t":"cmd","c":"maju"},
{"id":"b4","t":"cmd","c":"maju"},
{"id":"b5","t":"call"}],"jurus":[{"id":"b6","t":"cmd","c":"kiri"},
{"id":"b7","t":"cmd","c":"maju"},
{"id":"b8","t":"cmd","c":"maju"},
{"id":"b9","t":"cmd","c":"kanan"},
{"id":"b10","t":"cmd","c":"maju"},
{"id":"b11","t":"cmd","c":"maju"},
{"id":"b12","t":"cmd","c":"kanan"},
{"id":"b13","t":"cmd","c":"maju"},
{"id":"b14","t":"cmd","c":"maju"},
{"id":"b15","t":"cmd","c":"kiri"}]}},
{"id":"j39","theme":"sawah","dir":1,"blocks":["maju","kiri","kanan"],"map":[".....~...","...~.~.~.",".S.#...#G"],"hint":"Jurus lompat pematang: naik, maju, lalu turun lagi.","palette":["maju","kiri","kanan","jurus"],"best":15,"limit":16,"tip":"Jurus = [belok kiri, maju 2×, belok kanan, maju 2×, belok kanan, maju 2×, belok kiri]. Program: maju, jurus, maju 2×, jurus","solution":{"main":[{"id":"b1","t":"cmd","c":"maju"},
{"id":"b2","t":"call"},
{"id":"b3","t":"cmd","c":"maju"},
{"id":"b4","t":"cmd","c":"maju"},
{"id":"b5","t":"call"}],"jurus":[{"id":"b6","t":"cmd","c":"kiri"},
{"id":"b7","t":"cmd","c":"maju"},
{"id":"b8","t":"cmd","c":"maju"},
{"id":"b9","t":"cmd","c":"kanan"},
{"id":"b10","t":"cmd","c":"maju"},
{"id":"b11","t":"cmd","c":"maju"},
{"id":"b12","t":"cmd","c":"kanan"},
{"id":"b13","t":"cmd","c":"maju"},
{"id":"b14","t":"cmd","c":"maju"},
{"id":"b15","t":"cmd","c":"kiri"}]}},
{"id":"j40","theme":"sawah","dir":1,"blocks":["maju","kiri","kanan"],"map":[".S.#...~G","...~.#.#.",".#...#..."],"hint":"Jurus lompat pematang: naik, maju, lalu turun lagi.","palette":["maju","kiri","kanan","jurus"],"best":15,"limit":16,"tip":"Jurus = [belok kanan, maju 2×, belok kiri, maju 2×, belok kiri, maju 2×, belok kanan]. Program: maju, jurus, maju 2×, jurus","solution":{"main":[{"id":"b1","t":"cmd","c":"maju"},
{"id":"b2","t":"call"},
{"id":"b3","t":"cmd","c":"maju"},
{"id":"b4","t":"cmd","c":"maju"},
{"id":"b5","t":"call"}],"jurus":[{"id":"b6","t":"cmd","c":"kanan"},
{"id":"b7","t":"cmd","c":"maju"},
{"id":"b8","t":"cmd","c":"maju"},
{"id":"b9","t":"cmd","c":"kiri"},
{"id":"b10","t":"cmd","c":"maju"},
{"id":"b11","t":"cmd","c":"maju"},
{"id":"b12","t":"cmd","c":"kiri"},
{"id":"b13","t":"cmd","c":"maju"},
{"id":"b14","t":"cmd","c":"maju"},
{"id":"b15","t":"cmd","c":"kanan"}]}},
{"id":"j41","theme":"kota","dir":3,"blocks":["maju","kiri","kanan"],"map":["~#..~##.S","~###.....","#....#...","G..~..#.."],"hint":"Di antara jurus ada jalan lurus. Jurusnya tetap sama!","palette":["maju","kiri","kanan","jurus"],"best":10,"limit":11,"tip":"Jurus = [maju, belok kiri, maju, belok kanan, maju]. Program: jurus, maju, jurus, maju, jurus","solution":{"main":[{"id":"b1","t":"call"},
{"id":"b2","t":"cmd","c":"maju"},
{"id":"b3","t":"call"},
{"id":"b4","t":"cmd","c":"maju"},
{"id":"b5","t":"call"}],"jurus":[{"id":"b6","t":"cmd","c":"maju"},
{"id":"b7","t":"cmd","c":"kiri"},
{"id":"b8","t":"cmd","c":"maju"},
{"id":"b9","t":"cmd","c":"kanan"},
{"id":"b10","t":"cmd","c":"maju"}]}},
{"id":"j42","theme":"kota","dir":3,"blocks":["maju","kiri","kanan"],"map":["G...#...#","#....~#..","..#~.....","#.#.#...S"],"hint":"Di antara jurus ada jalan lurus. Jurusnya tetap sama!","palette":["maju","kiri","kanan","jurus"],"best":10,"limit":11,"tip":"Jurus = [maju, belok kanan, maju, belok kiri, maju]. Program: jurus, maju, jurus, maju, jurus","solution":{"main":[{"id":"b1","t":"call"},
{"id":"b2","t":"cmd","c":"maju"},
{"id":"b3","t":"call"},
{"id":"b4","t":"cmd","c":"maju"},
{"id":"b5","t":"call"}],"jurus":[{"id":"b6","t":"cmd","c":"maju"},
{"id":"b7","t":"cmd","c":"kanan"},
{"id":"b8","t":"cmd","c":"maju"},
{"id":"b9","t":"cmd","c":"kiri"},
{"id":"b10","t":"cmd","c":"maju"}]}},
{"id":"j43","theme":"kota","dir":1,"blocks":["maju","kiri","kanan"],"map":["S.###.#~.",".....~#..","#~~.....#","....#...G","......#.."],"hint":"Di antara jurus ada jalan lurus. Jurusnya tetap sama!","palette":["maju","kiri","kanan","jurus"],"best":10,"limit":11,"tip":"Jurus = [maju, belok kanan, maju, belok kiri, maju]. Program: jurus, maju, jurus, maju, jurus","solution":{"main":[{"id":"b1","t":"call"},
{"id":"b2","t":"cmd","c":"maju"},
{"id":"b3","t":"call"},
{"id":"b4","t":"cmd","c":"maju"},
{"id":"b5","t":"call"}],"jurus":[{"id":"b6","t":"cmd","c":"maju"},
{"id":"b7","t":"cmd","c":"kanan"},
{"id":"b8","t":"cmd","c":"maju"},
{"id":"b9","t":"cmd","c":"kiri"},
{"id":"b10","t":"cmd","c":"maju"}]}},
{"id":"j44","theme":"kota","dir":1,"blocks":["maju","kiri","kanan"],"map":["......~.G",".#~.....#",".....~..#","S.#~...#."],"hint":"Di antara jurus ada jalan lurus. Jurusnya tetap sama!","palette":["maju","kiri","kanan","jurus"],"best":10,"limit":11,"tip":"Jurus = [maju, belok kiri, maju, belok kanan, maju]. Program: jurus, maju, jurus, maju, jurus","solution":{"main":[{"id":"b1","t":"call"},
{"id":"b2","t":"cmd","c":"maju"},
{"id":"b3","t":"call"},
{"id":"b4","t":"cmd","c":"maju"},
{"id":"b5","t":"call"}],"jurus":[{"id":"b6","t":"cmd","c":"maju"},
{"id":"b7","t":"cmd","c":"kiri"},
{"id":"b8","t":"cmd","c":"maju"},
{"id":"b9","t":"cmd","c":"kanan"},
{"id":"b10","t":"cmd","c":"maju"}]}},
{"id":"j45","theme":"kota","dir":1,"blocks":["maju","kiri","kanan"],"map":[".....#..G","...#....#",".....####","S.#.#...."],"hint":"Di antara jurus ada jalan lurus. Jurusnya tetap sama!","palette":["maju","kiri","kanan","jurus"],"best":10,"limit":11,"tip":"Jurus = [maju, belok kiri, maju, belok kanan, maju]. Program: jurus, maju, jurus, maju, jurus","solution":{"main":[{"id":"b1","t":"call"},
{"id":"b2","t":"cmd","c":"maju"},
{"id":"b3","t":"call"},
{"id":"b4","t":"cmd","c":"maju"},
{"id":"b5","t":"call"}],"jurus":[{"id":"b6","t":"cmd","c":"maju"},
{"id":"b7","t":"cmd","c":"kiri"},
{"id":"b8","t":"cmd","c":"maju"},
{"id":"b9","t":"cmd","c":"kanan"},
{"id":"b10","t":"cmd","c":"maju"}]}},
{"id":"j46","theme":"kota","dir":2,"blocks":["maju","kiri","kanan"],"map":["#.~.#","...~S","..#..","#~..~","#..##","#..#.","G.###"],"hint":"Di antara jurus ada jalan lurus. Jurusnya tetap sama!","palette":["maju","kiri","kanan","jurus"],"best":11,"limit":12,"tip":"Jurus = [maju, belok kanan, maju, belok kiri, maju, belok kanan, maju, belok kiri]. Program: jurus, maju, jurus","solution":{"main":[{"id":"b1","t":"call"},
{"id":"b2","t":"cmd","c":"maju"},
{"id":"b3","t":"call"}],"jurus":[{"id":"b4","t":"cmd","c":"maju"},
{"id":"b5","t":"cmd","c":"kanan"},
{"id":"b6","t":"cmd","c":"maju"},
{"id":"b7","t":"cmd","c":"kiri"},
{"id":"b8","t":"cmd","c":"maju"},
{"id":"b9","t":"cmd","c":"kanan"},
{"id":"b10","t":"cmd","c":"maju"},
{"id":"b11","t":"cmd","c":"kiri"}]}},
{"id":"j47","theme":"kota","dir":2,"blocks":["maju","kiri","kanan"],"map":["....S",".##..","#...#",".~.##","#..##","G.#~."],"hint":"Di antara jurus ada jalan lurus. Jurusnya tetap sama!","palette":["maju","kiri","kanan","jurus"],"best":11,"limit":12,"tip":"Jurus = [maju, belok kanan, maju, belok kiri, maju, belok kanan, maju, belok kiri]. Program: jurus, maju, jurus","solution":{"main":[{"id":"b1","t":"call"},
{"id":"b2","t":"cmd","c":"maju"},
{"id":"b3","t":"call"}],"jurus":[{"id":"b4","t":"cmd","c":"maju"},
{"id":"b5","t":"cmd","c":"kanan"},
{"id":"b6","t":"cmd","c":"maju"},
{"id":"b7","t":"cmd","c":"kiri"},
{"id":"b8","t":"cmd","c":"maju"},
{"id":"b9","t":"cmd","c":"kanan"},
{"id":"b10","t":"cmd","c":"maju"},
{"id":"b11","t":"cmd","c":"kiri"}]}},
{"id":"j48","theme":"kota","dir":2,"blocks":["maju","kiri","kanan"],"map":[".~..#","##..S","..#..","....#",".#.#.","#..#~","G.#.#"],"hint":"Di antara jurus ada jalan lurus. Jurusnya tetap sama!","palette":["maju","kiri","kanan","jurus"],"best":11,"limit":12,"tip":"Jurus = [maju, belok kanan, maju, belok kiri, maju, belok kanan, maju, belok kiri]. Program: jurus, maju, jurus","solution":{"main":[{"id":"b1","t":"call"},
{"id":"b2","t":"cmd","c":"maju"},
{"id":"b3","t":"call"}],"jurus":[{"id":"b4","t":"cmd","c":"maju"},
{"id":"b5","t":"cmd","c":"kanan"},
{"id":"b6","t":"cmd","c":"maju"},
{"id":"b7","t":"cmd","c":"kiri"},
{"id":"b8","t":"cmd","c":"maju"},
{"id":"b9","t":"cmd","c":"kanan"},
{"id":"b10","t":"cmd","c":"maju"},
{"id":"b11","t":"cmd","c":"kiri"}]}},
{"id":"j49","theme":"kota","dir":1,"blocks":["maju","kiri","kanan"],"map":[".#....","#..#~G","~..#..",".~...#","...##.","S.##.."],"hint":"Di antara jurus ada jalan lurus. Jurusnya tetap sama!","palette":["maju","kiri","kanan","jurus"],"best":11,"limit":12,"tip":"Jurus = [maju, belok kiri, maju, belok kanan, maju, belok kiri, maju, belok kanan]. Program: jurus, maju, jurus","solution":{"main":[{"id":"b1","t":"call"},
{"id":"b2","t":"cmd","c":"maju"},
{"id":"b3","t":"call"}],"jurus":[{"id":"b4","t":"cmd","c":"maju"},
{"id":"b5","t":"cmd","c":"kiri"},
{"id":"b6","t":"cmd","c":"maju"},
{"id":"b7","t":"cmd","c":"kanan"},
{"id":"b8","t":"cmd","c":"maju"},
{"id":"b9","t":"cmd","c":"kiri"},
{"id":"b10","t":"cmd","c":"maju"},
{"id":"b11","t":"cmd","c":"kanan"}]}},
{"id":"j50","theme":"kota","dir":1,"blocks":["maju","kiri","kanan"],"map":["##....","S.#~..","...~..","##...#","..#...","..#.#G"],"hint":"Di antara jurus ada jalan lurus. Jurusnya tetap sama!","palette":["maju","kiri","kanan","jurus"],"best":11,"limit":12,"tip":"Jurus = [maju, belok kanan, maju, belok kiri, maju, belok kanan, maju, belok kiri]. Program: jurus, maju, jurus","solution":{"main":[{"id":"b1","t":"call"},
{"id":"b2","t":"cmd","c":"maju"},
{"id":"b3","t":"call"}],"jurus":[{"id":"b4","t":"cmd","c":"maju"},
{"id":"b5","t":"cmd","c":"kanan"},
{"id":"b6","t":"cmd","c":"maju"},
{"id":"b7","t":"cmd","c":"kiri"},
{"id":"b8","t":"cmd","c":"maju"},
{"id":"b9","t":"cmd","c":"kanan"},
{"id":"b10","t":"cmd","c":"maju"},
{"id":"b11","t":"cmd","c":"kiri"}]}},
{"id":"j51","theme":"salju","dir":0,"blocks":["maju","kiri","kanan"],"map":[".#...~G",".#.~...",".~##..#","~......","~......","...#.~~","S..#..."],"hint":"Jurusnya panjang. Hemat sekali kalau dipakai tiga kali!","palette":["maju","kiri","kanan","jurus"],"best":9,"limit":10,"tip":"Jurus = [maju, belok kanan, maju 2×, belok kiri, maju]. Program: jurus, jurus, jurus","solution":{"main":[{"id":"b1","t":"call"},
{"id":"b2","t":"call"},
{"id":"b3","t":"call"}],"jurus":[{"id":"b4","t":"cmd","c":"maju"},
{"id":"b5","t":"cmd","c":"kanan"},
{"id":"b6","t":"cmd","c":"maju"},
{"id":"b7","t":"cmd","c":"maju"},
{"id":"b8","t":"cmd","c":"kiri"},
{"id":"b9","t":"cmd","c":"maju"}]}},
{"id":"j52","theme":"salju","dir":0,"blocks":["maju","kiri","kanan"],"map":["#G~.~...","....~...",".~.....~",".#~....~","...##.~.",".#......","...##~~S"],"hint":"Jurusnya panjang. Hemat sekali kalau dipakai tiga kali!","palette":["maju","kiri","kanan","jurus"],"best":9,"limit":10,"tip":"Jurus = [maju, belok kiri, maju 2×, belok kanan, maju]. Program: jurus, jurus, jurus","solution":{"main":[{"id":"b1","t":"call"},
{"id":"b2","t":"call"},
{"id":"b3","t":"call"}],"jurus":[{"id":"b4","t":"cmd","c":"maju"},
{"id":"b5","t":"cmd","c":"kiri"},
{"id":"b6","t":"cmd","c":"maju"},
{"id":"b7","t":"cmd","c":"maju"},
{"id":"b8","t":"cmd","c":"kanan"},
{"id":"b9","t":"cmd","c":"maju"}]}},
{"id":"j53","theme":"salju","dir":1,"blocks":["maju","kiri","kanan"],"map":[".#..#..G","...~...~",".~......","..#~.#..",".....~..","#..#....",".S.#.##."],"hint":"Jurusnya panjang. Hemat sekali kalau dipakai tiga kali!","palette":["maju","kiri","kanan","jurus"],"best":9,"limit":10,"tip":"Jurus = [maju, belok kiri, maju 2×, belok kanan, maju]. Program: jurus, jurus, jurus","solution":{"main":[{"id":"b1","t":"call"},
{"id":"b2","t":"call"},
{"id":"b3","t":"call"}],"jurus":[{"id":"b4","t":"cmd","c":"maju"},
{"id":"b5","t":"cmd","c":"kiri"},
{"id":"b6","t":"cmd","c":"maju"},
{"id":"b7","t":"cmd","c":"maju"},
{"id":"b8","t":"cmd","c":"kanan"},
{"id":"b9","t":"cmd","c":"maju"}]}},
{"id":"j54","theme":"salju","dir":0,"blocks":["maju","kiri","kanan"],"map":["....~.G",".#.....","~.##...","~....##","...~...","...~.~.","S#.#..."],"hint":"Jurusnya panjang. Hemat sekali kalau dipakai tiga kali!","palette":["maju","kiri","kanan","jurus"],"best":9,"limit":10,"tip":"Jurus = [maju, belok kanan, maju 2×, belok kiri, maju]. Program: jurus, jurus, jurus","solution":{"main":[{"id":"b1","t":"call"},
{"id":"b2","t":"call"},
{"id":"b3","t":"call"}],"jurus":[{"id":"b4","t":"cmd","c":"maju"},
{"id":"b5","t":"cmd","c":"kanan"},
{"id":"b6","t":"cmd","c":"maju"},
{"id":"b7","t":"cmd","c":"maju"},
{"id":"b8","t":"cmd","c":"kiri"},
{"id":"b9","t":"cmd","c":"maju"}]}},
{"id":"j55","theme":"salju","dir":2,"blocks":["maju","kiri","kanan"],"map":[".....#S","#~.#...","...#.~~",".......","#....~.","....~..","G#.#..."],"hint":"Jurusnya panjang. Hemat sekali kalau dipakai tiga kali!","palette":["maju","kiri","kanan","jurus"],"best":9,"limit":10,"tip":"Jurus = [maju, belok kanan, maju 2×, belok kiri, maju]. Program: jurus, jurus, jurus","solution":{"main":[{"id":"b1","t":"call"},
{"id":"b2","t":"call"},
{"id":"b3","t":"call"}],"jurus":[{"id":"b4","t":"cmd","c":"maju"},
{"id":"b5","t":"cmd","c":"kanan"},
{"id":"b6","t":"cmd","c":"maju"},
{"id":"b7","t":"cmd","c":"maju"},
{"id":"b8","t":"cmd","c":"kiri"},
{"id":"b9","t":"cmd","c":"maju"}]}},
{"id":"j56","theme":"salju","dir":0,"blocks":["maju","kiri","kanan"],"map":[".G......",".#~..~~.","......#.","..~....#","~~..#...","...##...","#.#..~.S"],"hint":"Jurusnya panjang. Hemat sekali kalau dipakai tiga kali!","palette":["maju","kiri","kanan","jurus"],"best":9,"limit":10,"tip":"Jurus = [maju 2×, belok kiri, maju 2×, belok kanan]. Program: jurus, jurus, jurus","solution":{"main":[{"id":"b1","t":"call"},
{"id":"b2","t":"call"},
{"id":"b3","t":"call"}],"jurus":[{"id":"b4","t":"cmd","c":"maju"},
{"id":"b5","t":"cmd","c":"maju"},
{"id":"b6","t":"cmd","c":"kiri"},
{"id":"b7","t":"cmd","c":"maju"},
{"id":"b8","t":"cmd","c":"maju"},
{"id":"b9","t":"cmd","c":"kanan"}]}},
{"id":"j57","theme":"salju","dir":3,"blocks":["maju","kiri","kanan"],"map":["...#..S",".......","~......",".~.~#..",".....~.","..#.#..","G...~.."],"hint":"Jurusnya panjang. Hemat sekali kalau dipakai tiga kali!","palette":["maju","kiri","kanan","jurus"],"best":9,"limit":10,"tip":"Jurus = [maju 2×, belok kiri, maju 2×, belok kanan]. Program: jurus, jurus, jurus","solution":{"main":[{"id":"b1","t":"call"},
{"id":"b2","t":"call"},
{"id":"b3","t":"call"}],"jurus":[{"id":"b4","t":"cmd","c":"maju"},
{"id":"b5","t":"cmd","c":"maju"},
{"id":"b6","t":"cmd","c":"kiri"},
{"id":"b7","t":"cmd","c":"maju"},
{"id":"b8","t":"cmd","c":"maju"},
{"id":"b9","t":"cmd","c":"kanan"}]}},
{"id":"j58","theme":"salju","dir":1,"blocks":["maju","kiri","kanan"],"map":["#S..#...","....#...","......#.",".#.~....","...##...","....#...","#.~~.~.G"],"hint":"Jurusnya panjang. Hemat sekali kalau dipakai tiga kali!","palette":["maju","kiri","kanan","jurus"],"best":9,"limit":10,"tip":"Jurus = [maju 2×, belok kanan, maju 2×, belok kiri]. Program: jurus, jurus, jurus","solution":{"main":[{"id":"b1","t":"call"},
{"id":"b2","t":"call"},
{"id":"b3","t":"call"}],"jurus":[{"id":"b4","t":"cmd","c":"maju"},
{"id":"b5","t":"cmd","c":"maju"},
{"id":"b6","t":"cmd","c":"kanan"},
{"id":"b7","t":"cmd","c":"maju"},
{"id":"b8","t":"cmd","c":"maju"},
{"id":"b9","t":"cmd","c":"kiri"}]}},
{"id":"j59","theme":"salju","dir":3,"blocks":["maju","kiri","kanan"],"map":["G~.....",".#.....",".......","~...~~.","#.....#","~..#...","~.~...S"],"hint":"Jurusnya panjang. Hemat sekali kalau dipakai tiga kali!","palette":["maju","kiri","kanan","jurus"],"best":9,"limit":10,"tip":"Jurus = [maju 2×, belok kanan, maju 2×, belok kiri]. Program: jurus, jurus, jurus","solution":{"main":[{"id":"b1","t":"call"},
{"id":"b2","t":"call"},
{"id":"b3","t":"call"}],"jurus":[{"id":"b4","t":"cmd","c":"maju"},
{"id":"b5","t":"cmd","c":"maju"},
{"id":"b6","t":"cmd","c":"kanan"},
{"id":"b7","t":"cmd","c":"maju"},
{"id":"b8","t":"cmd","c":"maju"},
{"id":"b9","t":"cmd","c":"kiri"}]}},
{"id":"j60","theme":"salju","dir":0,"blocks":["maju","kiri","kanan"],"map":["~.~.~..G","......~#","..~...~.",".~...~..","....~...","..~#..~#",".S......"],"hint":"Jurusnya panjang. Hemat sekali kalau dipakai tiga kali!","palette":["maju","kiri","kanan","jurus"],"best":9,"limit":10,"tip":"Jurus = [maju 2×, belok kanan, maju 2×, belok kiri]. Program: jurus, jurus, jurus","solution":{"main":[{"id":"b1","t":"call"},
{"id":"b2","t":"call"},
{"id":"b3","t":"call"}],"jurus":[{"id":"b4","t":"cmd","c":"maju"},
{"id":"b5","t":"cmd","c":"maju"},
{"id":"b6","t":"cmd","c":"kanan"},
{"id":"b7","t":"cmd","c":"maju"},
{"id":"b8","t":"cmd","c":"maju"},
{"id":"b9","t":"cmd","c":"kiri"}]}},
{"id":"j61","theme":"gurun","dir":3,"blocks":["maju","kiri","kanan"],"map":["#....","...G.","...#.",".#~.#","...S."],"hint":"Sekarang ulangi boleh dipakai di dalam jurus!","palette":["maju","kiri","kanan","ulangi","jurus"],"best":6,"limit":7,"tip":"Jurus = [ulangi 3 kali [maju], belok kanan]. Program: jurus, jurus, jurus","solution":{"main":[{"id":"b1","t":"call"},
{"id":"b2","t":"call"},
{"id":"b3","t":"call"}],"jurus":[{"id":"b4","t":"loop","n":3,"body":[{"id":"b5","t":"cmd","c":"maju"}]},
{"id":"b6","t":"cmd","c":"kanan"}]}},
{"id":"j62","theme":"gurun","dir":3,"blocks":["maju","kiri","kanan"],"map":["....G",".....",".~#..","...#~","....S"],"hint":"Sekarang ulangi boleh dipakai di dalam jurus!","palette":["maju","kiri","kanan","ulangi","jurus"],"best":6,"limit":7,"tip":"Jurus = [ulangi 4 kali [maju], belok kanan]. Program: jurus, jurus, jurus","solution":{"main":[{"id":"b1","t":"call"},
{"id":"b2","t":"call"},
{"id":"b3","t":"call"}],"jurus":[{"id":"b4","t":"loop","n":4,"body":[{"id":"b5","t":"cmd","c":"maju"}]},
{"id":"b6","t":"cmd","c":"kanan"}]}},
{"id":"j63","theme":"gurun","dir":2,"blocks":["maju","kiri","kanan"],"map":["#...#","S#.G#",".#...",".#...","....."],"hint":"Sekarang ulangi boleh dipakai di dalam jurus!","palette":["maju","kiri","kanan","ulangi","jurus"],"best":6,"limit":7,"tip":"Jurus = [ulangi 3 kali [maju], belok kiri]. Program: jurus, jurus, jurus","solution":{"main":[{"id":"b1","t":"call"},
{"id":"b2","t":"call"},
{"id":"b3","t":"call"}],"jurus":[{"id":"b4","t":"loop","n":3,"body":[{"id":"b5","t":"cmd","c":"maju"}]},
{"id":"b6","t":"cmd","c":"kiri"}]}},
{"id":"j64","theme":"gurun","dir":0,"blocks":["maju","kiri","kanan"],"map":["..#.#",".....",".#.#.",".#...","..~..","S.#.G"],"hint":"Sekarang ulangi boleh dipakai di dalam jurus!","palette":["maju","kiri","kanan","ulangi","jurus"],"best":6,"limit":7,"tip":"Jurus = [ulangi 4 kali [maju], belok kanan]. Program: jurus, jurus, jurus","solution":{"main":[{"id":"b1","t":"call"},
{"id":"b2","t":"call"},
{"id":"b3","t":"call"}],"jurus":[{"id":"b4","t":"loop","n":4,"body":[{"id":"b5","t":"cmd","c":"maju"}]},
{"id":"b6","t":"cmd","c":"kanan"}]}},
{"id":"j65","theme":"gurun","dir":2,"blocks":["maju","kiri","kanan"],"map":["G##..S","..~...",".###..","...##.",".#....","......"],"hint":"Sekarang ulangi boleh dipakai di dalam jurus!","palette":["maju","kiri","kanan","ulangi","jurus"],"best":6,"limit":7,"tip":"Jurus = [ulangi 5 kali [maju], belok kanan]. Program: jurus, jurus, jurus","solution":{"main":[{"id":"b1","t":"call"},
{"id":"b2","t":"call"},
{"id":"b3","t":"call"}],"jurus":[{"id":"b4","t":"loop","n":5,"body":[{"id":"b5","t":"cmd","c":"maju"}]},
{"id":"b6","t":"cmd","c":"kanan"}]}},
{"id":"j66","theme":"gurun","dir":3,"blocks":["maju","kiri","kanan"],"map":[".#...#","...S..","..##..",".#.~#.","....G#"],"hint":"Sekarang ulangi boleh dipakai di dalam jurus!","palette":["maju","kiri","kanan","ulangi","jurus"],"best":7,"limit":8,"tip":"Jurus = [ulangi 3 kali [maju], belok kiri]. Program: jurus, jurus, maju, jurus","solution":{"main":[{"id":"b1","t":"call"},
{"id":"b2","t":"call"},
{"id":"b3","t":"cmd","c":"maju"},
{"id":"b4","t":"call"}],"jurus":[{"id":"b5","t":"loop","n":3,"body":[{"id":"b6","t":"cmd","c":"maju"}]},
{"id":"b7","t":"cmd","c":"kiri"}]}},
{"id":"j67","theme":"gurun","dir":1,"blocks":["maju","kiri","kanan"],"map":[".###...","#.S....","....#~.","#.#.#..",".~.#...",".G....."],"hint":"Sekarang ulangi boleh dipakai di dalam jurus!","palette":["maju","kiri","kanan","ulangi","jurus"],"best":7,"limit":8,"tip":"Jurus = [ulangi 4 kali [maju], belok kanan]. Program: jurus, jurus, maju, jurus","solution":{"main":[{"id":"b1","t":"call"},
{"id":"b2","t":"call"},
{"id":"b3","t":"cmd","c":"maju"},
{"id":"b4","t":"call"}],"jurus":[{"id":"b5","t":"loop","n":4,"body":[{"id":"b6","t":"cmd","c":"maju"}]},
{"id":"b7","t":"cmd","c":"kanan"}]}},
{"id":"j68","theme":"gurun","dir":1,"blocks":["maju","kiri","kanan"],"map":["G......","#.~....","...#...",".##.#..","#S.....",".....#."],"hint":"Sekarang ulangi boleh dipakai di dalam jurus!","palette":["maju","kiri","kanan","ulangi","jurus"],"best":7,"limit":8,"tip":"Jurus = [ulangi 4 kali [maju], belok kiri]. Program: jurus, jurus, maju, jurus","solution":{"main":[{"id":"b1","t":"call"},
{"id":"b2","t":"call"},
{"id":"b3","t":"cmd","c":"maju"},
{"id":"b4","t":"call"}],"jurus":[{"id":"b5","t":"loop","n":4,"body":[{"id":"b6","t":"cmd","c":"maju"}]},
{"id":"b7","t":"cmd","c":"kiri"}]}},
{"id":"j69","theme":"gurun","dir":1,"blocks":["maju","kiri","kanan"],"map":["....#...","G.......",".#.....#",".....~.~",".##.....","#..##...",".S.....~"],"hint":"Sekarang ulangi boleh dipakai di dalam jurus!","palette":["maju","kiri","kanan","ulangi","jurus"],"best":7,"limit":8,"tip":"Jurus = [ulangi 5 kali [maju], belok kiri]. Program: jurus, jurus, maju, jurus","solution":{"main":[{"id":"b1","t":"call"},
{"id":"b2","t":"call"},
{"id":"b3","t":"cmd","c":"maju"},
{"id":"b4","t":"call"}],"jurus":[{"id":"b5","t":"loop","n":5,"body":[{"id":"b6","t":"cmd","c":"maju"}]},
{"id":"b7","t":"cmd","c":"kiri"}]}},
{"id":"j70","theme":"gurun","dir":0,"blocks":["maju","kiri","kanan"],"map":[".......","#.##...","..##...","#...#..","..#.#..",".S..#~.","#....~G"],"hint":"Sekarang ulangi boleh dipakai di dalam jurus!","palette":["maju","kiri","kanan","ulangi","jurus"],"best":7,"limit":8,"tip":"Jurus = [ulangi 5 kali [maju], belok kanan]. Program: jurus, jurus, maju, jurus","solution":{"main":[{"id":"b1","t":"call"},
{"id":"b2","t":"call"},
{"id":"b3","t":"cmd","c":"maju"},
{"id":"b4","t":"call"}],"jurus":[{"id":"b5","t":"loop","n":5,"body":[{"id":"b6","t":"cmd","c":"maju"}]},
{"id":"b7","t":"cmd","c":"kanan"}]}},
{"id":"j71","theme":"laut","dir":2,"blocks":["maju","kiri","kanan"],"map":["S.##","..~.","#..#","##.G"],"hint":"Jurus juga bisa dipanggil di dalam ulangi!","palette":["maju","kiri","kanan","ulangi","jurus"],"best":6,"limit":7,"tip":"Jurus = [maju, belok kiri, maju, belok kanan]. Program: ulangi 3 kali [jurus]","solution":{"main":[{"id":"b1","t":"loop","n":3,"body":[{"id":"b2","t":"call"}]}],"jurus":[{"id":"b3","t":"cmd","c":"maju"},
{"id":"b4","t":"cmd","c":"kiri"},
{"id":"b5","t":"cmd","c":"maju"},
{"id":"b6","t":"cmd","c":"kanan"}]}},
{"id":"j72","theme":"laut","dir":0,"blocks":["maju","kiri","kanan"],"map":["..~.G","##..~","...#.","~S.##"],"hint":"Jurus juga bisa dipanggil di dalam ulangi!","palette":["maju","kiri","kanan","ulangi","jurus"],"best":6,"limit":7,"tip":"Jurus = [maju, belok kanan, maju, belok kiri]. Program: ulangi 3 kali [jurus]","solution":{"main":[{"id":"b1","t":"loop","n":3,"body":[{"id":"b2","t":"call"}]}],"jurus":[{"id":"b3","t":"cmd","c":"maju"},
{"id":"b4","t":"cmd","c":"kanan"},
{"id":"b5","t":"cmd","c":"maju"},
{"id":"b6","t":"cmd","c":"kiri"}]}},
{"id":"j73","theme":"laut","dir":3,"blocks":["maju","kiri","kanan"],"map":["..#.S",".#...","~..#.","..#..","G~.~."],"hint":"Jurus juga bisa dipanggil di dalam ulangi!","palette":["maju","kiri","kanan","ulangi","jurus"],"best":6,"limit":7,"tip":"Jurus = [maju, belok kiri, maju, belok kanan]. Program: ulangi 4 kali [jurus]","solution":{"main":[{"id":"b1","t":"loop","n":4,"body":[{"id":"b2","t":"call"}]}],"jurus":[{"id":"b3","t":"cmd","c":"maju"},
{"id":"b4","t":"cmd","c":"kiri"},
{"id":"b5","t":"cmd","c":"maju"},
{"id":"b6","t":"cmd","c":"kanan"}]}},
{"id":"j74","theme":"laut","dir":2,"blocks":["maju","kiri","kanan"],"map":["......","....S#","..#...",".#..~.","#..#..","G.~..#"],"hint":"Jurus juga bisa dipanggil di dalam ulangi!","palette":["maju","kiri","kanan","ulangi","jurus"],"best":6,"limit":7,"tip":"Jurus = [maju, belok kanan, maju, belok kiri]. Program: ulangi 4 kali [jurus]","solution":{"main":[{"id":"b1","t":"loop","n":4,"body":[{"id":"b2","t":"call"}]}],"jurus":[{"id":"b3","t":"cmd","c":"maju"},
{"id":"b4","t":"cmd","c":"kanan"},
{"id":"b5","t":"cmd","c":"maju"},
{"id":"b6","t":"cmd","c":"kiri"}]}},
{"id":"j75","theme":"laut","dir":0,"blocks":["maju","kiri","kanan"],"map":["..##..G","#.#..~.",".~..~..","#..#.#.",".S....#"],"hint":"Jurus juga bisa dipanggil di dalam ulangi!","palette":["maju","kiri","kanan","ulangi","jurus"],"best":10,"limit":11,"tip":"Jurus = [maju, belok kanan, maju, belok kiri]. Program: ulangi 3 kali [jurus], maju, belok kanan, maju 2×","solution":{"main":[{"id":"b1","t":"loop","n":3,"body":[{"id":"b2","t":"call"}]},
{"id":"b3","t":"cmd","c":"maju"},
{"id":"b4","t":"cmd","c":"kanan"},
{"id":"b5","t":"cmd","c":"maju"},
{"id":"b6","t":"cmd","c":"maju"}],"jurus":[{"id":"b7","t":"cmd","c":"maju"},
{"id":"b8","t":"cmd","c":"kanan"},
{"id":"b9","t":"cmd","c":"maju"},
{"id":"b10","t":"cmd","c":"kiri"}]}},
{"id":"j76","theme":"laut","dir":0,"blocks":["maju","kiri","kanan"],"map":["G..#...","~...##.",".~~..#.","#.##...",".#...S~"],"hint":"Jurus juga bisa dipanggil di dalam ulangi!","palette":["maju","kiri","kanan","ulangi","jurus"],"best":10,"limit":11,"tip":"Jurus = [maju, belok kiri, maju, belok kanan]. Program: ulangi 3 kali [jurus], maju, belok kiri, maju 2×","solution":{"main":[{"id":"b1","t":"loop","n":3,"body":[{"id":"b2","t":"call"}]},
{"id":"b3","t":"cmd","c":"maju"},
{"id":"b4","t":"cmd","c":"kiri"},
{"id":"b5","t":"cmd","c":"maju"},
{"id":"b6","t":"cmd","c":"maju"}],"jurus":[{"id":"b7","t":"cmd","c":"maju"},
{"id":"b8","t":"cmd","c":"kiri"},
{"id":"b9","t":"cmd","c":"maju"},
{"id":"b10","t":"cmd","c":"kanan"}]}},
{"id":"j77","theme":"laut","dir":0,"blocks":["maju","kiri","kanan"],"map":["G..#..#","~#..##~","..#..##","~..#..#","..~#~..",".#.~..S"],"hint":"Jurus juga bisa dipanggil di dalam ulangi!","palette":["maju","kiri","kanan","ulangi","jurus"],"best":10,"limit":11,"tip":"Jurus = [maju, belok kiri, maju, belok kanan]. Program: ulangi 4 kali [jurus], maju, belok kiri, maju 2×","solution":{"main":[{"id":"b1","t":"loop","n":4,"body":[{"id":"b2","t":"call"}]},
{"id":"b3","t":"cmd","c":"maju"},
{"id":"b4","t":"cmd","c":"kiri"},
{"id":"b5","t":"cmd","c":"maju"},
{"id":"b6","t":"cmd","c":"maju"}],"jurus":[{"id":"b7","t":"cmd","c":"maju"},
{"id":"b8","t":"cmd","c":"kiri"},
{"id":"b9","t":"cmd","c":"maju"},
{"id":"b10","t":"cmd","c":"kanan"}]}},
{"id":"j78","theme":"laut","dir":2,"blocks":["maju","kiri","kanan"],"map":["S~.##..#","..#.#...","~..~..#.",".#..#.#.","#.#..#..","..##..G."],"hint":"Jurus juga bisa dipanggil di dalam ulangi!","palette":["maju","kiri","kanan","ulangi","jurus"],"best":10,"limit":11,"tip":"Jurus = [maju, belok kiri, maju, belok kanan]. Program: ulangi 4 kali [jurus], maju, belok kiri, maju 2×","solution":{"main":[{"id":"b1","t":"loop","n":4,"body":[{"id":"b2","t":"call"}]},
{"id":"b3","t":"cmd","c":"maju"},
{"id":"b4","t":"cmd","c":"kiri"},
{"id":"b5","t":"cmd","c":"maju"},
{"id":"b6","t":"cmd","c":"maju"}],"jurus":[{"id":"b7","t":"cmd","c":"maju"},
{"id":"b8","t":"cmd","c":"kiri"},
{"id":"b9","t":"cmd","c":"maju"},
{"id":"b10","t":"cmd","c":"kanan"}]}},
{"id":"j79","theme":"laut","dir":3,"blocks":["maju","kiri","kanan"],"map":["#..#.",".~#.S",".#...","~..~~","..###",".#.##","G.#.."],"hint":"Jurus juga bisa dipanggil di dalam ulangi!","palette":["maju","kiri","kanan","ulangi","jurus"],"best":10,"limit":11,"tip":"Jurus = [maju, belok kiri, maju, belok kanan]. Program: ulangi 3 kali [jurus], maju, belok kiri, maju 2×","solution":{"main":[{"id":"b1","t":"loop","n":3,"body":[{"id":"b2","t":"call"}]},
{"id":"b3","t":"cmd","c":"maju"},
{"id":"b4","t":"cmd","c":"kiri"},
{"id":"b5","t":"cmd","c":"maju"},
{"id":"b6","t":"cmd","c":"maju"}],"jurus":[{"id":"b7","t":"cmd","c":"maju"},
{"id":"b8","t":"cmd","c":"kiri"},
{"id":"b9","t":"cmd","c":"maju"},
{"id":"b10","t":"cmd","c":"kanan"}]}},
{"id":"j80","theme":"laut","dir":1,"blocks":["maju","kiri","kanan"],"map":["S.~.#.","...~.#","~#..~.","..~..#","...#..","...#..","....#G"],"hint":"Jurus juga bisa dipanggil di dalam ulangi!","palette":["maju","kiri","kanan","ulangi","jurus"],"best":10,"limit":11,"tip":"Jurus = [maju, belok kanan, maju, belok kiri]. Program: ulangi 4 kali [jurus], maju, belok kanan, maju 2×","solution":{"main":[{"id":"b1","t":"loop","n":4,"body":[{"id":"b2","t":"call"}]},
{"id":"b3","t":"cmd","c":"maju"},
{"id":"b4","t":"cmd","c":"kanan"},
{"id":"b5","t":"cmd","c":"maju"},
{"id":"b6","t":"cmd","c":"maju"}],"jurus":[{"id":"b7","t":"cmd","c":"maju"},
{"id":"b8","t":"cmd","c":"kanan"},
{"id":"b9","t":"cmd","c":"maju"},
{"id":"b10","t":"cmd","c":"kiri"}]}},
{"id":"j81","theme":"gunung","dir":0,"blocks":["maju","kiri","kanan"],"map":["G~...",".....",".....","#..~.",".#..~",".....","#...S"],"hint":"Gabungkan jurus dan ulangi supaya programnya pendek.","palette":["maju","kiri","kanan","ulangi","jurus"],"best":10,"limit":11,"tip":"Jurus = [maju, belok kiri, maju 2×, belok kanan, maju]. Program: jurus, ulangi 2 kali [maju], jurus","solution":{"main":[{"id":"b1","t":"call"},
{"id":"b2","t":"loop","n":2,"body":[{"id":"b3","t":"cmd","c":"maju"}]},
{"id":"b4","t":"call"}],"jurus":[{"id":"b5","t":"cmd","c":"maju"},
{"id":"b6","t":"cmd","c":"kiri"},
{"id":"b7","t":"cmd","c":"maju"},
{"id":"b8","t":"cmd","c":"maju"},
{"id":"b9","t":"cmd","c":"kanan"},
{"id":"b10","t":"cmd","c":"maju"}]}},
{"id":"j82","theme":"gunung","dir":1,"blocks":["maju","kiri","kanan"],"map":["#.~#.~.G","....~..~","........","..#.#..~","S.#...#."],"hint":"Gabungkan jurus dan ulangi supaya programnya pendek.","palette":["maju","kiri","kanan","ulangi","jurus"],"best":10,"limit":11,"tip":"Jurus = [maju, belok kiri, maju 2×, belok kanan, maju]. Program: jurus, ulangi 3 kali [maju], jurus","solution":{"main":[{"id":"b1","t":"call"},
{"id":"b2","t":"loop","n":3,"body":[{"id":"b3","t":"cmd","c":"maju"}]},
{"id":"b4","t":"call"}],"jurus":[{"id":"b5","t":"cmd","c":"maju"},
{"id":"b6","t":"cmd","c":"kiri"},
{"id":"b7","t":"cmd","c":"maju"},
{"id":"b8","t":"cmd","c":"maju"},
{"id":"b9","t":"cmd","c":"kanan"},
{"id":"b10","t":"cmd","c":"maju"}]}},
{"id":"j83","theme":"gunung","dir":0,"blocks":["maju","kiri","kanan"],"map":["G.#..","....~","~#...","....#",".....",".~...","...#S"],"hint":"Gabungkan jurus dan ulangi supaya programnya pendek.","palette":["maju","kiri","kanan","ulangi","jurus"],"best":10,"limit":11,"tip":"Jurus = [maju, belok kiri, maju 2×, belok kanan, maju]. Program: jurus, ulangi 2 kali [maju], jurus","solution":{"main":[{"id":"b1","t":"call"},
{"id":"b2","t":"loop","n":2,"body":[{"id":"b3","t":"cmd","c":"maju"}]},
{"id":"b4","t":"call"}],"jurus":[{"id":"b5","t":"cmd","c":"maju"},
{"id":"b6","t":"cmd","c":"kiri"},
{"id":"b7","t":"cmd","c":"maju"},
{"id":"b8","t":"cmd","c":"maju"},
{"id":"b9","t":"cmd","c":"kanan"},
{"id":"b10","t":"cmd","c":"maju"}]}},
{"id":"j84","theme":"gunung","dir":1,"blocks":["maju","kiri","kanan"],"map":["S...~...","~.......","~.......",".......#","..~..#.G"],"hint":"Gabungkan jurus dan ulangi supaya programnya pendek.","palette":["maju","kiri","kanan","ulangi","jurus"],"best":10,"limit":11,"tip":"Jurus = [maju, belok kanan, maju 2×, belok kiri, maju]. Program: jurus, ulangi 3 kali [maju], jurus","solution":{"main":[{"id":"b1","t":"call"},
{"id":"b2","t":"loop","n":3,"body":[{"id":"b3","t":"cmd","c":"maju"}]},
{"id":"b4","t":"call"}],"jurus":[{"id":"b5","t":"cmd","c":"maju"},
{"id":"b6","t":"cmd","c":"kanan"},
{"id":"b7","t":"cmd","c":"maju"},
{"id":"b8","t":"cmd","c":"maju"},
{"id":"b9","t":"cmd","c":"kiri"},
{"id":"b10","t":"cmd","c":"maju"}]}},
{"id":"j85","theme":"gunung","dir":3,"blocks":["maju","kiri","kanan"],"map":["..#.....","G.#.....","~.#~~...","........",".~..~~..","~..~...S"],"hint":"Gabungkan jurus dan ulangi supaya programnya pendek.","palette":["maju","kiri","kanan","ulangi","jurus"],"best":10,"limit":11,"tip":"Jurus = [maju, belok kanan, maju 2×, belok kiri, maju]. Program: jurus, ulangi 3 kali [maju], jurus","solution":{"main":[{"id":"b1","t":"call"},
{"id":"b2","t":"loop","n":3,"body":[{"id":"b3","t":"cmd","c":"maju"}]},
{"id":"b4","t":"call"}],"jurus":[{"id":"b5","t":"cmd","c":"maju"},
{"id":"b6","t":"cmd","c":"kanan"},
{"id":"b7","t":"cmd","c":"maju"},
{"id":"b8","t":"cmd","c":"maju"},
{"id":"b9","t":"cmd","c":"kiri"},
{"id":"b10","t":"cmd","c":"maju"}]}},
{"id":"j86","theme":"gunung","dir":3,"blocks":["maju","kiri","kanan"],"map":["..~#.~..S",".#..#....","...~.....","#..~~.~..",".......~~","#.~...~.~","G.~~....."],"hint":"Gabungkan jurus dan ulangi supaya programnya pendek.","palette":["maju","kiri","kanan","ulangi","jurus"],"best":11,"limit":12,"tip":"Jurus = [maju, belok kiri, maju 2×, belok kanan, maju]. Program: jurus, jurus, ulangi 2 kali [maju], jurus","solution":{"main":[{"id":"b1","t":"call"},
{"id":"b2","t":"call"},
{"id":"b3","t":"loop","n":2,"body":[{"id":"b4","t":"cmd","c":"maju"}]},
{"id":"b5","t":"call"}],"jurus":[{"id":"b6","t":"cmd","c":"maju"},
{"id":"b7","t":"cmd","c":"kiri"},
{"id":"b8","t":"cmd","c":"maju"},
{"id":"b9","t":"cmd","c":"maju"},
{"id":"b10","t":"cmd","c":"kanan"},
{"id":"b11","t":"cmd","c":"maju"}]}},
{"id":"j87","theme":"gunung","dir":3,"blocks":["maju","kiri","kanan"],"map":["..##.~..S","....~.~..",".#..#....",".##......",".......#.","~..#.....","G.~.~.#.."],"hint":"Gabungkan jurus dan ulangi supaya programnya pendek.","palette":["maju","kiri","kanan","ulangi","jurus"],"best":11,"limit":12,"tip":"Jurus = [maju, belok kiri, maju 2×, belok kanan, maju]. Program: jurus, jurus, ulangi 2 kali [maju], jurus","solution":{"main":[{"id":"b1","t":"call"},
{"id":"b2","t":"call"},
{"id":"b3","t":"loop","n":2,"body":[{"id":"b4","t":"cmd","c":"maju"}]},
{"id":"b5","t":"call"}],"jurus":[{"id":"b6","t":"cmd","c":"maju"},
{"id":"b7","t":"cmd","c":"kiri"},
{"id":"b8","t":"cmd","c":"maju"},
{"id":"b9","t":"cmd","c":"maju"},
{"id":"b10","t":"cmd","c":"kanan"},
{"id":"b11","t":"cmd","c":"maju"}]}},
{"id":"j88","theme":"gunung","dir":1,"blocks":["maju","kiri","kanan"],"map":["#.#.....G","~.~~~...~","..#......","..#.~...~",".....~~..","#...~.#.~","S.~##..#."],"hint":"Gabungkan jurus dan ulangi supaya programnya pendek.","palette":["maju","kiri","kanan","ulangi","jurus"],"best":11,"limit":12,"tip":"Jurus = [maju, belok kiri, maju 2×, belok kanan, maju]. Program: jurus, jurus, ulangi 2 kali [maju], jurus","solution":{"main":[{"id":"b1","t":"call"},
{"id":"b2","t":"call"},
{"id":"b3","t":"loop","n":2,"body":[{"id":"b4","t":"cmd","c":"maju"}]},
{"id":"b5","t":"call"}],"jurus":[{"id":"b6","t":"cmd","c":"maju"},
{"id":"b7","t":"cmd","c":"kiri"},
{"id":"b8","t":"cmd","c":"maju"},
{"id":"b9","t":"cmd","c":"maju"},
{"id":"b10","t":"cmd","c":"kanan"},
{"id":"b11","t":"cmd","c":"maju"}]}},
{"id":"j89","theme":"gunung","dir":1,"blocks":["maju","kiri","kanan"],"map":["S....~...","#.##..#..","~...##.#.",".....~...",".~......~","..###....","#.#.##..G"],"hint":"Gabungkan jurus dan ulangi supaya programnya pendek.","palette":["maju","kiri","kanan","ulangi","jurus"],"best":11,"limit":12,"tip":"Jurus = [maju, belok kanan, maju 2×, belok kiri, maju]. Program: jurus, jurus, ulangi 2 kali [maju], jurus","solution":{"main":[{"id":"b1","t":"call"},
{"id":"b2","t":"call"},
{"id":"b3","t":"loop","n":2,"body":[{"id":"b4","t":"cmd","c":"maju"}]},
{"id":"b5","t":"call"}],"jurus":[{"id":"b6","t":"cmd","c":"maju"},
{"id":"b7","t":"cmd","c":"kanan"},
{"id":"b8","t":"cmd","c":"maju"},
{"id":"b9","t":"cmd","c":"maju"},
{"id":"b10","t":"cmd","c":"kiri"},
{"id":"b11","t":"cmd","c":"maju"}]}},
{"id":"j90","theme":"gunung","dir":1,"blocks":["maju","kiri","kanan"],"map":["S.~......","..#.....#","~...#..~.",".#.......","#.#.....~","....~....","~....~..G"],"hint":"Gabungkan jurus dan ulangi supaya programnya pendek.","palette":["maju","kiri","kanan","ulangi","jurus"],"best":11,"limit":12,"tip":"Jurus = [maju, belok kanan, maju 2×, belok kiri, maju]. Program: jurus, jurus, ulangi 2 kali [maju], jurus","solution":{"main":[{"id":"b1","t":"call"},
{"id":"b2","t":"call"},
{"id":"b3","t":"loop","n":2,"body":[{"id":"b4","t":"cmd","c":"maju"}]},
{"id":"b5","t":"call"}],"jurus":[{"id":"b6","t":"cmd","c":"maju"},
{"id":"b7","t":"cmd","c":"kanan"},
{"id":"b8","t":"cmd","c":"maju"},
{"id":"b9","t":"cmd","c":"maju"},
{"id":"b10","t":"cmd","c":"kiri"},
{"id":"b11","t":"cmd","c":"maju"}]}},
{"id":"j91","theme":"bulan","dir":3,"blocks":["maju","kiri","kanan"],"map":["##..###.","G~.#....","...#.#.#","..#.#~.S","#..#....",".#...~.#"],"hint":"Soal terakhir Jurus! Pakai jurus dan ulangi sehemat mungkin.","palette":["maju","kiri","kanan","ulangi","jurus"],"best":12,"limit":13,"tip":"Jurus = [maju, belok kiri, maju, belok kanan, maju]. Program: ulangi 2 kali [jurus], ulangi 1 kali [maju], belok kanan, ulangi 2 kali [jurus]","solution":{"main":[{"id":"b1","t":"loop","n":2,"body":[{"id":"b2","t":"call"}]},
{"id":"b3","t":"loop","n":1,"body":[{"id":"b4","t":"cmd","c":"maju"}]},
{"id":"b5","t":"cmd","c":"kanan"},
{"id":"b6","t":"loop","n":2,"body":[{"id":"b7","t":"call"}]}],"jurus":[{"id":"b8","t":"cmd","c":"maju"},
{"id":"b9","t":"cmd","c":"kiri"},
{"id":"b10","t":"cmd","c":"maju"},
{"id":"b11","t":"cmd","c":"kanan"},
{"id":"b12","t":"cmd","c":"maju"}]}},
{"id":"j92","theme":"bulan","dir":1,"blocks":["maju","kiri","kanan"],"map":[".#.....##","#...##..#","S.#.#.#..","~~##..#..","#...#..#G"],"hint":"Soal terakhir Jurus! Pakai jurus dan ulangi sehemat mungkin.","palette":["maju","kiri","kanan","ulangi","jurus"],"best":12,"limit":13,"tip":"Jurus = [maju, belok kiri, maju, belok kanan, maju]. Program: ulangi 2 kali [jurus], ulangi 2 kali [maju], belok kanan, ulangi 2 kali [jurus]","solution":{"main":[{"id":"b1","t":"loop","n":2,"body":[{"id":"b2","t":"call"}]},
{"id":"b3","t":"loop","n":2,"body":[{"id":"b4","t":"cmd","c":"maju"}]},
{"id":"b5","t":"cmd","c":"kanan"},
{"id":"b6","t":"loop","n":2,"body":[{"id":"b7","t":"call"}]}],"jurus":[{"id":"b8","t":"cmd","c":"maju"},
{"id":"b9","t":"cmd","c":"kiri"},
{"id":"b10","t":"cmd","c":"maju"},
{"id":"b11","t":"cmd","c":"kanan"},
{"id":"b12","t":"cmd","c":"maju"}]}},
{"id":"j93","theme":"bulan","dir":3,"blocks":["maju","kiri","kanan"],"map":[".G##...~.","...~..#..","##...##.S","....~....","..#...#..",".#.##..~."],"hint":"Soal terakhir Jurus! Pakai jurus dan ulangi sehemat mungkin.","palette":["maju","kiri","kanan","ulangi","jurus"],"best":12,"limit":13,"tip":"Jurus = [maju, belok kiri, maju, belok kanan, maju]. Program: ulangi 2 kali [jurus], ulangi 1 kali [maju], belok kanan, ulangi 2 kali [jurus]","solution":{"main":[{"id":"b1","t":"loop","n":2,"body":[{"id":"b2","t":"call"}]},
{"id":"b3","t":"loop","n":1,"body":[{"id":"b4","t":"cmd","c":"maju"}]},
{"id":"b5","t":"cmd","c":"kanan"},
{"id":"b6","t":"loop","n":2,"body":[{"id":"b7","t":"call"}]}],"jurus":[{"id":"b8","t":"cmd","c":"maju"},
{"id":"b9","t":"cmd","c":"kiri"},
{"id":"b10","t":"cmd","c":"maju"},
{"id":"b11","t":"cmd","c":"kanan"},
{"id":"b12","t":"cmd","c":"maju"}]}},
{"id":"j94","theme":"bulan","dir":1,"blocks":["maju","kiri","kanan"],"map":["......#~G","#..#..#..","S.~.#.#..","....~#..#","#.#....#."],"hint":"Soal terakhir Jurus! Pakai jurus dan ulangi sehemat mungkin.","palette":["maju","kiri","kanan","ulangi","jurus"],"best":12,"limit":13,"tip":"Jurus = [maju, belok kanan, maju, belok kiri, maju]. Program: ulangi 2 kali [jurus], ulangi 2 kali [maju], belok kiri, ulangi 2 kali [jurus]","solution":{"main":[{"id":"b1","t":"loop","n":2,"body":[{"id":"b2","t":"call"}]},
{"id":"b3","t":"loop","n":2,"body":[{"id":"b4","t":"cmd","c":"maju"}]},
{"id":"b5","t":"cmd","c":"kiri"},
{"id":"b6","t":"loop","n":2,"body":[{"id":"b7","t":"call"}]}],"jurus":[{"id":"b8","t":"cmd","c":"maju"},
{"id":"b9","t":"cmd","c":"kanan"},
{"id":"b10","t":"cmd","c":"maju"},
{"id":"b11","t":"cmd","c":"kiri"},
{"id":"b12","t":"cmd","c":"maju"}]}},
{"id":"j95","theme":"bulan","dir":1,"blocks":["maju","kiri","kanan"],"map":["#.##....#","~~#....~#","....#~..#","S.#~##..~","...#.##..",".#...~#~G"],"hint":"Soal terakhir Jurus! Pakai jurus dan ulangi sehemat mungkin.","palette":["maju","kiri","kanan","ulangi","jurus"],"best":12,"limit":13,"tip":"Jurus = [maju, belok kiri, maju, belok kanan, maju]. Program: ulangi 2 kali [jurus], ulangi 2 kali [maju], belok kanan, ulangi 2 kali [jurus]","solution":{"main":[{"id":"b1","t":"loop","n":2,"body":[{"id":"b2","t":"call"}]},
{"id":"b3","t":"loop","n":2,"body":[{"id":"b4","t":"cmd","c":"maju"}]},
{"id":"b5","t":"cmd","c":"kanan"},
{"id":"b6","t":"loop","n":2,"body":[{"id":"b7","t":"call"}]}],"jurus":[{"id":"b8","t":"cmd","c":"maju"},
{"id":"b9","t":"cmd","c":"kiri"},
{"id":"b10","t":"cmd","c":"maju"},
{"id":"b11","t":"cmd","c":"kanan"},
{"id":"b12","t":"cmd","c":"maju"}]}},
{"id":"j96","theme":"bulan","dir":3,"blocks":["maju","kiri","kanan"],"map":[".......~.","#~....~~#","...##....","~....#~.S","..#...#..","G~.....##"],"hint":"Soal terakhir Jurus! Pakai jurus dan ulangi sehemat mungkin.","palette":["maju","kiri","kanan","ulangi","jurus"],"best":12,"limit":13,"tip":"Jurus = [maju, belok kanan, maju, belok kiri, maju]. Program: ulangi 2 kali [jurus], ulangi 2 kali [maju], belok kiri, ulangi 2 kali [jurus]","solution":{"main":[{"id":"b1","t":"loop","n":2,"body":[{"id":"b2","t":"call"}]},
{"id":"b3","t":"loop","n":2,"body":[{"id":"b4","t":"cmd","c":"maju"}]},
{"id":"b5","t":"cmd","c":"kiri"},
{"id":"b6","t":"loop","n":2,"body":[{"id":"b7","t":"call"}]}],"jurus":[{"id":"b8","t":"cmd","c":"maju"},
{"id":"b9","t":"cmd","c":"kanan"},
{"id":"b10","t":"cmd","c":"maju"},
{"id":"b11","t":"cmd","c":"kiri"},
{"id":"b12","t":"cmd","c":"maju"}]}},
{"id":"j97","theme":"bulan","dir":3,"blocks":["maju","kiri","kanan"],"map":["~.#....~.","....~....",".#.#.##.S","...~#..#.","~G#~....."],"hint":"Soal terakhir Jurus! Pakai jurus dan ulangi sehemat mungkin.","palette":["maju","kiri","kanan","ulangi","jurus"],"best":12,"limit":13,"tip":"Jurus = [maju, belok kanan, maju, belok kiri, maju]. Program: ulangi 2 kali [jurus], ulangi 1 kali [maju], belok kiri, ulangi 2 kali [jurus]","solution":{"main":[{"id":"b1","t":"loop","n":2,"body":[{"id":"b2","t":"call"}]},
{"id":"b3","t":"loop","n":1,"body":[{"id":"b4","t":"cmd","c":"maju"}]},
{"id":"b5","t":"cmd","c":"kiri"},
{"id":"b6","t":"loop","n":2,"body":[{"id":"b7","t":"call"}]}],"jurus":[{"id":"b8","t":"cmd","c":"maju"},
{"id":"b9","t":"cmd","c":"kanan"},
{"id":"b10","t":"cmd","c":"maju"},
{"id":"b11","t":"cmd","c":"kiri"},
{"id":"b12","t":"cmd","c":"maju"}]}},
{"id":"j98","theme":"bulan","dir":3,"blocks":["maju","kiri","kanan"],"map":["G~~.#...#","..#......","~..#.~#.S","#..##....",".#....#.."],"hint":"Soal terakhir Jurus! Pakai jurus dan ulangi sehemat mungkin.","palette":["maju","kiri","kanan","ulangi","jurus"],"best":12,"limit":13,"tip":"Jurus = [maju, belok kiri, maju, belok kanan, maju]. Program: ulangi 2 kali [jurus], ulangi 2 kali [maju], belok kanan, ulangi 2 kali [jurus]","solution":{"main":[{"id":"b1","t":"loop","n":2,"body":[{"id":"b2","t":"call"}]},
{"id":"b3","t":"loop","n":2,"body":[{"id":"b4","t":"cmd","c":"maju"}]},
{"id":"b5","t":"cmd","c":"kanan"},
{"id":"b6","t":"loop","n":2,"body":[{"id":"b7","t":"call"}]}],"jurus":[{"id":"b8","t":"cmd","c":"maju"},
{"id":"b9","t":"cmd","c":"kiri"},
{"id":"b10","t":"cmd","c":"maju"},
{"id":"b11","t":"cmd","c":"kanan"},
{"id":"b12","t":"cmd","c":"maju"}]}},
{"id":"j99","theme":"bulan","dir":1,"blocks":["maju","kiri","kanan"],"map":["~..#.....",".#.....~.","....##...","S.~.#.#.~","#..~..~..",".#.#...#G"],"hint":"Soal terakhir Jurus! Pakai jurus dan ulangi sehemat mungkin.","palette":["maju","kiri","kanan","ulangi","jurus"],"best":12,"limit":13,"tip":"Jurus = [maju, belok kiri, maju, belok kanan, maju]. Program: ulangi 2 kali [jurus], ulangi 2 kali [maju], belok kanan, ulangi 2 kali [jurus]","solution":{"main":[{"id":"b1","t":"loop","n":2,"body":[{"id":"b2","t":"call"}]},
{"id":"b3","t":"loop","n":2,"body":[{"id":"b4","t":"cmd","c":"maju"}]},
{"id":"b5","t":"cmd","c":"kanan"},
{"id":"b6","t":"loop","n":2,"body":[{"id":"b7","t":"call"}]}],"jurus":[{"id":"b8","t":"cmd","c":"maju"},
{"id":"b9","t":"cmd","c":"kiri"},
{"id":"b10","t":"cmd","c":"maju"},
{"id":"b11","t":"cmd","c":"kanan"},
{"id":"b12","t":"cmd","c":"maju"}]}},
{"id":"j100","theme":"bulan","dir":3,"blocks":["maju","kiri","kanan"],"map":["G##.#....","...~...#~","#.#.~.#.S","#..#.....",".#.....#.","~.~#..#.."],"hint":"Soal terakhir Jurus! Pakai jurus dan ulangi sehemat mungkin.","palette":["maju","kiri","kanan","ulangi","jurus"],"best":12,"limit":13,"tip":"Jurus = [maju, belok kiri, maju, belok kanan, maju]. Program: ulangi 2 kali [jurus], ulangi 2 kali [maju], belok kanan, ulangi 2 kali [jurus]","solution":{"main":[{"id":"b1","t":"loop","n":2,"body":[{"id":"b2","t":"call"}]},
{"id":"b3","t":"loop","n":2,"body":[{"id":"b4","t":"cmd","c":"maju"}]},
{"id":"b5","t":"cmd","c":"kanan"},
{"id":"b6","t":"loop","n":2,"body":[{"id":"b7","t":"call"}]}],"jurus":[{"id":"b8","t":"cmd","c":"maju"},
{"id":"b9","t":"cmd","c":"kiri"},
{"id":"b10","t":"cmd","c":"maju"},
{"id":"b11","t":"cmd","c":"kanan"},
{"id":"b12","t":"cmd","c":"maju"}]}}];
