// Level game "Langkah" (konsep: urutan perintah) — 100 level untuk usia 3–8 tahun, makin tinggi makin sulit.
// DIBUAT OTOMATIS oleh scripts/gen-langkah.ts (lihat src/lib/koding/gen-langkah.ts); jangan diedit manual.
// Kebun 1–20 · Pantai 21–40 · Salju 41–60 · Gurun 61–80 · Luar Angkasa 81–100.
// Peta: . kosong · # rintangan · ~ air/es · S mulai · G bintang. dir: 0 atas, 1 kanan, 2 bawah, 3 kiri.

import type { Level } from './engine';

export const LANGKAH: Level[] = [
  { id: 'k1', theme: 'kebun', dir: 1, blocks: ['maju'], map: ['S.G..', '.....', '.....'], hint: 'Ketuk blok Maju, lalu tekan Jalankan. Agam akan berjalan!' },
  { id: 'k2', theme: 'kebun', dir: 1, blocks: ['maju'], map: ['.S..G.', '......', '......'], hint: 'Berapa kotak sampai ke bintang? Sebanyak itu blok Maju.' },
  { id: 'k3', theme: 'kebun', dir: 0, blocks: ['maju'], map: ['....', 'G...', '....', '....', 'S...', '....'], hint: 'Agam menghadap ke atas. Maju berarti jalan ke atas.' },
  { id: 'k4', theme: 'kebun', dir: 1, blocks: ['maju'], map: ['......', 'S...G.', '......'], hint: 'Hitung kotaknya, lalu ketuk Maju sebanyak itu.' },
  { id: 'k5', theme: 'kebun', dir: 0, blocks: ['maju'], map: ['..G.', '....', '....', '....', '..S.', '....'], hint: 'Hitung kotaknya, lalu ketuk Maju sebanyak itu.' },
  { id: 'k6', theme: 'kebun', dir: 3, blocks: ['maju'], map: ['#.....', 'G...S.', '......'], hint: 'Agam menghadap ke kiri. Maju berarti jalan ke kiri.' },
  { id: 'k7', theme: 'kebun', dir: 2, blocks: ['maju'], map: ['.S..', '..~.', '...#', '..#.', '....', '.G..', '....'], hint: 'Sekarang Agam menghadap ke bawah.' },
  { id: 'k8', theme: 'kebun', dir: 1, blocks: ['maju'], map: ['.S....G', '..#....', '......#'], hint: 'Hitung kotaknya, lalu ketuk Maju sebanyak itu.' },
  { id: 'k9', theme: 'kebun', dir: 0, blocks: ['maju'], map: ['...G', '....', '....', '....', '.#..', '....', '#..S'], hint: 'Hitung kotaknya, lalu ketuk Maju sebanyak itu.' },
  { id: 'k10', theme: 'kebun', dir: 3, blocks: ['maju'], map: ['.#......', 'G.....S.', '~#......'], hint: 'Hitung kotaknya, lalu ketuk Maju sebanyak itu.' },
  { id: 'k11', theme: 'pantai', dir: 1, blocks: ['maju', 'kanan'], map: ['..#.', 'S...', '..G.', '....'], hint: 'Selamat datang di Pantai! Blok baru: belok kanan. Agam berputar di tempat, belum berjalan.' },
  { id: 'k12', theme: 'pantai', dir: 2, blocks: ['maju', 'kanan'], map: ['..S.', '....', 'G..~'], hint: 'Maju dulu, belok kanan, lalu maju lagi.' },
  { id: 'k13', theme: 'pantai', dir: 3, blocks: ['maju', 'kanan'], map: ['....', 'G.~.', '....', '....', '.S..'], hint: 'Maju dulu, belok kanan, lalu maju lagi.' },
  { id: 'k14', theme: 'pantai', dir: 0, blocks: ['maju', 'kanan'], map: ['.....G', '......', '..S...'], hint: 'Maju dulu, belok kanan, lalu maju lagi.' },
  { id: 'k15', theme: 'pantai', dir: 1, blocks: ['maju', 'kanan'], map: ['......', '.S....', '......', '.....G', '......'], hint: 'Maju dulu, belok kanan, lalu maju lagi.' },
  { id: 'k16', theme: 'pantai', dir: 2, blocks: ['maju', 'kiri'], map: ['..S~..', '.....G', '.~.~..', '#..~..'], hint: 'Blok baru: belok kiri! Agam berputar ke arah tangan kirinya.' },
  { id: 'k17', theme: 'pantai', dir: 3, blocks: ['maju', 'kiri'], map: ['.~...', '...S~', '..~..', 'G....'], hint: 'Maju dulu, belok kiri, lalu maju lagi.' },
  { id: 'k18', theme: 'pantai', dir: 2, blocks: ['maju', 'kiri'], map: ['S...', '..~.', '....', '....', '..G.'], hint: 'Maju dulu, belok kiri, lalu maju lagi.' },
  { id: 'k19', theme: 'pantai', dir: 0, blocks: ['maju', 'kiri', 'kanan'], map: ['..G.~.', '##....', '...#.S', '~.~.#.'], hint: 'Sekarang ada belok kiri dan belok kanan. Pilih yang tepat, ya.' },
  { id: 'k20', theme: 'pantai', dir: 3, blocks: ['maju', 'kiri', 'kanan'], map: ['.#...', '~...S', '.....', 'G.~..'], hint: 'Kalau salah, tidak apa-apa. Programmer juga sering mencoba lagi.' },
  { id: 'k21', theme: 'hutan', dir: 1, blocks: ['maju', 'kiri', 'kanan'], map: ['#.#..G', 'S...~#', '.##.#.'], hint: 'Masuk Hutan! Pohon besar dan sungai kecil menghalangi jalan.' },
  { id: 'k22', theme: 'hutan', dir: 2, blocks: ['maju', 'kiri', 'kanan'], map: ['.~S#.', '~....', '#....', '.....', 'G##.#'], hint: 'Belok tidak membuat Agam berjalan. Setelah belok, jangan lupa Maju.' },
  { id: 'k23', theme: 'hutan', dir: 3, blocks: ['maju', 'kiri', 'kanan'], map: ['...S..', '...#.#', '#....G'], hint: 'Lihat dulu ke mana Agam menghadap sebelum menyusun blok.' },
  { id: 'k24', theme: 'hutan', dir: 3, blocks: ['maju', 'kiri', 'kanan'], map: ['.#..S.', '#....#', '~.....', 'G.....', '...#~.'], hint: 'Tunjuk kotaknya dengan jari sambil menghitung.' },
  { id: 'k25', theme: 'hutan', dir: 2, blocks: ['maju', 'kiri', 'kanan'], map: ['S.#.', '...#', '...~', '....', '~.#G'], hint: 'Bayangkan kamu adalah Agam. Ke mana tangan kananmu?' },
  { id: 'k26', theme: 'hutan', dir: 1, blocks: ['maju', 'kiri', 'kanan'], map: ['....', 'S...', '##~.', '.G..', '.##~'], hint: 'Susun sedikit dulu, jalankan, lalu tambah lagi.' },
  { id: 'k27', theme: 'hutan', dir: 3, blocks: ['maju', 'kiri', 'kanan'], map: ['.#..S#', '.~.#~.', '#..#..', 'G..###'], hint: 'Makin sedikit blok, makin banyak bintang.' },
  { id: 'k28', theme: 'hutan', dir: 1, blocks: ['maju', 'kiri', 'kanan'], map: ['..#~.', '#~S..', '..~#.', '#.~..', '.G...'], hint: 'Kalau salah, tidak apa-apa. Programmer juga sering mencoba lagi.' },
  { id: 'k29', theme: 'hutan', dir: 0, blocks: ['maju', 'kiri', 'kanan'], map: ['....#.', '......', 'G#....', '...#.S'], hint: 'Ikuti jalan yang kosong, hindari rintangan.' },
  { id: 'k30', theme: 'hutan', dir: 2, blocks: ['maju', 'kiri', 'kanan'], map: ['....S.', '##.~..', 'G###..', '.....#', '#..~..'], hint: 'Agam menghadap ke bawah. Kanan dan kiri Agam jadi terbalik, lho!' },
  { id: 'k31', theme: 'sawah', dir: 0, blocks: ['maju', 'kiri', 'kanan'], map: ['#.#~', '...~', '.~..', '.#.~', 'G~S#'], hint: 'Di Sawah, Agam hanya boleh lewat pematang. Jangan injak padi, ya!' },
  { id: 'k32', theme: 'sawah', dir: 0, blocks: ['maju', 'kiri', 'kanan'], map: ['.#..', '....', '..~.', '..~.', '~S~G'], hint: 'Tunjuk kotaknya dengan jari sambil menghitung.' },
  { id: 'k33', theme: 'sawah', dir: 3, blocks: ['maju', 'kiri', 'kanan'], map: ['...S', '..#~', '.~..', '..G.'], hint: 'Bayangkan kamu adalah Agam. Ke mana tangan kananmu?' },
  { id: 'k34', theme: 'sawah', dir: 3, blocks: ['maju', 'kiri', 'kanan'], map: ['..S.#.', '.~~~.#', '.....G', '~....~'], hint: 'Susun sedikit dulu, jalankan, lalu tambah lagi.' },
  { id: 'k35', theme: 'sawah', dir: 0, blocks: ['maju', 'kiri', 'kanan'], map: ['.....', '.#.#.', '.~...', 'S#...', '~.G..'], hint: 'Makin sedikit blok, makin banyak bintang.' },
  { id: 'k36', theme: 'sawah', dir: 2, blocks: ['maju', 'kiri', 'kanan'], map: ['~...##', 'G..#S.', '.~.#..', '~.....'], hint: 'Agam menghadap ke bawah. Kanan dan kiri Agam jadi terbalik, lho!' },
  { id: 'k37', theme: 'sawah', dir: 1, blocks: ['maju', 'kiri', 'kanan'], map: ['......', 'S.....', '#...~~', '......', '...#.G'], hint: 'Ikuti jalan yang kosong, hindari rintangan.' },
  { id: 'k38', theme: 'sawah', dir: 1, blocks: ['maju', 'kiri', 'kanan'], map: ['S...~.', '~.#...', '......', '....~.', '....~G'], hint: 'Belok tidak membuat Agam berjalan. Setelah belok, jangan lupa Maju.' },
  { id: 'k39', theme: 'sawah', dir: 3, blocks: ['maju', 'kiri', 'kanan'], map: ['......', '..~..~', '~.~..S', '.G.~..', '.~.#~.'], hint: 'Lihat dulu ke mana Agam menghadap sebelum menyusun blok.' },
  { id: 'k40', theme: 'sawah', dir: 1, blocks: ['maju', 'kiri', 'kanan'], map: ['G#..', '....', '.~#.', '##..', '.S..'], hint: 'Tunjuk kotaknya dengan jari sambil menghitung.' },
  { id: 'k41', theme: 'kota', dir: 3, blocks: ['maju', 'kiri', 'kanan'], map: ['.....S', '#..~#~', '......', '..#.#.', '.#.G..'], hint: 'Selamat datang di Kota! Hindari kerucut, mobil parkir, dan air mancur.' },
  { id: 'k42', theme: 'kota', dir: 2, blocks: ['maju', 'kiri', 'kanan'], map: ['##....#', '..##.#S', '###....', '.....##', '#G...##'], hint: 'Agam menghadap ke bawah. Kanan dan kiri Agam jadi terbalik, lho!' },
  { id: 'k43', theme: 'kota', dir: 2, blocks: ['maju', 'kiri', 'kanan'], map: ['.#S#.', '~~...', '.....', '.~#..', '..G#.'], hint: 'Makin sedikit blok, makin banyak bintang.' },
  { id: 'k44', theme: 'kota', dir: 0, blocks: ['maju', 'kiri', 'kanan'], map: ['##.....', '.~.~.~#', '~#S#...', '.##...G'], hint: 'Kalau salah, tidak apa-apa. Programmer juga sering mencoba lagi.' },
  { id: 'k45', theme: 'kota', dir: 3, blocks: ['maju', 'kiri', 'kanan'], map: ['.....##', '.#..#.G', '.......', '..##.#.', '..S.#..'], hint: 'Ikuti jalan yang kosong, hindari rintangan.' },
  { id: 'k46', theme: 'kota', dir: 2, blocks: ['maju', 'kiri', 'kanan'], map: ['##..G.', 'S#.###', '.#...#', '...~..', '..#.~.'], hint: 'Belok tidak membuat Agam berjalan. Setelah belok, jangan lupa Maju.' },
  { id: 'k47', theme: 'kota', dir: 0, blocks: ['maju', 'kiri', 'kanan'], map: ['#.#....', '~..~...', '#.##.#.', '#G...#S'], hint: 'Lihat dulu ke mana Agam menghadap sebelum menyusun blok.' },
  { id: 'k48', theme: 'kota', dir: 1, blocks: ['maju', 'kiri', 'kanan'], map: ['#.#.#.#', 'S....~#', '###.~G#', '....#..', '.......'], hint: 'Tunjuk kotaknya dengan jari sambil menghitung.' },
  { id: 'k49', theme: 'kota', dir: 1, blocks: ['maju', 'kiri', 'kanan'], map: ['...##.', '..#...', '......', '..##~.', '#G~S..'], hint: 'Bayangkan kamu adalah Agam. Ke mana tangan kananmu?' },
  { id: 'k50', theme: 'kota', dir: 0, blocks: ['maju', 'kiri', 'kanan'], map: ['#.....', 'G...~.', '.~.~..', '#~.~..', '##..#S'], hint: 'Susun sedikit dulu, jalankan, lalu tambah lagi.' },
  { id: 'k51', theme: 'salju', dir: 0, blocks: ['maju', 'kiri', 'kanan'], map: ['...#...', '.#.#...', '.~...G.', 'S#....~', '.~...~#'], hint: 'Brrr, dunia Salju! Kolam es tipis bisa retak, dan ada boneka salju.' },
  { id: 'k52', theme: 'salju', dir: 3, blocks: ['maju', 'kiri', 'kanan'], map: ['.~...G.', '.......', '.~~.#.#', '..#..#.', '.S.##~#'], hint: 'Kalau salah, tidak apa-apa. Programmer juga sering mencoba lagi.' },
  { id: 'k53', theme: 'salju', dir: 0, blocks: ['maju', 'kiri', 'kanan'], map: ['G..#...', '.#.....', '#~.....', '#......', '~....#S'], hint: 'Ikuti jalan yang kosong, hindari rintangan.' },
  { id: 'k54', theme: 'salju', dir: 2, blocks: ['maju', 'kiri', 'kanan'], map: ['.~S.~#', '.#....', '..#.#.', '...~..', '.G....'], hint: 'Agam menghadap ke bawah. Kanan dan kiri Agam jadi terbalik, lho!' },
  { id: 'k55', theme: 'salju', dir: 3, blocks: ['maju', 'kiri', 'kanan'], map: ['#~..#.', '....~.', '.#..#.', '..#...', 'G.#..S'], hint: 'Lihat dulu ke mana Agam menghadap sebelum menyusun blok.' },
  { id: 'k56', theme: 'salju', dir: 2, blocks: ['maju', 'kiri', 'kanan'], map: ['..#.~.S', '.....#.', '..~....', '.G.#...'], hint: 'Tunjuk kotaknya dengan jari sambil menghitung.' },
  { id: 'k57', theme: 'salju', dir: 3, blocks: ['maju', 'kiri', 'kanan'], map: ['G....~#', '~...~..', '.....#.', '.......', '...#..S'], hint: 'Bayangkan kamu adalah Agam. Ke mana tangan kananmu?' },
  { id: 'k58', theme: 'salju', dir: 0, blocks: ['maju', 'kiri', 'kanan'], map: ['......', '.....#', '.~..~.', '.#....', 'G#...S'], hint: 'Susun sedikit dulu, jalankan, lalu tambah lagi.' },
  { id: 'k59', theme: 'salju', dir: 2, blocks: ['maju', 'kiri', 'kanan'], map: ['S..#..~', '..#~.#.', '....##.', '..~..~G', '~......'], hint: 'Makin sedikit blok, makin banyak bintang.' },
  { id: 'k60', theme: 'salju', dir: 2, blocks: ['maju', 'kiri', 'kanan'], map: ['#.#~~#~', '~~...#G', 'S##~~..', '.#.....', '......#'], hint: 'Agam menghadap ke bawah. Kanan dan kiri Agam jadi terbalik, lho!' },
  { id: 'k61', theme: 'gurun', dir: 2, blocks: ['maju', 'kiri', 'kanan'], map: ['.#...', 'G~..#', '..#..', '...~S', '...#.', '.~...'], hint: 'Gurun yang panas! Hati-hati kaktus berduri, dan jangan tercebur di oasis.' },
  { id: 'k62', theme: 'gurun', dir: 3, blocks: ['maju', 'kiri', 'kanan'], map: ['#G..~##', '#~.#.~#', '#....#~', '.#.#...', '..~#...', '#.....S'], hint: 'Belok tidak membuat Agam berjalan. Setelah belok, jangan lupa Maju.' },
  { id: 'k63', theme: 'gurun', dir: 2, blocks: ['maju', 'kiri', 'kanan'], map: ['S....#', '.##.~.', '......', '.#.#.#', '#.##..', '....#G'], hint: 'Agam menghadap ke bawah. Kanan dan kiri Agam jadi terbalik, lho!' },
  { id: 'k64', theme: 'gurun', dir: 0, blocks: ['maju', 'kiri', 'kanan'], map: ['......#', 'S..##..', '..#..#.', '...#...', '#.#.~.G'], hint: 'Tunjuk kotaknya dengan jari sambil menghitung.' },
  { id: 'k65', theme: 'gurun', dir: 2, blocks: ['maju', 'kiri', 'kanan'], map: ['.#S#', 'G#..', '..#.', '..~.', '....', '#..#'], hint: 'Bayangkan kamu adalah Agam. Ke mana tangan kananmu?' },
  { id: 'k66', theme: 'gurun', dir: 1, blocks: ['maju', 'kiri', 'kanan'], map: ['S..#.', '.#.~.', '.....', '...#.', '####.', '..G..'], hint: 'Susun sedikit dulu, jalankan, lalu tambah lagi.' },
  { id: 'k67', theme: 'gurun', dir: 1, blocks: ['maju', 'kiri', 'kanan'], map: ['..G...', '....#.', '.~.#..', '#.#...', '#S..#.'], hint: 'Makin sedikit blok, makin banyak bintang.' },
  { id: 'k68', theme: 'gurun', dir: 1, blocks: ['maju', 'kiri', 'kanan'], map: ['....#.#', '#.#..#.', 'S.#....', '~#.....', '.##.##.', '~....G.'], hint: 'Kalau salah, tidak apa-apa. Programmer juga sering mencoba lagi.' },
  { id: 'k69', theme: 'gurun', dir: 2, blocks: ['maju', 'kiri', 'kanan'], map: ['.~...S.', '.~~.#..', '.G.#..#', '#.#.#..', '..#...#', '....#..'], hint: 'Agam menghadap ke bawah. Kanan dan kiri Agam jadi terbalik, lho!' },
  { id: 'k70', theme: 'gurun', dir: 0, blocks: ['maju', 'kiri', 'kanan'], map: ['#....#.', '..#.#.~', '.S#....', '....#..', '#~..#..', '#..#..G'], hint: 'Belok tidak membuat Agam berjalan. Setelah belok, jangan lupa Maju.' },
  { id: 'k71', theme: 'laut', dir: 1, blocks: ['maju', 'kiri', 'kanan'], map: ['...~#..', '...~#..', '.#.....', '#G..#..', '.#.~.#.', '..#S...'], hint: 'Menyelam ke Bawah Laut! Jauhi karang dan ubur-ubur.' },
  { id: 'k72', theme: 'laut', dir: 2, blocks: ['maju', 'kiri', 'kanan'], map: ['.#.~.~S', '.~.....', '~...~..', '.~..#..', 'G#...~#', '...~~..'], hint: 'Agam menghadap ke bawah. Kanan dan kiri Agam jadi terbalik, lho!' },
  { id: 'k73', theme: 'laut', dir: 2, blocks: ['maju', 'kiri', 'kanan'], map: ['S#....', '.~.~#.', '....~.', '...#.G', '...~..', '#..#..'], hint: 'Bayangkan kamu adalah Agam. Ke mana tangan kananmu?' },
  { id: 'k74', theme: 'laut', dir: 2, blocks: ['maju', 'kiri', 'kanan'], map: ['#......', '.#.....', 'S~..#..', '.~..#.G', '....~..', '..~..#~'], hint: 'Susun sedikit dulu, jalankan, lalu tambah lagi.' },
  { id: 'k75', theme: 'laut', dir: 1, blocks: ['maju', 'kiri', 'kanan'], map: ['...#...', '.....#.', '.#.....', 'S...~#.', '..~#.~.', '.~.G...'], hint: 'Makin sedikit blok, makin banyak bintang.' },
  { id: 'k76', theme: 'laut', dir: 2, blocks: ['maju', 'kiri', 'kanan'], map: ['S...#.', '...#.G', '...~..', '...~..', '~....~'], hint: 'Kalau salah, tidak apa-apa. Programmer juga sering mencoba lagi.' },
  { id: 'k77', theme: 'laut', dir: 0, blocks: ['maju', 'kiri', 'kanan'], map: ['#.....~', '#.~.~..', '....#.~', '##.##S#', 'G..~...'], hint: 'Ikuti jalan yang kosong, hindari rintangan.' },
  { id: 'k78', theme: 'laut', dir: 0, blocks: ['maju', 'kiri', 'kanan'], map: ['....#.', 'S~#..~', '.#....', '.#.#..', '.~~.#.', '..#G..'], hint: 'Belok tidak membuat Agam berjalan. Setelah belok, jangan lupa Maju.' },
  { id: 'k79', theme: 'laut', dir: 2, blocks: ['maju', 'kiri', 'kanan'], map: ['...~..G', '...#.#~', '##....~', 'S#..#.~', '.#..#..', '....#..'], hint: 'Lihat dulu ke mana Agam menghadap sebelum menyusun blok.' },
  { id: 'k80', theme: 'laut', dir: 3, blocks: ['maju', 'kiri', 'kanan'], map: ['.....##', '.~.~~..', '.#.....', 'G#....#', '.~#~..S', '~~....#'], hint: 'Tunjuk kotaknya dengan jari sambil menghitung.' },
  { id: 'k81', theme: 'gunung', dir: 2, blocks: ['maju', 'kiri', 'kanan'], map: ['.S.#...', '#.#G...', '..~....', '.#.~..#', '......~', '.#.....'], hint: 'Gunung Berapi! Lava itu panas sekali. Cari jalan di batu yang aman.' },
  { id: 'k82', theme: 'gunung', dir: 2, blocks: ['maju', 'kiri', 'kanan'], map: ['.S.~..G.', '..#~..~.', '....~..~', '##..~...', '.~#.....', '.~....#.'], hint: 'Susun sedikit dulu, jalankan, lalu tambah lagi.' },
  { id: 'k83', theme: 'gunung', dir: 1, blocks: ['maju', 'kiri', 'kanan'], map: ['..S..', '.#~~.', '#G#..', '..~.~', '#.#..', '.....'], hint: 'Makin sedikit blok, makin banyak bintang.' },
  { id: 'k84', theme: 'gunung', dir: 1, blocks: ['maju', 'kiri', 'kanan'], map: ['.~#.G~~', '...#...', '.#.#...', '~S..#~.', '~~..~..', '#......'], hint: 'Kalau salah, tidak apa-apa. Programmer juga sering mencoba lagi.' },
  { id: 'k85', theme: 'gunung', dir: 1, blocks: ['maju', 'kiri', 'kanan'], map: ['......~', '~~.~...', '...#.~.', '...~..~', 'S..~~..', '..~..G.'], hint: 'Ikuti jalan yang kosong, hindari rintangan.' },
  { id: 'k86', theme: 'gunung', dir: 3, blocks: ['maju', 'kiri', 'kanan'], map: ['.....', '#.~.#', '..~.G', '.~#~~', '.....', '..S~.'], hint: 'Belok tidak membuat Agam berjalan. Setelah belok, jangan lupa Maju.' },
  { id: 'k87', theme: 'gunung', dir: 1, blocks: ['maju', 'kiri', 'kanan'], map: ['~..#..G', '#~.~...', '...~.~.', 'S.#..##', '#.~.##.', '.....##'], hint: 'Lihat dulu ke mana Agam menghadap sebelum menyusun blok.' },
  { id: 'k88', theme: 'gunung', dir: 3, blocks: ['maju', 'kiri', 'kanan'], map: ['..~~..S.', '.#....##', 'G.~.#.~.', '..#.#.#.', '~.~..#..', '~...#.~.'], hint: 'Tunjuk kotaknya dengan jari sambil menghitung.' },
  { id: 'k89', theme: 'gunung', dir: 1, blocks: ['maju', 'kiri', 'kanan'], map: ['.#~.~S..', '...~.~~.', '#....#..', '~..#....', '.#...#..', 'G..~..~#'], hint: 'Bayangkan kamu adalah Agam. Ke mana tangan kananmu?' },
  { id: 'k90', theme: 'gunung', dir: 1, blocks: ['maju', 'kiri', 'kanan'], map: ['..S..~', '.~....', '#.#...', '.~.~..', 'G...~.', '#.....'], hint: 'Susun sedikit dulu, jalankan, lalu tambah lagi.' },
  { id: 'k91', theme: 'bulan', dir: 3, blocks: ['maju', 'kiri', 'kanan'], map: ['.~...#..', '#....#~#', '..#....G', '...#...#', '##..##~.', '....S...'], hint: 'Mendarat di Bulan! Awas kawah dalam dan batu bulan.' },
  { id: 'k92', theme: 'bulan', dir: 1, blocks: ['maju', 'kiri', 'kanan'], map: ['...~G...', '...#...#', '....##..', '.S...##.', '~#......', '#....#..'], hint: 'Kalau salah, tidak apa-apa. Programmer juga sering mencoba lagi.' },
  { id: 'k93', theme: 'bulan', dir: 0, blocks: ['maju', 'kiri', 'kanan'], map: ['##......', '....##..', '.S#.#.~.', '..#~....', '~.##G..#'], hint: 'Ikuti jalan yang kosong, hindari rintangan.' },
  { id: 'k94', theme: 'bulan', dir: 1, blocks: ['maju', 'kiri', 'kanan'], map: ['.....#', '..~..~', '...~..', 'S.##~.', '.~G...', '.~#...'], hint: 'Belok tidak membuat Agam berjalan. Setelah belok, jangan lupa Maju.' },
  { id: 'k95', theme: 'bulan', dir: 3, blocks: ['maju', 'kiri', 'kanan'], map: ['..#...G.', '.....##.', '#...#~.#', '...#.~.~', '#..#...S', '........'], hint: 'Lihat dulu ke mana Agam menghadap sebelum menyusun blok.' },
  { id: 'k96', theme: 'bulan', dir: 3, blocks: ['maju', 'kiri', 'kanan'], map: ['#......', '~.~...~', '..~..##', '.#..#..', 'G#.#.~.', '.~..S~.'], hint: 'Tunjuk kotaknya dengan jari sambil menghitung.' },
  { id: 'k97', theme: 'bulan', dir: 1, blocks: ['maju', 'kiri', 'kanan'], map: ['....~', '~.~.#', '..#.~', '.##..', 'G.~#.', '##S..'], hint: 'Bayangkan kamu adalah Agam. Ke mana tangan kananmu?' },
  { id: 'k98', theme: 'bulan', dir: 1, blocks: ['maju', 'kiri', 'kanan'], map: ['.....~.G', '....#.#.', 'S..#.#..', '..~~....', '~..~.##~', '##......'], hint: 'Susun sedikit dulu, jalankan, lalu tambah lagi.' },
  { id: 'k99', theme: 'bulan', dir: 3, blocks: ['maju', 'kiri', 'kanan'], map: ['G#...#..', '.#.#.#~.', '...~..~.', '#.#.~...', '.#....#.', '#.~....S'], hint: 'Makin sedikit blok, makin banyak bintang.' },
  { id: 'k100', theme: 'bulan', dir: 0, blocks: ['maju', 'kiri', 'kanan'], map: ['.....#.~', '.#.#.#..', '#..#S...', '...##~#.', '..##..G~', '#.....##'], hint: 'Soal terakhir! Selesaikan, lalu ambil sertifikatmu.' },
];
