// Level game "Ulangi (konsep: perulangan)" — 100 soal (10 Level bertema × 10 coding) untuk usia 3–8 tahun.
// DIBUAT OTOMATIS oleh scripts/gen-prog.ts (lihat src/lib/koding/gen-prog.ts); jangan diedit manual.
// Peta: . kosong · # rintangan · ~ air/es · S mulai · G bintang. dir: 0 atas, 1 kanan, 2 bawah, 3 kiri.

import type { ProgLevel } from './prog';

export const ULANGI: ProgLevel[] = [{"id":"u1","theme":"kebun","dir":1,"blocks":["maju","kiri","kanan"],"map":["S..G.","....#","..#.."],"hint":"Blok baru: ULANGI! Masukkan \"maju\" ke dalamnya, lalu ketuk angkanya untuk memilih berapa kali.","palette":["maju","ulangi"],"best":2,"limit":2,"tip":"ulangi 3 kali [maju]","solution":{"main":[{"id":"b1","t":"loop","n":3,"body":[{"id":"b2","t":"cmd","c":"maju"}]}],"jurus":[]}},
{"id":"u2","theme":"kebun","dir":1,"blocks":["maju","kiri","kanan"],"map":[".###.",".##..",".S..G"],"hint":"Hitung kotaknya. Ulangi maju sebanyak itu!","palette":["maju","ulangi"],"best":2,"limit":2,"tip":"ulangi 3 kali [maju]","solution":{"main":[{"id":"b1","t":"loop","n":3,"body":[{"id":"b2","t":"cmd","c":"maju"}]}],"jurus":[]}},
{"id":"u3","theme":"kebun","dir":1,"blocks":["maju","kiri","kanan"],"map":["S...G","#....","..#.."],"hint":"Hitung kotaknya. Ulangi maju sebanyak itu!","palette":["maju","ulangi"],"best":2,"limit":2,"tip":"ulangi 4 kali [maju]","solution":{"main":[{"id":"b1","t":"loop","n":4,"body":[{"id":"b2","t":"cmd","c":"maju"}]}],"jurus":[]}},
{"id":"u4","theme":"kebun","dir":1,"blocks":["maju","kiri","kanan"],"map":["....#","...#.","S...G"],"hint":"Hitung kotaknya. Ulangi maju sebanyak itu!","palette":["maju","ulangi"],"best":2,"limit":2,"tip":"ulangi 4 kali [maju]","solution":{"main":[{"id":"b1","t":"loop","n":4,"body":[{"id":"b2","t":"cmd","c":"maju"}]}],"jurus":[]}},
{"id":"u5","theme":"kebun","dir":3,"blocks":["maju","kiri","kanan"],"map":[".#.#..","G....S","...~.."],"hint":"Hitung kotaknya. Ulangi maju sebanyak itu!","palette":["maju","ulangi"],"best":2,"limit":2,"tip":"ulangi 5 kali [maju]","solution":{"main":[{"id":"b1","t":"loop","n":5,"body":[{"id":"b2","t":"cmd","c":"maju"}]}],"jurus":[]}},
{"id":"u6","theme":"kebun","dir":0,"blocks":["maju","kiri","kanan"],"map":[".##.","#G..","....","...#","#...","...#",".S#."],"hint":"Hitung kotaknya. Ulangi maju sebanyak itu!","palette":["maju","ulangi"],"best":2,"limit":2,"tip":"ulangi 5 kali [maju]","solution":{"main":[{"id":"b1","t":"loop","n":5,"body":[{"id":"b2","t":"cmd","c":"maju"}]}],"jurus":[]}},
{"id":"u7","theme":"kebun","dir":1,"blocks":["maju","kiri","kanan"],"map":[".S.....G","....#~..","....#.#."],"hint":"Hitung kotaknya. Ulangi maju sebanyak itu!","palette":["maju","ulangi"],"best":2,"limit":2,"tip":"ulangi 6 kali [maju]","solution":{"main":[{"id":"b1","t":"loop","n":6,"body":[{"id":"b2","t":"cmd","c":"maju"}]}],"jurus":[]}},
{"id":"u8","theme":"kebun","dir":2,"blocks":["maju","kiri","kanan"],"map":["...S","....","....","~...","....",".#..",".#.G"],"hint":"Hitung kotaknya. Ulangi maju sebanyak itu!","palette":["maju","ulangi"],"best":2,"limit":2,"tip":"ulangi 6 kali [maju]","solution":{"main":[{"id":"b1","t":"loop","n":6,"body":[{"id":"b2","t":"cmd","c":"maju"}]}],"jurus":[]}},
{"id":"u9","theme":"kebun","dir":3,"blocks":["maju","kiri","kanan"],"map":["......#.","G......S","...~#.#."],"hint":"Hitung kotaknya. Ulangi maju sebanyak itu!","palette":["maju","ulangi"],"best":2,"limit":2,"tip":"ulangi 7 kali [maju]","solution":{"main":[{"id":"b1","t":"loop","n":7,"body":[{"id":"b2","t":"cmd","c":"maju"}]}],"jurus":[]}},
{"id":"u10","theme":"kebun","dir":1,"blocks":["maju","kiri","kanan"],"map":["S.......G",".~.......","........."],"hint":"Hitung kotaknya. Ulangi maju sebanyak itu!","palette":["maju","ulangi"],"best":2,"limit":2,"tip":"ulangi 8 kali [maju]","solution":{"main":[{"id":"b1","t":"loop","n":8,"body":[{"id":"b2","t":"cmd","c":"maju"}]}],"jurus":[]}},
{"id":"u11","theme":"pantai","dir":2,"blocks":["maju","kiri","kanan"],"map":["..#.S",".....",".....",".G..."],"hint":"Dua bagian lurus! Pakai dua blok ulangi dengan belokan di tengahnya.","palette":["maju","kiri","kanan","ulangi"],"best":5,"limit":6,"tip":"ulangi 3 kali [maju], belok kanan, ulangi 3 kali [maju]","solution":{"main":[{"id":"b1","t":"loop","n":3,"body":[{"id":"b2","t":"cmd","c":"maju"}]},
{"id":"b3","t":"cmd","c":"kanan"},
{"id":"b4","t":"loop","n":3,"body":[{"id":"b5","t":"cmd","c":"maju"}]}],"jurus":[]}},
{"id":"u12","theme":"pantai","dir":2,"blocks":["maju","kiri","kanan"],"map":["....~.","..~..S",".#....","......",".G...."],"hint":"Dua bagian lurus! Pakai dua blok ulangi dengan belokan di tengahnya.","palette":["maju","kiri","kanan","ulangi"],"best":5,"limit":6,"tip":"ulangi 3 kali [maju], belok kanan, ulangi 4 kali [maju]","solution":{"main":[{"id":"b1","t":"loop","n":3,"body":[{"id":"b2","t":"cmd","c":"maju"}]},
{"id":"b3","t":"cmd","c":"kanan"},
{"id":"b4","t":"loop","n":4,"body":[{"id":"b5","t":"cmd","c":"maju"}]}],"jurus":[]}},
{"id":"u13","theme":"pantai","dir":1,"blocks":["maju","kiri","kanan"],"map":["##...",".~..G",".~...",".~...","S...."],"hint":"Dua bagian lurus! Pakai dua blok ulangi dengan belokan di tengahnya.","palette":["maju","kiri","kanan","ulangi"],"best":5,"limit":6,"tip":"ulangi 4 kali [maju], belok kiri, ulangi 3 kali [maju]","solution":{"main":[{"id":"b1","t":"loop","n":4,"body":[{"id":"b2","t":"cmd","c":"maju"}]},
{"id":"b3","t":"cmd","c":"kiri"},
{"id":"b4","t":"loop","n":3,"body":[{"id":"b5","t":"cmd","c":"maju"}]}],"jurus":[]}},
{"id":"u14","theme":"pantai","dir":3,"blocks":["maju","kiri","kanan"],"map":["G....#","...#..","....~.","..#...","....S~"],"hint":"Dua bagian lurus! Pakai dua blok ulangi dengan belokan di tengahnya.","palette":["maju","kiri","kanan","ulangi"],"best":5,"limit":6,"tip":"ulangi 4 kali [maju], belok kanan, ulangi 4 kali [maju]","solution":{"main":[{"id":"b1","t":"loop","n":4,"body":[{"id":"b2","t":"cmd","c":"maju"}]},
{"id":"b3","t":"cmd","c":"kanan"},
{"id":"b4","t":"loop","n":4,"body":[{"id":"b5","t":"cmd","c":"maju"}]}],"jurus":[]}},
{"id":"u15","theme":"pantai","dir":0,"blocks":["maju","kiri","kanan"],"map":["..~...",".....G","......","...#.~","S.#..."],"hint":"Dua bagian lurus! Pakai dua blok ulangi dengan belokan di tengahnya.","palette":["maju","kiri","kanan","ulangi"],"best":5,"limit":6,"tip":"ulangi 3 kali [maju], belok kanan, ulangi 5 kali [maju]","solution":{"main":[{"id":"b1","t":"loop","n":3,"body":[{"id":"b2","t":"cmd","c":"maju"}]},
{"id":"b3","t":"cmd","c":"kanan"},
{"id":"b4","t":"loop","n":5,"body":[{"id":"b5","t":"cmd","c":"maju"}]}],"jurus":[]}},
{"id":"u16","theme":"pantai","dir":0,"blocks":["maju","kiri","kanan"],"map":["..~~","G...","....","~...","....","....",".#.S"],"hint":"Dua bagian lurus! Pakai dua blok ulangi dengan belokan di tengahnya.","palette":["maju","kiri","kanan","ulangi"],"best":5,"limit":6,"tip":"ulangi 5 kali [maju], belok kiri, ulangi 3 kali [maju]","solution":{"main":[{"id":"b1","t":"loop","n":5,"body":[{"id":"b2","t":"cmd","c":"maju"}]},
{"id":"b3","t":"cmd","c":"kiri"},
{"id":"b4","t":"loop","n":3,"body":[{"id":"b5","t":"cmd","c":"maju"}]}],"jurus":[]}},
{"id":"u17","theme":"pantai","dir":1,"blocks":["maju","kiri","kanan"],"map":[".....G","#.....",".#....","..#...",".~.~..",".S....","......"],"hint":"Dua bagian lurus! Pakai dua blok ulangi dengan belokan di tengahnya.","palette":["maju","kiri","kanan","ulangi"],"best":5,"limit":6,"tip":"ulangi 4 kali [maju], belok kiri, ulangi 5 kali [maju]","solution":{"main":[{"id":"b1","t":"loop","n":4,"body":[{"id":"b2","t":"cmd","c":"maju"}]},
{"id":"b3","t":"cmd","c":"kiri"},
{"id":"b4","t":"loop","n":5,"body":[{"id":"b5","t":"cmd","c":"maju"}]}],"jurus":[]}},
{"id":"u18","theme":"pantai","dir":3,"blocks":["maju","kiri","kanan"],"map":["G......","....#~.",".......","..#...~",".....S."],"hint":"Dua bagian lurus! Pakai dua blok ulangi dengan belokan di tengahnya.","palette":["maju","kiri","kanan","ulangi"],"best":5,"limit":6,"tip":"ulangi 5 kali [maju], belok kanan, ulangi 4 kali [maju]","solution":{"main":[{"id":"b1","t":"loop","n":5,"body":[{"id":"b2","t":"cmd","c":"maju"}]},
{"id":"b3","t":"cmd","c":"kanan"},
{"id":"b4","t":"loop","n":4,"body":[{"id":"b5","t":"cmd","c":"maju"}]}],"jurus":[]}},
{"id":"u19","theme":"pantai","dir":0,"blocks":["maju","kiri","kanan"],"map":[".#.G","....","..~.","....","....","....","S~.."],"hint":"Dua bagian lurus! Pakai dua blok ulangi dengan belokan di tengahnya.","palette":["maju","kiri","kanan","ulangi"],"best":8,"limit":9,"tip":"ulangi 3 kali [maju], belok kanan, ulangi 3 kali [maju], belok kiri, ulangi 3 kali [maju]","solution":{"main":[{"id":"b1","t":"loop","n":3,"body":[{"id":"b2","t":"cmd","c":"maju"}]},
{"id":"b3","t":"cmd","c":"kanan"},
{"id":"b4","t":"loop","n":3,"body":[{"id":"b5","t":"cmd","c":"maju"}]},
{"id":"b6","t":"cmd","c":"kiri"},
{"id":"b7","t":"loop","n":3,"body":[{"id":"b8","t":"cmd","c":"maju"}]}],"jurus":[]}},
{"id":"u20","theme":"pantai","dir":2,"blocks":["maju","kiri","kanan"],"map":["...~S.","~.....",".....#","......","......","....#~","G~...."],"hint":"Dua bagian lurus! Pakai dua blok ulangi dengan belokan di tengahnya.","palette":["maju","kiri","kanan","ulangi"],"best":8,"limit":9,"tip":"ulangi 3 kali [maju], belok kanan, ulangi 4 kali [maju], belok kiri, ulangi 3 kali [maju]","solution":{"main":[{"id":"b1","t":"loop","n":3,"body":[{"id":"b2","t":"cmd","c":"maju"}]},
{"id":"b3","t":"cmd","c":"kanan"},
{"id":"b4","t":"loop","n":4,"body":[{"id":"b5","t":"cmd","c":"maju"}]},
{"id":"b6","t":"cmd","c":"kiri"},
{"id":"b7","t":"loop","n":3,"body":[{"id":"b8","t":"cmd","c":"maju"}]}],"jurus":[]}},
{"id":"u21","theme":"hutan","dir":2,"blocks":["maju","kiri","kanan"],"map":["....",".S.#","...#","##.G"],"hint":"Jalannya seperti tangga. Cari gerakan yang berulang: maju, belok, maju, belok…","palette":["maju","kiri","kanan","ulangi"],"best":5,"limit":6,"tip":"ulangi 2 kali [maju, belok kiri, maju, belok kanan]","solution":{"main":[{"id":"b1","t":"loop","n":2,"body":[{"id":"b2","t":"cmd","c":"maju"},
{"id":"b3","t":"cmd","c":"kiri"},
{"id":"b4","t":"cmd","c":"maju"},
{"id":"b5","t":"cmd","c":"kanan"}]}],"jurus":[]}},
{"id":"u22","theme":"hutan","dir":2,"blocks":["maju","kiri","kanan"],"map":[".....","#S.##","...##",".~..#",".~#.G"],"hint":"Jalannya seperti tangga. Cari gerakan yang berulang: maju, belok, maju, belok…","palette":["maju","kiri","kanan","ulangi"],"best":5,"limit":6,"tip":"ulangi 3 kali [maju, belok kiri, maju, belok kanan]","solution":{"main":[{"id":"b1","t":"loop","n":3,"body":[{"id":"b2","t":"cmd","c":"maju"},
{"id":"b3","t":"cmd","c":"kiri"},
{"id":"b4","t":"cmd","c":"maju"},
{"id":"b5","t":"cmd","c":"kanan"}]}],"jurus":[]}},
{"id":"u23","theme":"hutan","dir":1,"blocks":["maju","kiri","kanan"],"map":["~..~G","#.~..","....#",".S.~#"],"hint":"Jalannya seperti tangga. Cari gerakan yang berulang: maju, belok, maju, belok…","palette":["maju","kiri","kanan","ulangi"],"best":5,"limit":6,"tip":"ulangi 3 kali [maju, belok kiri, maju, belok kanan]","solution":{"main":[{"id":"b1","t":"loop","n":3,"body":[{"id":"b2","t":"cmd","c":"maju"},
{"id":"b3","t":"cmd","c":"kiri"},
{"id":"b4","t":"cmd","c":"maju"},
{"id":"b5","t":"cmd","c":"kanan"}]}],"jurus":[]}},
{"id":"u24","theme":"hutan","dir":0,"blocks":["maju","kiri","kanan"],"map":["G.~#","#..~",".~..",".#~S","###."],"hint":"Jalannya seperti tangga. Cari gerakan yang berulang: maju, belok, maju, belok…","palette":["maju","kiri","kanan","ulangi"],"best":5,"limit":6,"tip":"ulangi 3 kali [maju, belok kiri, maju, belok kanan]","solution":{"main":[{"id":"b1","t":"loop","n":3,"body":[{"id":"b2","t":"cmd","c":"maju"},
{"id":"b3","t":"cmd","c":"kiri"},
{"id":"b4","t":"cmd","c":"maju"},
{"id":"b5","t":"cmd","c":"kanan"}]}],"jurus":[]}},
{"id":"u25","theme":"hutan","dir":0,"blocks":["maju","kiri","kanan"],"map":[".G.#..","~#..~.","..#..#","#..#..",".#...S"],"hint":"Jalannya seperti tangga. Cari gerakan yang berulang: maju, belok, maju, belok…","palette":["maju","kiri","kanan","ulangi"],"best":5,"limit":6,"tip":"ulangi 4 kali [maju, belok kiri, maju, belok kanan]","solution":{"main":[{"id":"b1","t":"loop","n":4,"body":[{"id":"b2","t":"cmd","c":"maju"},
{"id":"b3","t":"cmd","c":"kiri"},
{"id":"b4","t":"cmd","c":"maju"},
{"id":"b5","t":"cmd","c":"kanan"}]}],"jurus":[]}},
{"id":"u26","theme":"hutan","dir":1,"blocks":["maju","kiri","kanan"],"map":["..##G~",".##...",".#..#.","#..##.","S.~..#"],"hint":"Jalannya seperti tangga. Cari gerakan yang berulang: maju, belok, maju, belok…","palette":["maju","kiri","kanan","ulangi"],"best":5,"limit":6,"tip":"ulangi 4 kali [maju, belok kiri, maju, belok kanan]","solution":{"main":[{"id":"b1","t":"loop","n":4,"body":[{"id":"b2","t":"cmd","c":"maju"},
{"id":"b3","t":"cmd","c":"kiri"},
{"id":"b4","t":"cmd","c":"maju"},
{"id":"b5","t":"cmd","c":"kanan"}]}],"jurus":[]}},
{"id":"u27","theme":"hutan","dir":0,"blocks":["maju","kiri","kanan"],"map":["G.#.#.","#..~~.","~#..#.","..~...","#...S."],"hint":"Jalannya seperti tangga. Cari gerakan yang berulang: maju, belok, maju, belok…","palette":["maju","kiri","kanan","ulangi"],"best":5,"limit":6,"tip":"ulangi 4 kali [maju, belok kiri, maju, belok kanan]","solution":{"main":[{"id":"b1","t":"loop","n":4,"body":[{"id":"b2","t":"cmd","c":"maju"},
{"id":"b3","t":"cmd","c":"kiri"},
{"id":"b4","t":"cmd","c":"maju"},
{"id":"b5","t":"cmd","c":"kanan"}]}],"jurus":[]}},
{"id":"u28","theme":"hutan","dir":2,"blocks":["maju","kiri","kanan"],"map":[".~.S","~...",".~..","...~","#..#","..#~","G.~."],"hint":"Jalannya seperti tangga. Cari gerakan yang berulang: maju, belok, maju, belok…","palette":["maju","kiri","kanan","ulangi"],"best":6,"limit":7,"tip":"ulangi 3 kali [maju 2×, belok kanan, maju, belok kiri]","solution":{"main":[{"id":"b1","t":"loop","n":3,"body":[{"id":"b2","t":"cmd","c":"maju"},
{"id":"b3","t":"cmd","c":"maju"},
{"id":"b4","t":"cmd","c":"kanan"},
{"id":"b5","t":"cmd","c":"maju"},
{"id":"b6","t":"cmd","c":"kiri"}]}],"jurus":[]}},
{"id":"u29","theme":"hutan","dir":3,"blocks":["maju","kiri","kanan"],"map":["##~#..S","~......","....#..","G#~...."],"hint":"Jalannya seperti tangga. Cari gerakan yang berulang: maju, belok, maju, belok…","palette":["maju","kiri","kanan","ulangi"],"best":6,"limit":7,"tip":"ulangi 3 kali [maju 2×, belok kiri, maju, belok kanan]","solution":{"main":[{"id":"b1","t":"loop","n":3,"body":[{"id":"b2","t":"cmd","c":"maju"},
{"id":"b3","t":"cmd","c":"maju"},
{"id":"b4","t":"cmd","c":"kiri"},
{"id":"b5","t":"cmd","c":"maju"},
{"id":"b6","t":"cmd","c":"kanan"}]}],"jurus":[]}},
{"id":"u30","theme":"hutan","dir":1,"blocks":["maju","kiri","kanan"],"map":["..#..#G.","...~.#.#","...#....","...#....",".....#..","~~..#...","S..#~..."],"hint":"Jalannya seperti tangga. Cari gerakan yang berulang: maju, belok, maju, belok…","palette":["maju","kiri","kanan","ulangi"],"best":7,"limit":8,"tip":"ulangi 3 kali [maju 2×, belok kiri, maju 2×, belok kanan]","solution":{"main":[{"id":"b1","t":"loop","n":3,"body":[{"id":"b2","t":"cmd","c":"maju"},
{"id":"b3","t":"cmd","c":"maju"},
{"id":"b4","t":"cmd","c":"kiri"},
{"id":"b5","t":"cmd","c":"maju"},
{"id":"b6","t":"cmd","c":"maju"},
{"id":"b7","t":"cmd","c":"kanan"}]}],"jurus":[]}},
{"id":"u31","theme":"sawah","dir":2,"blocks":["maju","kiri","kanan"],"map":["..#S","....",".G..","..#."],"hint":"Agam berkeliling pematang. Setiap sisi: maju beberapa kali, lalu belok ke arah yang sama.","palette":["maju","kiri","kanan","ulangi"],"best":4,"limit":4,"tip":"ulangi 2 kali [maju 2×, belok kanan]","solution":{"main":[{"id":"b1","t":"loop","n":2,"body":[{"id":"b2","t":"cmd","c":"maju"},
{"id":"b3","t":"cmd","c":"maju"},
{"id":"b4","t":"cmd","c":"kanan"}]}],"jurus":[]}},
{"id":"u32","theme":"sawah","dir":0,"blocks":["maju","kiri","kanan"],"map":["G....",".#...","~....","..~S.","~...."],"hint":"Agam berkeliling pematang. Setiap sisi: maju beberapa kali, lalu belok ke arah yang sama.","palette":["maju","kiri","kanan","ulangi"],"best":5,"limit":6,"tip":"ulangi 2 kali [maju 3×, belok kiri]","solution":{"main":[{"id":"b1","t":"loop","n":2,"body":[{"id":"b2","t":"cmd","c":"maju"},
{"id":"b3","t":"cmd","c":"maju"},
{"id":"b4","t":"cmd","c":"maju"},
{"id":"b5","t":"cmd","c":"kiri"}]}],"jurus":[]}},
{"id":"u33","theme":"sawah","dir":0,"blocks":["maju","kiri","kanan"],"map":["G.....","...#..","~~....",".#.~..","...~S.","...~.."],"hint":"Agam berkeliling pematang. Setiap sisi: maju beberapa kali, lalu belok ke arah yang sama.","palette":["maju","kiri","kanan","ulangi"],"best":6,"limit":7,"tip":"ulangi 2 kali [maju 4×, belok kiri]","solution":{"main":[{"id":"b1","t":"loop","n":2,"body":[{"id":"b2","t":"cmd","c":"maju"},
{"id":"b3","t":"cmd","c":"maju"},
{"id":"b4","t":"cmd","c":"maju"},
{"id":"b5","t":"cmd","c":"maju"},
{"id":"b6","t":"cmd","c":"kiri"}]}],"jurus":[]}},
{"id":"u34","theme":"sawah","dir":2,"blocks":["maju","kiri","kanan"],"map":[".S~G","~.#.","...."],"hint":"Agam berkeliling pematang. Setiap sisi: maju beberapa kali, lalu belok ke arah yang sama.","palette":["maju","kiri","kanan","ulangi"],"best":4,"limit":5,"tip":"ulangi 3 kali [maju 2×, belok kiri]","solution":{"main":[{"id":"b1","t":"loop","n":3,"body":[{"id":"b2","t":"cmd","c":"maju"},
{"id":"b3","t":"cmd","c":"maju"},
{"id":"b4","t":"cmd","c":"kiri"}]}],"jurus":[]}},
{"id":"u35","theme":"sawah","dir":0,"blocks":["maju","kiri","kanan"],"map":["...#",".~..","S~G#"],"hint":"Agam berkeliling pematang. Setiap sisi: maju beberapa kali, lalu belok ke arah yang sama.","palette":["maju","kiri","kanan","ulangi"],"best":4,"limit":5,"tip":"ulangi 3 kali [maju 2×, belok kanan]","solution":{"main":[{"id":"b1","t":"loop","n":3,"body":[{"id":"b2","t":"cmd","c":"maju"},
{"id":"b3","t":"cmd","c":"maju"},
{"id":"b4","t":"cmd","c":"kanan"}]}],"jurus":[]}},
{"id":"u36","theme":"sawah","dir":0,"blocks":["maju","kiri","kanan"],"map":["....","..~.","..~.","S~.G"],"hint":"Agam berkeliling pematang. Setiap sisi: maju beberapa kali, lalu belok ke arah yang sama.","palette":["maju","kiri","kanan","ulangi"],"best":5,"limit":6,"tip":"ulangi 3 kali [maju 3×, belok kanan]","solution":{"main":[{"id":"b1","t":"loop","n":3,"body":[{"id":"b2","t":"cmd","c":"maju"},
{"id":"b3","t":"cmd","c":"maju"},
{"id":"b4","t":"cmd","c":"maju"},
{"id":"b5","t":"cmd","c":"kanan"}]}],"jurus":[]}},
{"id":"u37","theme":"sawah","dir":3,"blocks":["maju","kiri","kanan"],"map":["...S",".~~.","...#","...G"],"hint":"Agam berkeliling pematang. Setiap sisi: maju beberapa kali, lalu belok ke arah yang sama.","palette":["maju","kiri","kanan","ulangi"],"best":5,"limit":6,"tip":"ulangi 3 kali [maju 3×, belok kiri]","solution":{"main":[{"id":"b1","t":"loop","n":3,"body":[{"id":"b2","t":"cmd","c":"maju"},
{"id":"b3","t":"cmd","c":"maju"},
{"id":"b4","t":"cmd","c":"maju"},
{"id":"b5","t":"cmd","c":"kiri"}]}],"jurus":[]}},
{"id":"u38","theme":"sawah","dir":0,"blocks":["maju","kiri","kanan"],"map":[".~...~","......","~...~.","..~.~.","..~...",".S~~.G"],"hint":"Agam berkeliling pematang. Setiap sisi: maju beberapa kali, lalu belok ke arah yang sama.","palette":["maju","kiri","kanan","ulangi"],"best":6,"limit":7,"tip":"ulangi 3 kali [maju 4×, belok kanan]","solution":{"main":[{"id":"b1","t":"loop","n":3,"body":[{"id":"b2","t":"cmd","c":"maju"},
{"id":"b3","t":"cmd","c":"maju"},
{"id":"b4","t":"cmd","c":"maju"},
{"id":"b5","t":"cmd","c":"maju"},
{"id":"b6","t":"cmd","c":"kanan"}]}],"jurus":[]}},
{"id":"u39","theme":"sawah","dir":0,"blocks":["maju","kiri","kanan"],"map":[".....","..~..","..#..","...#.","S.~.G","..#.~"],"hint":"Agam berkeliling pematang. Setiap sisi: maju beberapa kali, lalu belok ke arah yang sama.","palette":["maju","kiri","kanan","ulangi"],"best":6,"limit":7,"tip":"ulangi 3 kali [maju 4×, belok kanan]","solution":{"main":[{"id":"b1","t":"loop","n":3,"body":[{"id":"b2","t":"cmd","c":"maju"},
{"id":"b3","t":"cmd","c":"maju"},
{"id":"b4","t":"cmd","c":"maju"},
{"id":"b5","t":"cmd","c":"maju"},
{"id":"b6","t":"cmd","c":"kanan"}]}],"jurus":[]}},
{"id":"u40","theme":"sawah","dir":0,"blocks":["maju","kiri","kanan"],"map":["......","..~~..","..~...",".~..#.","...~..","G~..~S","..~..~"],"hint":"Agam berkeliling pematang. Setiap sisi: maju beberapa kali, lalu belok ke arah yang sama.","palette":["maju","kiri","kanan","ulangi"],"best":7,"limit":8,"tip":"ulangi 3 kali [maju 5×, belok kiri]","solution":{"main":[{"id":"b1","t":"loop","n":3,"body":[{"id":"b2","t":"cmd","c":"maju"},
{"id":"b3","t":"cmd","c":"maju"},
{"id":"b4","t":"cmd","c":"maju"},
{"id":"b5","t":"cmd","c":"maju"},
{"id":"b6","t":"cmd","c":"maju"},
{"id":"b7","t":"cmd","c":"kiri"}]}],"jurus":[]}},
{"id":"u41","theme":"kota","dir":3,"blocks":["maju","kiri","kanan"],"map":["..##.#","..#..S",".#..#.",".G.~.."],"hint":"Ada dua bagian: jalan lurus dan tangga. Satu ulangi untuk tiap bagian.","palette":["maju","kiri","kanan","ulangi"],"best":7,"limit":8,"tip":"ulangi 2 kali [maju], ulangi 2 kali [belok kiri, maju, belok kanan, maju]","solution":{"main":[{"id":"b1","t":"loop","n":2,"body":[{"id":"b2","t":"cmd","c":"maju"}]},
{"id":"b3","t":"loop","n":2,"body":[{"id":"b4","t":"cmd","c":"kiri"},
{"id":"b5","t":"cmd","c":"maju"},
{"id":"b6","t":"cmd","c":"kanan"},
{"id":"b7","t":"cmd","c":"maju"}]}],"jurus":[]}},
{"id":"u42","theme":"kota","dir":1,"blocks":["maju","kiri","kanan"],"map":["S...~.","..#..#","#.~#.G"],"hint":"Ada dua bagian: jalan lurus dan tangga. Satu ulangi untuk tiap bagian.","palette":["maju","kiri","kanan","ulangi"],"best":7,"limit":8,"tip":"ulangi 3 kali [maju], ulangi 2 kali [belok kanan, maju, belok kiri, maju]","solution":{"main":[{"id":"b1","t":"loop","n":3,"body":[{"id":"b2","t":"cmd","c":"maju"}]},
{"id":"b3","t":"loop","n":2,"body":[{"id":"b4","t":"cmd","c":"kanan"},
{"id":"b5","t":"cmd","c":"maju"},
{"id":"b6","t":"cmd","c":"kiri"},
{"id":"b7","t":"cmd","c":"maju"}]}],"jurus":[]}},
{"id":"u43","theme":"kota","dir":0,"blocks":["maju","kiri","kanan"],"map":["G~...","..#..","~..~.","~~..#","#...~","#....",".~.S."],"hint":"Ada dua bagian: jalan lurus dan tangga. Satu ulangi untuk tiap bagian.","palette":["maju","kiri","kanan","ulangi"],"best":7,"limit":8,"tip":"ulangi 3 kali [maju], ulangi 3 kali [belok kiri, maju, belok kanan, maju]","solution":{"main":[{"id":"b1","t":"loop","n":3,"body":[{"id":"b2","t":"cmd","c":"maju"}]},
{"id":"b3","t":"loop","n":3,"body":[{"id":"b4","t":"cmd","c":"kiri"},
{"id":"b5","t":"cmd","c":"maju"},
{"id":"b6","t":"cmd","c":"kanan"},
{"id":"b7","t":"cmd","c":"maju"}]}],"jurus":[]}},
{"id":"u44","theme":"kota","dir":3,"blocks":["maju","kiri","kanan"],"map":["G.#.....","#.....#.",".#....S."],"hint":"Ada dua bagian: jalan lurus dan tangga. Satu ulangi untuk tiap bagian.","palette":["maju","kiri","kanan","ulangi"],"best":7,"limit":8,"tip":"ulangi 4 kali [maju], ulangi 2 kali [belok kanan, maju, belok kiri, maju]","solution":{"main":[{"id":"b1","t":"loop","n":4,"body":[{"id":"b2","t":"cmd","c":"maju"}]},
{"id":"b3","t":"loop","n":2,"body":[{"id":"b4","t":"cmd","c":"kanan"},
{"id":"b5","t":"cmd","c":"maju"},
{"id":"b6","t":"cmd","c":"kiri"},
{"id":"b7","t":"cmd","c":"maju"}]}],"jurus":[]}},
{"id":"u45","theme":"kota","dir":1,"blocks":["maju","kiri","kanan"],"map":[".S....#.~","..#....~.","...~.#..#","#....##.G"],"hint":"Ada dua bagian: jalan lurus dan tangga. Satu ulangi untuk tiap bagian.","palette":["maju","kiri","kanan","ulangi"],"best":7,"limit":8,"tip":"ulangi 4 kali [maju], ulangi 3 kali [belok kanan, maju, belok kiri, maju]","solution":{"main":[{"id":"b1","t":"loop","n":4,"body":[{"id":"b2","t":"cmd","c":"maju"}]},
{"id":"b3","t":"loop","n":3,"body":[{"id":"b4","t":"cmd","c":"kanan"},
{"id":"b5","t":"cmd","c":"maju"},
{"id":"b6","t":"cmd","c":"kiri"},
{"id":"b7","t":"cmd","c":"maju"}]}],"jurus":[]}},
{"id":"u46","theme":"kota","dir":3,"blocks":["maju","kiri","kanan"],"map":["#.....","~.#.S.",".#....","G..##."],"hint":"Ada dua bagian: jalan lurus dan tangga. Satu ulangi untuk tiap bagian.","palette":["maju","kiri","kanan","ulangi"],"best":7,"limit":8,"tip":"ulangi 2 kali [maju, belok kiri, maju, belok kanan], ulangi 2 kali [maju]","solution":{"main":[{"id":"b1","t":"loop","n":2,"body":[{"id":"b2","t":"cmd","c":"maju"},
{"id":"b3","t":"cmd","c":"kiri"},
{"id":"b4","t":"cmd","c":"maju"},
{"id":"b5","t":"cmd","c":"kanan"}]},
{"id":"b6","t":"loop","n":2,"body":[{"id":"b7","t":"cmd","c":"maju"}]}],"jurus":[]}},
{"id":"u47","theme":"kota","dir":3,"blocks":["maju","kiri","kanan"],"map":[".G...#.","..~...#","##~.#.S","......#"],"hint":"Ada dua bagian: jalan lurus dan tangga. Satu ulangi untuk tiap bagian.","palette":["maju","kiri","kanan","ulangi"],"best":7,"limit":8,"tip":"ulangi 2 kali [maju, belok kanan, maju, belok kiri], ulangi 3 kali [maju]","solution":{"main":[{"id":"b1","t":"loop","n":2,"body":[{"id":"b2","t":"cmd","c":"maju"},
{"id":"b3","t":"cmd","c":"kanan"},
{"id":"b4","t":"cmd","c":"maju"},
{"id":"b5","t":"cmd","c":"kiri"}]},
{"id":"b6","t":"loop","n":3,"body":[{"id":"b7","t":"cmd","c":"maju"}]}],"jurus":[]}},
{"id":"u48","theme":"kota","dir":2,"blocks":["maju","kiri","kanan"],"map":["~S..#","#..##","~#..#","#.#..","...#.","..#..","....G"],"hint":"Ada dua bagian: jalan lurus dan tangga. Satu ulangi untuk tiap bagian.","palette":["maju","kiri","kanan","ulangi"],"best":7,"limit":8,"tip":"ulangi 3 kali [maju, belok kiri, maju, belok kanan], ulangi 3 kali [maju]","solution":{"main":[{"id":"b1","t":"loop","n":3,"body":[{"id":"b2","t":"cmd","c":"maju"},
{"id":"b3","t":"cmd","c":"kiri"},
{"id":"b4","t":"cmd","c":"maju"},
{"id":"b5","t":"cmd","c":"kanan"}]},
{"id":"b6","t":"loop","n":3,"body":[{"id":"b7","t":"cmd","c":"maju"}]}],"jurus":[]}},
{"id":"u49","theme":"kota","dir":3,"blocks":["maju","kiri","kanan"],"map":["...##.#.S","#....#...",".###...~~",".G....##."],"hint":"Ada dua bagian: jalan lurus dan tangga. Satu ulangi untuk tiap bagian.","palette":["maju","kiri","kanan","ulangi"],"best":7,"limit":8,"tip":"ulangi 3 kali [maju, belok kiri, maju, belok kanan], ulangi 4 kali [maju]","solution":{"main":[{"id":"b1","t":"loop","n":3,"body":[{"id":"b2","t":"cmd","c":"maju"},
{"id":"b3","t":"cmd","c":"kiri"},
{"id":"b4","t":"cmd","c":"maju"},
{"id":"b5","t":"cmd","c":"kanan"}]},
{"id":"b6","t":"loop","n":4,"body":[{"id":"b7","t":"cmd","c":"maju"}]}],"jurus":[]}},
{"id":"u50","theme":"kota","dir":3,"blocks":["maju","kiri","kanan"],"map":["#.#.##.S.","..###..~.","..##..~..","G....##.."],"hint":"Ada dua bagian: jalan lurus dan tangga. Satu ulangi untuk tiap bagian.","palette":["maju","kiri","kanan","ulangi"],"best":7,"limit":8,"tip":"ulangi 3 kali [maju, belok kiri, maju, belok kanan], ulangi 4 kali [maju]","solution":{"main":[{"id":"b1","t":"loop","n":3,"body":[{"id":"b2","t":"cmd","c":"maju"},
{"id":"b3","t":"cmd","c":"kiri"},
{"id":"b4","t":"cmd","c":"maju"},
{"id":"b5","t":"cmd","c":"kanan"}]},
{"id":"b6","t":"loop","n":4,"body":[{"id":"b7","t":"cmd","c":"maju"}]}],"jurus":[]}},
{"id":"u51","theme":"salju","dir":2,"blocks":["maju","kiri","kanan"],"map":["~~.~","S...","..~.","...~","#.~.","~.G."],"hint":"Anak tangganya besar! Hitung berapa maju ke depan dan berapa maju ke samping.","palette":["maju","kiri","kanan","ulangi"],"best":6,"limit":7,"tip":"ulangi 2 kali [maju 2×, belok kiri, maju, belok kanan]","solution":{"main":[{"id":"b1","t":"loop","n":2,"body":[{"id":"b2","t":"cmd","c":"maju"},
{"id":"b3","t":"cmd","c":"maju"},
{"id":"b4","t":"cmd","c":"kiri"},
{"id":"b5","t":"cmd","c":"maju"},
{"id":"b6","t":"cmd","c":"kanan"}]}],"jurus":[]}},
{"id":"u52","theme":"salju","dir":1,"blocks":["maju","kiri","kanan"],"map":["...#","...G",".#~.","....","....","~S.#"],"hint":"Jalannya berkelok seperti ular. Setiap bagian lurus pakai ulangi.","palette":["maju","kiri","kanan","ulangi"],"best":6,"limit":7,"tip":"ulangi 2 kali [maju, belok kiri, maju 2×, belok kanan]","solution":{"main":[{"id":"b1","t":"loop","n":2,"body":[{"id":"b2","t":"cmd","c":"maju"},
{"id":"b3","t":"cmd","c":"kiri"},
{"id":"b4","t":"cmd","c":"maju"},
{"id":"b5","t":"cmd","c":"maju"},
{"id":"b6","t":"cmd","c":"kanan"}]}],"jurus":[]}},
{"id":"u53","theme":"salju","dir":0,"blocks":["maju","kiri","kanan"],"map":["....G.","~.....","...#.~","..~~.~","S..#..","#..~.#"],"hint":"Jalannya berkelok seperti ular. Setiap bagian lurus pakai ulangi.","palette":["maju","kiri","kanan","ulangi"],"best":7,"limit":8,"tip":"ulangi 2 kali [maju 2×, belok kanan, maju 2×, belok kiri]","solution":{"main":[{"id":"b1","t":"loop","n":2,"body":[{"id":"b2","t":"cmd","c":"maju"},
{"id":"b3","t":"cmd","c":"maju"},
{"id":"b4","t":"cmd","c":"kanan"},
{"id":"b5","t":"cmd","c":"maju"},
{"id":"b6","t":"cmd","c":"maju"},
{"id":"b7","t":"cmd","c":"kiri"}]}],"jurus":[]}},
{"id":"u54","theme":"salju","dir":3,"blocks":["maju","kiri","kanan"],"map":[".G#~....",".....#~.","#~....~.","#..##..S"],"hint":"Jalannya berkelok seperti ular. Setiap bagian lurus pakai ulangi.","palette":["maju","kiri","kanan","ulangi"],"best":6,"limit":7,"tip":"ulangi 3 kali [maju 2×, belok kanan, maju, belok kiri]","solution":{"main":[{"id":"b1","t":"loop","n":3,"body":[{"id":"b2","t":"cmd","c":"maju"},
{"id":"b3","t":"cmd","c":"maju"},
{"id":"b4","t":"cmd","c":"kanan"},
{"id":"b5","t":"cmd","c":"maju"},
{"id":"b6","t":"cmd","c":"kiri"}]}],"jurus":[]}},
{"id":"u55","theme":"salju","dir":2,"blocks":["maju","kiri","kanan"],"map":["......#","......S",".~#~...","~~...#.","G...##."],"hint":"Jalannya berkelok seperti ular. Setiap bagian lurus pakai ulangi.","palette":["maju","kiri","kanan","ulangi"],"best":6,"limit":7,"tip":"ulangi 3 kali [maju, belok kanan, maju 2×, belok kiri]","solution":{"main":[{"id":"b1","t":"loop","n":3,"body":[{"id":"b2","t":"cmd","c":"maju"},
{"id":"b3","t":"cmd","c":"kanan"},
{"id":"b4","t":"cmd","c":"maju"},
{"id":"b5","t":"cmd","c":"maju"},
{"id":"b6","t":"cmd","c":"kiri"}]}],"jurus":[]}},
{"id":"u56","theme":"salju","dir":0,"blocks":["maju","kiri","kanan"],"map":["G~...#",".#.~..",".#.#..","...#S.","~.#..~"],"hint":"Jalannya berkelok seperti ular. Setiap bagian lurus pakai ulangi.","palette":["maju","kiri","kanan","ulangi"],"best":14,"limit":15,"tip":"ulangi 3 kali [maju], belok kiri, ulangi 2 kali [maju], belok kiri, ulangi 3 kali [maju], belok kanan, ulangi 2 kali [maju], belok kanan, ulangi 3 kali [maju]","solution":{"main":[{"id":"b1","t":"loop","n":3,"body":[{"id":"b2","t":"cmd","c":"maju"}]},
{"id":"b3","t":"cmd","c":"kiri"},
{"id":"b4","t":"loop","n":2,"body":[{"id":"b5","t":"cmd","c":"maju"}]},
{"id":"b6","t":"cmd","c":"kiri"},
{"id":"b7","t":"loop","n":3,"body":[{"id":"b8","t":"cmd","c":"maju"}]},
{"id":"b9","t":"cmd","c":"kanan"},
{"id":"b10","t":"loop","n":2,"body":[{"id":"b11","t":"cmd","c":"maju"}]},
{"id":"b12","t":"cmd","c":"kanan"},
{"id":"b13","t":"loop","n":3,"body":[{"id":"b14","t":"cmd","c":"maju"}]}],"jurus":[]}},
{"id":"u57","theme":"salju","dir":1,"blocks":["maju","kiri","kanan"],"map":["S...","###.","....",".#~#","...G",".#.~"],"hint":"Jalannya berkelok seperti ular. Setiap bagian lurus pakai ulangi.","palette":["maju","kiri","kanan","ulangi"],"best":14,"limit":15,"tip":"ulangi 3 kali [maju], belok kanan, ulangi 2 kali [maju], belok kanan, ulangi 3 kali [maju], belok kiri, ulangi 2 kali [maju], belok kiri, ulangi 3 kali [maju]","solution":{"main":[{"id":"b1","t":"loop","n":3,"body":[{"id":"b2","t":"cmd","c":"maju"}]},
{"id":"b3","t":"cmd","c":"kanan"},
{"id":"b4","t":"loop","n":2,"body":[{"id":"b5","t":"cmd","c":"maju"}]},
{"id":"b6","t":"cmd","c":"kanan"},
{"id":"b7","t":"loop","n":3,"body":[{"id":"b8","t":"cmd","c":"maju"}]},
{"id":"b9","t":"cmd","c":"kiri"},
{"id":"b10","t":"loop","n":2,"body":[{"id":"b11","t":"cmd","c":"maju"}]},
{"id":"b12","t":"cmd","c":"kiri"},
{"id":"b13","t":"loop","n":3,"body":[{"id":"b14","t":"cmd","c":"maju"}]}],"jurus":[]}},
{"id":"u58","theme":"salju","dir":2,"blocks":["maju","kiri","kanan"],"map":[".S#...","~.~.#.","..~.~.","#.#.#.","....~G"],"hint":"Jalannya berkelok seperti ular. Setiap bagian lurus pakai ulangi.","palette":["maju","kiri","kanan","ulangi"],"best":14,"limit":15,"tip":"ulangi 4 kali [maju], belok kiri, ulangi 2 kali [maju], belok kiri, ulangi 4 kali [maju], belok kanan, ulangi 2 kali [maju], belok kanan, ulangi 4 kali [maju]","solution":{"main":[{"id":"b1","t":"loop","n":4,"body":[{"id":"b2","t":"cmd","c":"maju"}]},
{"id":"b3","t":"cmd","c":"kiri"},
{"id":"b4","t":"loop","n":2,"body":[{"id":"b5","t":"cmd","c":"maju"}]},
{"id":"b6","t":"cmd","c":"kiri"},
{"id":"b7","t":"loop","n":4,"body":[{"id":"b8","t":"cmd","c":"maju"}]},
{"id":"b9","t":"cmd","c":"kanan"},
{"id":"b10","t":"loop","n":2,"body":[{"id":"b11","t":"cmd","c":"maju"}]},
{"id":"b12","t":"cmd","c":"kanan"},
{"id":"b13","t":"loop","n":4,"body":[{"id":"b14","t":"cmd","c":"maju"}]}],"jurus":[]}},
{"id":"u59","theme":"salju","dir":0,"blocks":["maju","kiri","kanan"],"map":["G~....",".~.~..",".#.#..",".#.#..","...#S."],"hint":"Jalannya berkelok seperti ular. Setiap bagian lurus pakai ulangi.","palette":["maju","kiri","kanan","ulangi"],"best":14,"limit":15,"tip":"ulangi 4 kali [maju], belok kiri, ulangi 2 kali [maju], belok kiri, ulangi 4 kali [maju], belok kanan, ulangi 2 kali [maju], belok kanan, ulangi 4 kali [maju]","solution":{"main":[{"id":"b1","t":"loop","n":4,"body":[{"id":"b2","t":"cmd","c":"maju"}]},
{"id":"b3","t":"cmd","c":"kiri"},
{"id":"b4","t":"loop","n":2,"body":[{"id":"b5","t":"cmd","c":"maju"}]},
{"id":"b6","t":"cmd","c":"kiri"},
{"id":"b7","t":"loop","n":4,"body":[{"id":"b8","t":"cmd","c":"maju"}]},
{"id":"b9","t":"cmd","c":"kanan"},
{"id":"b10","t":"loop","n":2,"body":[{"id":"b11","t":"cmd","c":"maju"}]},
{"id":"b12","t":"cmd","c":"kanan"},
{"id":"b13","t":"loop","n":4,"body":[{"id":"b14","t":"cmd","c":"maju"}]}],"jurus":[]}},
{"id":"u60","theme":"salju","dir":1,"blocks":["maju","kiri","kanan"],"map":["S.....","#~~~#.","......",".#~~##",".....G"],"hint":"Jalannya berkelok seperti ular. Setiap bagian lurus pakai ulangi.","palette":["maju","kiri","kanan","ulangi"],"best":14,"limit":15,"tip":"ulangi 5 kali [maju], belok kanan, ulangi 2 kali [maju], belok kanan, ulangi 5 kali [maju], belok kiri, ulangi 2 kali [maju], belok kiri, ulangi 5 kali [maju]","solution":{"main":[{"id":"b1","t":"loop","n":5,"body":[{"id":"b2","t":"cmd","c":"maju"}]},
{"id":"b3","t":"cmd","c":"kanan"},
{"id":"b4","t":"loop","n":2,"body":[{"id":"b5","t":"cmd","c":"maju"}]},
{"id":"b6","t":"cmd","c":"kanan"},
{"id":"b7","t":"loop","n":5,"body":[{"id":"b8","t":"cmd","c":"maju"}]},
{"id":"b9","t":"cmd","c":"kiri"},
{"id":"b10","t":"loop","n":2,"body":[{"id":"b11","t":"cmd","c":"maju"}]},
{"id":"b12","t":"cmd","c":"kiri"},
{"id":"b13","t":"loop","n":5,"body":[{"id":"b14","t":"cmd","c":"maju"}]}],"jurus":[]}},
{"id":"u61","theme":"gurun","dir":2,"blocks":["maju","kiri","kanan"],"map":["#S..","~..#","..#.","...#","##..","..#G",".#.."],"hint":"Pecah jalannya jadi bagian-bagian. Bagian yang berulang pakai ulangi.","palette":["maju","kiri","kanan","ulangi"],"best":8,"limit":9,"tip":"ulangi 3 kali [maju], belok kiri, ulangi 2 kali [maju, belok kanan, maju, belok kiri]","solution":{"main":[{"id":"b1","t":"loop","n":3,"body":[{"id":"b2","t":"cmd","c":"maju"}]},
{"id":"b3","t":"cmd","c":"kiri"},
{"id":"b4","t":"loop","n":2,"body":[{"id":"b5","t":"cmd","c":"maju"},
{"id":"b6","t":"cmd","c":"kanan"},
{"id":"b7","t":"cmd","c":"maju"},
{"id":"b8","t":"cmd","c":"kiri"}]}],"jurus":[]}},
{"id":"u62","theme":"gurun","dir":0,"blocks":["maju","kiri","kanan"],"map":["...#G","..#..",".#..#","...##",".....",".....",".S.##"],"hint":"Pecah jalannya jadi bagian-bagian. Bagian yang berulang pakai ulangi.","palette":["maju","kiri","kanan","ulangi"],"best":8,"limit":9,"tip":"ulangi 3 kali [maju], belok kanan, ulangi 3 kali [maju, belok kiri, maju, belok kanan]","solution":{"main":[{"id":"b1","t":"loop","n":3,"body":[{"id":"b2","t":"cmd","c":"maju"}]},
{"id":"b3","t":"cmd","c":"kanan"},
{"id":"b4","t":"loop","n":3,"body":[{"id":"b5","t":"cmd","c":"maju"},
{"id":"b6","t":"cmd","c":"kiri"},
{"id":"b7","t":"cmd","c":"maju"},
{"id":"b8","t":"cmd","c":"kanan"}]}],"jurus":[]}},
{"id":"u63","theme":"gurun","dir":3,"blocks":["maju","kiri","kanan"],"map":[".G.#~.~.",".#......","#.#....S","..#...#."],"hint":"Pecah jalannya jadi bagian-bagian. Bagian yang berulang pakai ulangi.","palette":["maju","kiri","kanan","ulangi"],"best":8,"limit":9,"tip":"ulangi 4 kali [maju], belok kanan, ulangi 2 kali [maju, belok kiri, maju, belok kanan]","solution":{"main":[{"id":"b1","t":"loop","n":4,"body":[{"id":"b2","t":"cmd","c":"maju"}]},
{"id":"b3","t":"cmd","c":"kanan"},
{"id":"b4","t":"loop","n":2,"body":[{"id":"b5","t":"cmd","c":"maju"},
{"id":"b6","t":"cmd","c":"kiri"},
{"id":"b7","t":"cmd","c":"maju"},
{"id":"b8","t":"cmd","c":"kanan"}]}],"jurus":[]}},
{"id":"u64","theme":"gurun","dir":1,"blocks":["maju","kiri","kanan"],"map":["...#.#.G","#.#.#..#","...#..~.","S....~.."],"hint":"Pecah jalannya jadi bagian-bagian. Bagian yang berulang pakai ulangi.","palette":["maju","kiri","kanan","ulangi"],"best":8,"limit":9,"tip":"ulangi 4 kali [maju], belok kiri, ulangi 3 kali [maju, belok kanan, maju, belok kiri]","solution":{"main":[{"id":"b1","t":"loop","n":4,"body":[{"id":"b2","t":"cmd","c":"maju"}]},
{"id":"b3","t":"cmd","c":"kiri"},
{"id":"b4","t":"loop","n":3,"body":[{"id":"b5","t":"cmd","c":"maju"},
{"id":"b6","t":"cmd","c":"kanan"},
{"id":"b7","t":"cmd","c":"maju"},
{"id":"b8","t":"cmd","c":"kiri"}]}],"jurus":[]}},
{"id":"u65","theme":"gurun","dir":3,"blocks":["maju","kiri","kanan"],"map":["..#.....S","##..#.#..","#..#..#..","G.~#.#...","......#.."],"hint":"Pecah jalannya jadi bagian-bagian. Bagian yang berulang pakai ulangi.","palette":["maju","kiri","kanan","ulangi"],"best":8,"limit":9,"tip":"ulangi 5 kali [maju], belok kiri, ulangi 3 kali [maju, belok kanan, maju, belok kiri]","solution":{"main":[{"id":"b1","t":"loop","n":5,"body":[{"id":"b2","t":"cmd","c":"maju"}]},
{"id":"b3","t":"cmd","c":"kiri"},
{"id":"b4","t":"loop","n":3,"body":[{"id":"b5","t":"cmd","c":"maju"},
{"id":"b6","t":"cmd","c":"kanan"},
{"id":"b7","t":"cmd","c":"maju"},
{"id":"b8","t":"cmd","c":"kiri"}]}],"jurus":[]}},
{"id":"u66","theme":"gurun","dir":2,"blocks":["maju","kiri","kanan"],"map":["...S","##..","....",".#..","...#","#G#~"],"hint":"Pecah jalannya jadi bagian-bagian. Bagian yang berulang pakai ulangi.","palette":["maju","kiri","kanan","ulangi"],"best":8,"limit":9,"tip":"ulangi 3 kali [maju], belok kanan, ulangi 2 kali [maju, belok kiri, maju, belok kanan]","solution":{"main":[{"id":"b1","t":"loop","n":3,"body":[{"id":"b2","t":"cmd","c":"maju"}]},
{"id":"b3","t":"cmd","c":"kanan"},
{"id":"b4","t":"loop","n":2,"body":[{"id":"b5","t":"cmd","c":"maju"},
{"id":"b6","t":"cmd","c":"kiri"},
{"id":"b7","t":"cmd","c":"maju"},
{"id":"b8","t":"cmd","c":"kanan"}]}],"jurus":[]}},
{"id":"u67","theme":"gurun","dir":1,"blocks":["maju","kiri","kanan"],"map":["##~####.G",".....~..#","...#...##",".S....###"],"hint":"Pecah jalannya jadi bagian-bagian. Bagian yang berulang pakai ulangi.","palette":["maju","kiri","kanan","ulangi"],"best":8,"limit":9,"tip":"ulangi 4 kali [maju], belok kiri, ulangi 3 kali [maju, belok kanan, maju, belok kiri]","solution":{"main":[{"id":"b1","t":"loop","n":4,"body":[{"id":"b2","t":"cmd","c":"maju"}]},
{"id":"b3","t":"cmd","c":"kiri"},
{"id":"b4","t":"loop","n":3,"body":[{"id":"b5","t":"cmd","c":"maju"},
{"id":"b6","t":"cmd","c":"kanan"},
{"id":"b7","t":"cmd","c":"maju"},
{"id":"b8","t":"cmd","c":"kiri"}]}],"jurus":[]}},
{"id":"u68","theme":"gurun","dir":3,"blocks":["maju","kiri","kanan"],"map":[".##....S.","#~.......","#..###.#.","G.#...#.."],"hint":"Pecah jalannya jadi bagian-bagian. Bagian yang berulang pakai ulangi.","palette":["maju","kiri","kanan","ulangi"],"best":8,"limit":9,"tip":"ulangi 4 kali [maju], belok kiri, ulangi 3 kali [maju, belok kanan, maju, belok kiri]","solution":{"main":[{"id":"b1","t":"loop","n":4,"body":[{"id":"b2","t":"cmd","c":"maju"}]},
{"id":"b3","t":"cmd","c":"kiri"},
{"id":"b4","t":"loop","n":3,"body":[{"id":"b5","t":"cmd","c":"maju"},
{"id":"b6","t":"cmd","c":"kanan"},
{"id":"b7","t":"cmd","c":"maju"},
{"id":"b8","t":"cmd","c":"kiri"}]}],"jurus":[]}},
{"id":"u69","theme":"gurun","dir":3,"blocks":["maju","kiri","kanan"],"map":["G.##.....","~..~~#~..",".#...~...","##~.....S"],"hint":"Pecah jalannya jadi bagian-bagian. Bagian yang berulang pakai ulangi.","palette":["maju","kiri","kanan","ulangi"],"best":8,"limit":9,"tip":"ulangi 5 kali [maju], belok kanan, ulangi 3 kali [maju, belok kiri, maju, belok kanan]","solution":{"main":[{"id":"b1","t":"loop","n":5,"body":[{"id":"b2","t":"cmd","c":"maju"}]},
{"id":"b3","t":"cmd","c":"kanan"},
{"id":"b4","t":"loop","n":3,"body":[{"id":"b5","t":"cmd","c":"maju"},
{"id":"b6","t":"cmd","c":"kiri"},
{"id":"b7","t":"cmd","c":"maju"},
{"id":"b8","t":"cmd","c":"kanan"}]}],"jurus":[]}},
{"id":"u70","theme":"gurun","dir":3,"blocks":["maju","kiri","kanan"],"map":["G.#..##..","~..#.#...",".#..#....","~.#....#.",".#.~....S","#....#..."],"hint":"Pecah jalannya jadi bagian-bagian. Bagian yang berulang pakai ulangi.","palette":["maju","kiri","kanan","ulangi"],"best":8,"limit":9,"tip":"ulangi 4 kali [maju], belok kanan, ulangi 4 kali [maju, belok kiri, maju, belok kanan]","solution":{"main":[{"id":"b1","t":"loop","n":4,"body":[{"id":"b2","t":"cmd","c":"maju"}]},
{"id":"b3","t":"cmd","c":"kanan"},
{"id":"b4","t":"loop","n":4,"body":[{"id":"b5","t":"cmd","c":"maju"},
{"id":"b6","t":"cmd","c":"kiri"},
{"id":"b7","t":"cmd","c":"maju"},
{"id":"b8","t":"cmd","c":"kanan"}]}],"jurus":[]}},
{"id":"u71","theme":"laut","dir":1,"blocks":["maju","kiri","kanan"],"map":["......","....#.","#S..#G"],"hint":"Dua kelompok gerakan berulang. Butuh dua blok ulangi.","palette":["maju","kiri","kanan","ulangi"],"best":9,"limit":10,"tip":"ulangi 2 kali [maju], belok kiri, ulangi 2 kali [maju 2×, belok kanan], ulangi 2 kali [maju]","solution":{"main":[{"id":"b1","t":"loop","n":2,"body":[{"id":"b2","t":"cmd","c":"maju"}]},
{"id":"b3","t":"cmd","c":"kiri"},
{"id":"b4","t":"loop","n":2,"body":[{"id":"b5","t":"cmd","c":"maju"},
{"id":"b6","t":"cmd","c":"maju"},
{"id":"b7","t":"cmd","c":"kanan"}]},
{"id":"b8","t":"loop","n":2,"body":[{"id":"b9","t":"cmd","c":"maju"}]}],"jurus":[]}},
{"id":"u72","theme":"laut","dir":2,"blocks":["maju","kiri","kanan"],"map":[".S..","#...","#...",".#~.","G..."],"hint":"Dua kelompok gerakan berulang. Butuh dua blok ulangi.","palette":["maju","kiri","kanan","ulangi"],"best":9,"limit":10,"tip":"ulangi 2 kali [maju], belok kiri, ulangi 2 kali [maju 2×, belok kanan], ulangi 3 kali [maju]","solution":{"main":[{"id":"b1","t":"loop","n":2,"body":[{"id":"b2","t":"cmd","c":"maju"}]},
{"id":"b3","t":"cmd","c":"kiri"},
{"id":"b4","t":"loop","n":2,"body":[{"id":"b5","t":"cmd","c":"maju"},
{"id":"b6","t":"cmd","c":"maju"},
{"id":"b7","t":"cmd","c":"kanan"}]},
{"id":"b8","t":"loop","n":3,"body":[{"id":"b9","t":"cmd","c":"maju"}]}],"jurus":[]}},
{"id":"u73","theme":"laut","dir":1,"blocks":["maju","kiri","kanan"],"map":[".##...#",".......","#.~.~..","S...~G."],"hint":"Dua kelompok gerakan berulang. Butuh dua blok ulangi.","palette":["maju","kiri","kanan","ulangi"],"best":9,"limit":10,"tip":"ulangi 3 kali [maju], belok kiri, ulangi 2 kali [maju 2×, belok kanan], ulangi 2 kali [maju]","solution":{"main":[{"id":"b1","t":"loop","n":3,"body":[{"id":"b2","t":"cmd","c":"maju"}]},
{"id":"b3","t":"cmd","c":"kiri"},
{"id":"b4","t":"loop","n":2,"body":[{"id":"b5","t":"cmd","c":"maju"},
{"id":"b6","t":"cmd","c":"maju"},
{"id":"b7","t":"cmd","c":"kanan"}]},
{"id":"b8","t":"loop","n":2,"body":[{"id":"b9","t":"cmd","c":"maju"}]}],"jurus":[]}},
{"id":"u74","theme":"laut","dir":3,"blocks":["maju","kiri","kanan"],"map":["G.~.~.",".#...S",".#.~.#","......"],"hint":"Dua kelompok gerakan berulang. Butuh dua blok ulangi.","palette":["maju","kiri","kanan","ulangi"],"best":9,"limit":10,"tip":"ulangi 3 kali [maju], belok kiri, ulangi 2 kali [maju 2×, belok kanan], ulangi 3 kali [maju]","solution":{"main":[{"id":"b1","t":"loop","n":3,"body":[{"id":"b2","t":"cmd","c":"maju"}]},
{"id":"b3","t":"cmd","c":"kiri"},
{"id":"b4","t":"loop","n":2,"body":[{"id":"b5","t":"cmd","c":"maju"},
{"id":"b6","t":"cmd","c":"maju"},
{"id":"b7","t":"cmd","c":"kanan"}]},
{"id":"b8","t":"loop","n":3,"body":[{"id":"b9","t":"cmd","c":"maju"}]}],"jurus":[]}},
{"id":"u75","theme":"laut","dir":0,"blocks":["maju","kiri","kanan"],"map":["....G#",".~#~#.","....#~","#~....","#.S..."],"hint":"Dua kelompok gerakan berulang. Butuh dua blok ulangi.","palette":["maju","kiri","kanan","ulangi"],"best":9,"limit":10,"tip":"ulangi 2 kali [maju], belok kiri, ulangi 2 kali [maju 2×, belok kanan], ulangi 4 kali [maju]","solution":{"main":[{"id":"b1","t":"loop","n":2,"body":[{"id":"b2","t":"cmd","c":"maju"}]},
{"id":"b3","t":"cmd","c":"kiri"},
{"id":"b4","t":"loop","n":2,"body":[{"id":"b5","t":"cmd","c":"maju"},
{"id":"b6","t":"cmd","c":"maju"},
{"id":"b7","t":"cmd","c":"kanan"}]},
{"id":"b8","t":"loop","n":4,"body":[{"id":"b9","t":"cmd","c":"maju"}]}],"jurus":[]}},
{"id":"u76","theme":"laut","dir":3,"blocks":["maju","kiri","kanan"],"map":[".G.#...","..#...S","#.#....","~.....~"],"hint":"Dua kelompok gerakan berulang. Butuh dua blok ulangi.","palette":["maju","kiri","kanan","ulangi"],"best":9,"limit":10,"tip":"ulangi 3 kali [maju], belok kiri, ulangi 2 kali [maju 2×, belok kanan], ulangi 3 kali [maju]","solution":{"main":[{"id":"b1","t":"loop","n":3,"body":[{"id":"b2","t":"cmd","c":"maju"}]},
{"id":"b3","t":"cmd","c":"kiri"},
{"id":"b4","t":"loop","n":2,"body":[{"id":"b5","t":"cmd","c":"maju"},
{"id":"b6","t":"cmd","c":"maju"},
{"id":"b7","t":"cmd","c":"kanan"}]},
{"id":"b8","t":"loop","n":3,"body":[{"id":"b9","t":"cmd","c":"maju"}]}],"jurus":[]}},
{"id":"u77","theme":"laut","dir":1,"blocks":["maju","kiri","kanan"],"map":["....#G.","....~..","S...~..","..#.~..",".#....."],"hint":"Dua kelompok gerakan berulang. Butuh dua blok ulangi.","palette":["maju","kiri","kanan","ulangi"],"best":9,"limit":10,"tip":"ulangi 3 kali [maju], belok kanan, ulangi 2 kali [maju 2×, belok kiri], ulangi 4 kali [maju]","solution":{"main":[{"id":"b1","t":"loop","n":3,"body":[{"id":"b2","t":"cmd","c":"maju"}]},
{"id":"b3","t":"cmd","c":"kanan"},
{"id":"b4","t":"loop","n":2,"body":[{"id":"b5","t":"cmd","c":"maju"},
{"id":"b6","t":"cmd","c":"maju"},
{"id":"b7","t":"cmd","c":"kiri"}]},
{"id":"b8","t":"loop","n":4,"body":[{"id":"b9","t":"cmd","c":"maju"}]}],"jurus":[]}},
{"id":"u78","theme":"laut","dir":2,"blocks":["maju","kiri","kanan"],"map":["#.S.","....","#...","...~","...#",".##.","...G"],"hint":"Dua kelompok gerakan berulang. Butuh dua blok ulangi.","palette":["maju","kiri","kanan","ulangi"],"best":9,"limit":10,"tip":"ulangi 4 kali [maju], belok kanan, ulangi 2 kali [maju 2×, belok kiri], ulangi 3 kali [maju]","solution":{"main":[{"id":"b1","t":"loop","n":4,"body":[{"id":"b2","t":"cmd","c":"maju"}]},
{"id":"b3","t":"cmd","c":"kanan"},
{"id":"b4","t":"loop","n":2,"body":[{"id":"b5","t":"cmd","c":"maju"},
{"id":"b6","t":"cmd","c":"maju"},
{"id":"b7","t":"cmd","c":"kiri"}]},
{"id":"b8","t":"loop","n":3,"body":[{"id":"b9","t":"cmd","c":"maju"}]}],"jurus":[]}},
{"id":"u79","theme":"laut","dir":1,"blocks":["maju","kiri","kanan"],"map":["#......","...~.~.","S....#.","....#..",".#.~..G"],"hint":"Dua kelompok gerakan berulang. Butuh dua blok ulangi.","palette":["maju","kiri","kanan","ulangi"],"best":9,"limit":10,"tip":"ulangi 4 kali [maju], belok kiri, ulangi 2 kali [maju 2×, belok kanan], ulangi 4 kali [maju]","solution":{"main":[{"id":"b1","t":"loop","n":4,"body":[{"id":"b2","t":"cmd","c":"maju"}]},
{"id":"b3","t":"cmd","c":"kiri"},
{"id":"b4","t":"loop","n":2,"body":[{"id":"b5","t":"cmd","c":"maju"},
{"id":"b6","t":"cmd","c":"maju"},
{"id":"b7","t":"cmd","c":"kanan"}]},
{"id":"b8","t":"loop","n":4,"body":[{"id":"b9","t":"cmd","c":"maju"}]}],"jurus":[]}},
{"id":"u80","theme":"laut","dir":3,"blocks":["maju","kiri","kanan"],"map":[".~...#.","G~...#.",".#.~.#.",".~....#",".#....S",".#.#..~","......."],"hint":"Dua kelompok gerakan berulang. Butuh dua blok ulangi.","palette":["maju","kiri","kanan","ulangi"],"best":9,"limit":10,"tip":"ulangi 4 kali [maju], belok kiri, ulangi 2 kali [maju 2×, belok kanan], ulangi 5 kali [maju]","solution":{"main":[{"id":"b1","t":"loop","n":4,"body":[{"id":"b2","t":"cmd","c":"maju"}]},
{"id":"b3","t":"cmd","c":"kiri"},
{"id":"b4","t":"loop","n":2,"body":[{"id":"b5","t":"cmd","c":"maju"},
{"id":"b6","t":"cmd","c":"maju"},
{"id":"b7","t":"cmd","c":"kanan"}]},
{"id":"b8","t":"loop","n":5,"body":[{"id":"b9","t":"cmd","c":"maju"}]}],"jurus":[]}},
{"id":"u81","theme":"gunung","dir":3,"blocks":["maju","kiri","kanan"],"map":["#~...S.","...~...","G.#...."],"hint":"Tangganya bertingkat dua. Satu anak tangga = maju 2, belok, maju, belok.","palette":["maju","kiri","kanan","ulangi"],"best":8,"limit":9,"tip":"ulangi 1 kali [maju], ulangi 2 kali [maju 2×, belok kiri, maju, belok kanan]","solution":{"main":[{"id":"b1","t":"loop","n":1,"body":[{"id":"b2","t":"cmd","c":"maju"}]},
{"id":"b3","t":"loop","n":2,"body":[{"id":"b4","t":"cmd","c":"maju"},
{"id":"b5","t":"cmd","c":"maju"},
{"id":"b6","t":"cmd","c":"kiri"},
{"id":"b7","t":"cmd","c":"maju"},
{"id":"b8","t":"cmd","c":"kanan"}]}],"jurus":[]}},
{"id":"u82","theme":"gunung","dir":1,"blocks":["maju","kiri","kanan"],"map":[".....~G#","........","S....#.."],"hint":"Tangganya bertingkat dua. Satu anak tangga = maju 2, belok, maju, belok.","palette":["maju","kiri","kanan","ulangi"],"best":8,"limit":9,"tip":"ulangi 2 kali [maju], ulangi 2 kali [maju 2×, belok kiri, maju, belok kanan]","solution":{"main":[{"id":"b1","t":"loop","n":2,"body":[{"id":"b2","t":"cmd","c":"maju"}]},
{"id":"b3","t":"loop","n":2,"body":[{"id":"b4","t":"cmd","c":"maju"},
{"id":"b5","t":"cmd","c":"maju"},
{"id":"b6","t":"cmd","c":"kiri"},
{"id":"b7","t":"cmd","c":"maju"},
{"id":"b8","t":"cmd","c":"kanan"}]}],"jurus":[]}},
{"id":"u83","theme":"gunung","dir":1,"blocks":["maju","kiri","kanan"],"map":["...~....","S...##..",".......#","~~..~...",".#..~.~G"],"hint":"Tangganya bertingkat dua. Satu anak tangga = maju 2, belok, maju, belok.","palette":["maju","kiri","kanan","ulangi"],"best":8,"limit":9,"tip":"ulangi 1 kali [maju], ulangi 3 kali [maju 2×, belok kanan, maju, belok kiri]","solution":{"main":[{"id":"b1","t":"loop","n":1,"body":[{"id":"b2","t":"cmd","c":"maju"}]},
{"id":"b3","t":"loop","n":3,"body":[{"id":"b4","t":"cmd","c":"maju"},
{"id":"b5","t":"cmd","c":"maju"},
{"id":"b6","t":"cmd","c":"kanan"},
{"id":"b7","t":"cmd","c":"maju"},
{"id":"b8","t":"cmd","c":"kiri"}]}],"jurus":[]}},
{"id":"u84","theme":"gunung","dir":3,"blocks":["maju","kiri","kanan"],"map":["G.~......","....#....","~~....~..","...~....S"],"hint":"Tangganya bertingkat dua. Satu anak tangga = maju 2, belok, maju, belok.","palette":["maju","kiri","kanan","ulangi"],"best":8,"limit":9,"tip":"ulangi 2 kali [maju], ulangi 3 kali [maju 2×, belok kanan, maju, belok kiri]","solution":{"main":[{"id":"b1","t":"loop","n":2,"body":[{"id":"b2","t":"cmd","c":"maju"}]},
{"id":"b3","t":"loop","n":3,"body":[{"id":"b4","t":"cmd","c":"maju"},
{"id":"b5","t":"cmd","c":"maju"},
{"id":"b6","t":"cmd","c":"kanan"},
{"id":"b7","t":"cmd","c":"maju"},
{"id":"b8","t":"cmd","c":"kiri"}]}],"jurus":[]}},
{"id":"u85","theme":"gunung","dir":3,"blocks":["maju","kiri","kanan"],"map":["...~....S",".~.......","...#.#~..","G.#~.##.."],"hint":"Tangganya bertingkat dua. Satu anak tangga = maju 2, belok, maju, belok.","palette":["maju","kiri","kanan","ulangi"],"best":8,"limit":9,"tip":"ulangi 2 kali [maju], ulangi 3 kali [maju 2×, belok kiri, maju, belok kanan]","solution":{"main":[{"id":"b1","t":"loop","n":2,"body":[{"id":"b2","t":"cmd","c":"maju"}]},
{"id":"b3","t":"loop","n":3,"body":[{"id":"b4","t":"cmd","c":"maju"},
{"id":"b5","t":"cmd","c":"maju"},
{"id":"b6","t":"cmd","c":"kiri"},
{"id":"b7","t":"cmd","c":"maju"},
{"id":"b8","t":"cmd","c":"kanan"}]}],"jurus":[]}},
{"id":"u86","theme":"gunung","dir":3,"blocks":["maju","kiri","kanan"],"map":["G#.#~.~..","....#.##.","~....~~~.","~~~#....S","....#...."],"hint":"Tangganya bertingkat dua. Satu anak tangga = maju 2, belok, maju, belok.","palette":["maju","kiri","kanan","ulangi"],"best":8,"limit":9,"tip":"ulangi 2 kali [maju], ulangi 3 kali [maju 2×, belok kanan, maju, belok kiri]","solution":{"main":[{"id":"b1","t":"loop","n":2,"body":[{"id":"b2","t":"cmd","c":"maju"}]},
{"id":"b3","t":"loop","n":3,"body":[{"id":"b4","t":"cmd","c":"maju"},
{"id":"b5","t":"cmd","c":"maju"},
{"id":"b6","t":"cmd","c":"kanan"},
{"id":"b7","t":"cmd","c":"maju"},
{"id":"b8","t":"cmd","c":"kiri"}]}],"jurus":[]}},
{"id":"u87","theme":"gunung","dir":1,"blocks":["maju","kiri","kanan"],"map":["S...~...~",".~#...~~.","...~....#",".....~~..","..#~.~.~.","......~.G","...~~...."],"hint":"Tangganya bertingkat dua. Satu anak tangga = maju 2, belok, maju, belok.","palette":["maju","kiri","kanan","ulangi"],"best":12,"limit":13,"tip":"ulangi 1 kali [maju], ulangi 3 kali [maju 2×, belok kanan, maju, belok kiri], maju, belok kanan, ulangi 2 kali [maju]","solution":{"main":[{"id":"b1","t":"loop","n":1,"body":[{"id":"b2","t":"cmd","c":"maju"}]},
{"id":"b3","t":"loop","n":3,"body":[{"id":"b4","t":"cmd","c":"maju"},
{"id":"b5","t":"cmd","c":"maju"},
{"id":"b6","t":"cmd","c":"kanan"},
{"id":"b7","t":"cmd","c":"maju"},
{"id":"b8","t":"cmd","c":"kiri"}]},
{"id":"b9","t":"cmd","c":"maju"},
{"id":"b10","t":"cmd","c":"kanan"},
{"id":"b11","t":"loop","n":2,"body":[{"id":"b12","t":"cmd","c":"maju"}]}],"jurus":[]}},
{"id":"u88","theme":"gunung","dir":1,"blocks":["maju","kiri","kanan"],"map":[".~.#..##G","..#....#.","~.~~.#~..","....#...~",".~....~~.","S....~..."],"hint":"Tangganya bertingkat dua. Satu anak tangga = maju 2, belok, maju, belok.","palette":["maju","kiri","kanan","ulangi"],"best":12,"limit":13,"tip":"ulangi 1 kali [maju], ulangi 3 kali [maju 2×, belok kiri, maju, belok kanan], maju, belok kiri, ulangi 2 kali [maju]","solution":{"main":[{"id":"b1","t":"loop","n":1,"body":[{"id":"b2","t":"cmd","c":"maju"}]},
{"id":"b3","t":"loop","n":3,"body":[{"id":"b4","t":"cmd","c":"maju"},
{"id":"b5","t":"cmd","c":"maju"},
{"id":"b6","t":"cmd","c":"kiri"},
{"id":"b7","t":"cmd","c":"maju"},
{"id":"b8","t":"cmd","c":"kanan"}]},
{"id":"b9","t":"cmd","c":"maju"},
{"id":"b10","t":"cmd","c":"kiri"},
{"id":"b11","t":"loop","n":2,"body":[{"id":"b12","t":"cmd","c":"maju"}]}],"jurus":[]}},
{"id":"u89","theme":"gunung","dir":3,"blocks":["maju","kiri","kanan"],"map":["G#.#.#~..",".~.#~...#","..##...#.","...#.#~##","~...~....","..#......","..~.#...S"],"hint":"Tangganya bertingkat dua. Satu anak tangga = maju 2, belok, maju, belok.","palette":["maju","kiri","kanan","ulangi"],"best":12,"limit":13,"tip":"ulangi 1 kali [maju], ulangi 3 kali [maju 2×, belok kanan, maju, belok kiri], maju, belok kanan, ulangi 3 kali [maju]","solution":{"main":[{"id":"b1","t":"loop","n":1,"body":[{"id":"b2","t":"cmd","c":"maju"}]},
{"id":"b3","t":"loop","n":3,"body":[{"id":"b4","t":"cmd","c":"maju"},
{"id":"b5","t":"cmd","c":"maju"},
{"id":"b6","t":"cmd","c":"kanan"},
{"id":"b7","t":"cmd","c":"maju"},
{"id":"b8","t":"cmd","c":"kiri"}]},
{"id":"b9","t":"cmd","c":"maju"},
{"id":"b10","t":"cmd","c":"kanan"},
{"id":"b11","t":"loop","n":3,"body":[{"id":"b12","t":"cmd","c":"maju"}]}],"jurus":[]}},
{"id":"u90","theme":"gunung","dir":1,"blocks":["maju","kiri","kanan"],"map":["S...~.~..","~......#~","~~..~...~","~....~#..","...~~~#~.","~##.~#...","...~..#.G"],"hint":"Tangganya bertingkat dua. Satu anak tangga = maju 2, belok, maju, belok.","palette":["maju","kiri","kanan","ulangi"],"best":12,"limit":13,"tip":"ulangi 1 kali [maju], ulangi 3 kali [maju 2×, belok kanan, maju, belok kiri], maju, belok kanan, ulangi 3 kali [maju]","solution":{"main":[{"id":"b1","t":"loop","n":1,"body":[{"id":"b2","t":"cmd","c":"maju"}]},
{"id":"b3","t":"loop","n":3,"body":[{"id":"b4","t":"cmd","c":"maju"},
{"id":"b5","t":"cmd","c":"maju"},
{"id":"b6","t":"cmd","c":"kanan"},
{"id":"b7","t":"cmd","c":"maju"},
{"id":"b8","t":"cmd","c":"kiri"}]},
{"id":"b9","t":"cmd","c":"maju"},
{"id":"b10","t":"cmd","c":"kanan"},
{"id":"b11","t":"loop","n":3,"body":[{"id":"b12","t":"cmd","c":"maju"}]}],"jurus":[]}},
{"id":"u91","theme":"bulan","dir":1,"blocks":["maju","kiri","kanan"],"map":["~..G..","..#.#.",".#.#..","##...~",".S..#.","...#.."],"hint":"Soal terakhir Ulangi! Cari semua bagian yang berulang.","palette":["maju","kiri","kanan","ulangi"],"best":13,"limit":14,"tip":"ulangi 2 kali [maju], belok kiri, ulangi 2 kali [maju, belok kanan, maju, belok kiri], ulangi 2 kali [maju], belok kiri, ulangi 2 kali [maju]","solution":{"main":[{"id":"b1","t":"loop","n":2,"body":[{"id":"b2","t":"cmd","c":"maju"}]},
{"id":"b3","t":"cmd","c":"kiri"},
{"id":"b4","t":"loop","n":2,"body":[{"id":"b5","t":"cmd","c":"maju"},
{"id":"b6","t":"cmd","c":"kanan"},
{"id":"b7","t":"cmd","c":"maju"},
{"id":"b8","t":"cmd","c":"kiri"}]},
{"id":"b9","t":"loop","n":2,"body":[{"id":"b10","t":"cmd","c":"maju"}]},
{"id":"b11","t":"cmd","c":"kiri"},
{"id":"b12","t":"loop","n":2,"body":[{"id":"b13","t":"cmd","c":"maju"}]}],"jurus":[]}},
{"id":"u92","theme":"bulan","dir":1,"blocks":["maju","kiri","kanan"],"map":["....G..",".~...#.","#.###..","..#...#","#S...##"],"hint":"Soal terakhir Ulangi! Cari semua bagian yang berulang.","palette":["maju","kiri","kanan","ulangi"],"best":13,"limit":14,"tip":"ulangi 3 kali [maju], belok kiri, ulangi 2 kali [maju, belok kanan, maju, belok kiri], ulangi 2 kali [maju], belok kiri, ulangi 2 kali [maju]","solution":{"main":[{"id":"b1","t":"loop","n":3,"body":[{"id":"b2","t":"cmd","c":"maju"}]},
{"id":"b3","t":"cmd","c":"kiri"},
{"id":"b4","t":"loop","n":2,"body":[{"id":"b5","t":"cmd","c":"maju"},
{"id":"b6","t":"cmd","c":"kanan"},
{"id":"b7","t":"cmd","c":"maju"},
{"id":"b8","t":"cmd","c":"kiri"}]},
{"id":"b9","t":"loop","n":2,"body":[{"id":"b10","t":"cmd","c":"maju"}]},
{"id":"b11","t":"cmd","c":"kiri"},
{"id":"b12","t":"loop","n":2,"body":[{"id":"b13","t":"cmd","c":"maju"}]}],"jurus":[]}},
{"id":"u93","theme":"bulan","dir":0,"blocks":["maju","kiri","kanan"],"map":[".~..#.","...#.~",".~..#.","G#~..#","..~#..",".~#.#.","~.#.#S"],"hint":"Soal terakhir Ulangi! Cari semua bagian yang berulang.","palette":["maju","kiri","kanan","ulangi"],"best":13,"limit":14,"tip":"ulangi 2 kali [maju], belok kiri, ulangi 3 kali [maju, belok kanan, maju, belok kiri], ulangi 2 kali [maju], belok kiri, ulangi 2 kali [maju]","solution":{"main":[{"id":"b1","t":"loop","n":2,"body":[{"id":"b2","t":"cmd","c":"maju"}]},
{"id":"b3","t":"cmd","c":"kiri"},
{"id":"b4","t":"loop","n":3,"body":[{"id":"b5","t":"cmd","c":"maju"},
{"id":"b6","t":"cmd","c":"kanan"},
{"id":"b7","t":"cmd","c":"maju"},
{"id":"b8","t":"cmd","c":"kiri"}]},
{"id":"b9","t":"loop","n":2,"body":[{"id":"b10","t":"cmd","c":"maju"}]},
{"id":"b11","t":"cmd","c":"kiri"},
{"id":"b12","t":"loop","n":2,"body":[{"id":"b13","t":"cmd","c":"maju"}]}],"jurus":[]}},
{"id":"u94","theme":"bulan","dir":0,"blocks":["maju","kiri","kanan"],"map":["...#..",".~..~.","G##..#",".###..","~.##..","......",".....S"],"hint":"Soal terakhir Ulangi! Cari semua bagian yang berulang.","palette":["maju","kiri","kanan","ulangi"],"best":13,"limit":14,"tip":"ulangi 3 kali [maju], belok kiri, ulangi 3 kali [maju, belok kanan, maju, belok kiri], ulangi 2 kali [maju], belok kiri, ulangi 2 kali [maju]","solution":{"main":[{"id":"b1","t":"loop","n":3,"body":[{"id":"b2","t":"cmd","c":"maju"}]},
{"id":"b3","t":"cmd","c":"kiri"},
{"id":"b4","t":"loop","n":3,"body":[{"id":"b5","t":"cmd","c":"maju"},
{"id":"b6","t":"cmd","c":"kanan"},
{"id":"b7","t":"cmd","c":"maju"},
{"id":"b8","t":"cmd","c":"kiri"}]},
{"id":"b9","t":"loop","n":2,"body":[{"id":"b10","t":"cmd","c":"maju"}]},
{"id":"b11","t":"cmd","c":"kiri"},
{"id":"b12","t":"loop","n":2,"body":[{"id":"b13","t":"cmd","c":"maju"}]}],"jurus":[]}},
{"id":"u95","theme":"bulan","dir":0,"blocks":["maju","kiri","kanan"],"map":["..~...",".#..#.","#..##G","..#~..","..~...",".~#..#","S..#.."],"hint":"Soal terakhir Ulangi! Cari semua bagian yang berulang.","palette":["maju","kiri","kanan","ulangi"],"best":13,"limit":14,"tip":"ulangi 3 kali [maju], belok kanan, ulangi 3 kali [maju, belok kiri, maju, belok kanan], ulangi 2 kali [maju], belok kanan, ulangi 2 kali [maju]","solution":{"main":[{"id":"b1","t":"loop","n":3,"body":[{"id":"b2","t":"cmd","c":"maju"}]},
{"id":"b3","t":"cmd","c":"kanan"},
{"id":"b4","t":"loop","n":3,"body":[{"id":"b5","t":"cmd","c":"maju"},
{"id":"b6","t":"cmd","c":"kiri"},
{"id":"b7","t":"cmd","c":"maju"},
{"id":"b8","t":"cmd","c":"kanan"}]},
{"id":"b9","t":"loop","n":2,"body":[{"id":"b10","t":"cmd","c":"maju"}]},
{"id":"b11","t":"cmd","c":"kanan"},
{"id":"b12","t":"loop","n":2,"body":[{"id":"b13","t":"cmd","c":"maju"}]}],"jurus":[]}},
{"id":"u96","theme":"bulan","dir":1,"blocks":["maju","kiri","kanan"],"map":["...~.G..",".~.##.#.","#....##.","#....#..","..~.#..#","##....##","S....#.."],"hint":"Soal terakhir Ulangi! Cari semua bagian yang berulang.","palette":["maju","kiri","kanan","ulangi"],"best":13,"limit":14,"tip":"ulangi 4 kali [maju], belok kiri, ulangi 3 kali [maju, belok kanan, maju, belok kiri], ulangi 3 kali [maju], belok kiri, ulangi 2 kali [maju]","solution":{"main":[{"id":"b1","t":"loop","n":4,"body":[{"id":"b2","t":"cmd","c":"maju"}]},
{"id":"b3","t":"cmd","c":"kiri"},
{"id":"b4","t":"loop","n":3,"body":[{"id":"b5","t":"cmd","c":"maju"},
{"id":"b6","t":"cmd","c":"kanan"},
{"id":"b7","t":"cmd","c":"maju"},
{"id":"b8","t":"cmd","c":"kiri"}]},
{"id":"b9","t":"loop","n":3,"body":[{"id":"b10","t":"cmd","c":"maju"}]},
{"id":"b11","t":"cmd","c":"kiri"},
{"id":"b12","t":"loop","n":2,"body":[{"id":"b13","t":"cmd","c":"maju"}]}],"jurus":[]}},
{"id":"u97","theme":"bulan","dir":1,"blocks":["maju","kiri","kanan"],"map":[".S...#~#","..##..#.","~#.##..~",".....~..",".~..~#~.",".#......","..#.#G.."],"hint":"Soal terakhir Ulangi! Cari semua bagian yang berulang.","palette":["maju","kiri","kanan","ulangi"],"best":13,"limit":14,"tip":"ulangi 3 kali [maju], belok kanan, ulangi 3 kali [maju, belok kiri, maju, belok kanan], ulangi 3 kali [maju], belok kanan, ulangi 2 kali [maju]","solution":{"main":[{"id":"b1","t":"loop","n":3,"body":[{"id":"b2","t":"cmd","c":"maju"}]},
{"id":"b3","t":"cmd","c":"kanan"},
{"id":"b4","t":"loop","n":3,"body":[{"id":"b5","t":"cmd","c":"maju"},
{"id":"b6","t":"cmd","c":"kiri"},
{"id":"b7","t":"cmd","c":"maju"},
{"id":"b8","t":"cmd","c":"kanan"}]},
{"id":"b9","t":"loop","n":3,"body":[{"id":"b10","t":"cmd","c":"maju"}]},
{"id":"b11","t":"cmd","c":"kanan"},
{"id":"b12","t":"loop","n":2,"body":[{"id":"b13","t":"cmd","c":"maju"}]}],"jurus":[]}},
{"id":"u98","theme":"bulan","dir":1,"blocks":["maju","kiri","kanan"],"map":["#..#~G..","#.~..~#.",".....~#.","~....#..",".#..#..#","#..~..##","S....~~."],"hint":"Soal terakhir Ulangi! Cari semua bagian yang berulang.","palette":["maju","kiri","kanan","ulangi"],"best":13,"limit":14,"tip":"ulangi 4 kali [maju], belok kiri, ulangi 3 kali [maju, belok kanan, maju, belok kiri], ulangi 3 kali [maju], belok kiri, ulangi 2 kali [maju]","solution":{"main":[{"id":"b1","t":"loop","n":4,"body":[{"id":"b2","t":"cmd","c":"maju"}]},
{"id":"b3","t":"cmd","c":"kiri"},
{"id":"b4","t":"loop","n":3,"body":[{"id":"b5","t":"cmd","c":"maju"},
{"id":"b6","t":"cmd","c":"kanan"},
{"id":"b7","t":"cmd","c":"maju"},
{"id":"b8","t":"cmd","c":"kiri"}]},
{"id":"b9","t":"loop","n":3,"body":[{"id":"b10","t":"cmd","c":"maju"}]},
{"id":"b11","t":"cmd","c":"kiri"},
{"id":"b12","t":"loop","n":2,"body":[{"id":"b13","t":"cmd","c":"maju"}]}],"jurus":[]}},
{"id":"u99","theme":"bulan","dir":1,"blocks":["maju","kiri","kanan"],"map":["S....#.##","......#~#","..#.#..#.",".~...#...",".~..~~#..","...#..#..","..~..G..."],"hint":"Soal terakhir Ulangi! Cari semua bagian yang berulang.","palette":["maju","kiri","kanan","ulangi"],"best":13,"limit":14,"tip":"ulangi 4 kali [maju], belok kanan, ulangi 3 kali [maju, belok kiri, maju, belok kanan], ulangi 3 kali [maju], belok kanan, ulangi 2 kali [maju]","solution":{"main":[{"id":"b1","t":"loop","n":4,"body":[{"id":"b2","t":"cmd","c":"maju"}]},
{"id":"b3","t":"cmd","c":"kanan"},
{"id":"b4","t":"loop","n":3,"body":[{"id":"b5","t":"cmd","c":"maju"},
{"id":"b6","t":"cmd","c":"kiri"},
{"id":"b7","t":"cmd","c":"maju"},
{"id":"b8","t":"cmd","c":"kanan"}]},
{"id":"b9","t":"loop","n":3,"body":[{"id":"b10","t":"cmd","c":"maju"}]},
{"id":"b11","t":"cmd","c":"kanan"},
{"id":"b12","t":"loop","n":2,"body":[{"id":"b13","t":"cmd","c":"maju"}]}],"jurus":[]}},
{"id":"u100","theme":"bulan","dir":1,"blocks":["maju","kiri","kanan"],"map":[".#.#.G...",".....##.#","#.~##.~.#",".....#..~",".~..#..~.","####..###","S....##.."],"hint":"Soal terakhir Ulangi! Cari semua bagian yang berulang.","palette":["maju","kiri","kanan","ulangi"],"best":13,"limit":14,"tip":"ulangi 4 kali [maju], belok kiri, ulangi 3 kali [maju, belok kanan, maju, belok kiri], ulangi 3 kali [maju], belok kiri, ulangi 2 kali [maju]","solution":{"main":[{"id":"b1","t":"loop","n":4,"body":[{"id":"b2","t":"cmd","c":"maju"}]},
{"id":"b3","t":"cmd","c":"kiri"},
{"id":"b4","t":"loop","n":3,"body":[{"id":"b5","t":"cmd","c":"maju"},
{"id":"b6","t":"cmd","c":"kanan"},
{"id":"b7","t":"cmd","c":"maju"},
{"id":"b8","t":"cmd","c":"kiri"}]},
{"id":"b9","t":"loop","n":3,"body":[{"id":"b10","t":"cmd","c":"maju"}]},
{"id":"b11","t":"cmd","c":"kiri"},
{"id":"b12","t":"loop","n":2,"body":[{"id":"b13","t":"cmd","c":"maju"}]}],"jurus":[]}}];
