'use client';
import dynamic from 'next/dynamic';
import Link from 'next/link';
import { useCallback, useEffect, useMemo, useReducer, useRef, useState } from 'react';
import { Avatar, Icon, Switch } from '@/components/ui';
import { useMe, useRumila, useUI } from '@/lib/store';
import { initialState, reducer, searchable, visiblePart } from '@/lib/anatomy/state';
import { useAnatomySession } from '@/lib/anatomy/use-session';
import { LAYERS, REGIONS, SYSTEMS, type Manifest, type Part, type RegionId } from '@/lib/anatomy/types';
import type { ViewerHandle } from './viewer';
const Viewer=dynamic(()=>import('./viewer').then(m=>m.Viewer),{ssr:false,loading:()=> <div className="anatomy-loading" role="status">Membuka ruang 3D…</div>});
const QUESTIONS=[{id:'locate-heart',text:'Organ mana yang memompa darah ke seluruh tubuh?',answer:'heart',explanation:'Jantung menggerakkan darah melalui sirkulasi paru dan sirkulasi tubuh.'},{id:'locate-stomach',text:'Temukan organ yang mengaduk makanan sebelum masuk ke usus halus.',answer:'stomach',explanation:'Lambung mencampur makanan dengan cairan pencernaan.'},{id:'locate-kidney',text:'Pilih ginjal kiri dari sudut pandang tubuh model.',answer:'kidney_l',explanation:'Kiri mengikuti tubuh model. Saat model menghadap kita, sisi kirinya berada di kanan layar.'}];
export function Explorer({manifest,memberId}:{manifest:Manifest;memberId:string}){
 const me=useMe(),openSheet=useUI(s=>s.openSheet),activity=useRumila(s=>s.activity),complete=useRumila(s=>s.completeAnatomy);
 useAnatomySession(memberId);
 const [state,dispatch]=useReducer(reducer,undefined,()=>initialState());
 const [query,setQuery]=useState(''),[system,setSystem]=useState('all'),[tab,setTab]=useState<'definition'|'parts'|'function'>('definition');
 const [panel,setPanel]=useState<'compact'|'medium'|'full'>('medium'),[mobileLayers,setMobileLayers]=useState(false),[detailOpen,setDetailOpen]=useState(false),[fullscreen,setFullscreen]=useState(false),[notice,setNotice]=useState('');
 const [guide,setGuide]=useState(false),[sources,setSources]=useState(false),[quiz,setQuiz]=useState<number|null>(null),[feedback,setFeedback]=useState(''),[quizCorrect,setQuizCorrect]=useState(false),[speaking,setSpeaking]=useState(false);
 const app=useRef<HTMLElement>(null);
 const viewer=useRef<ViewerHandle>(null),guideDialog=useRef<HTMLDialogElement>(null),sourceDialog=useRef<HTMLDialogElement>(null),searchInput=useRef<HTMLInputElement>(null);
 const organShortcuts=[['eye_l','Mata','visibility'],['ear_l','Telinga','hearing'],['nose','Hidung','air'],['mouth','Mulut & gigi','dentistry'],['hand_l','Tangan','back_hand'],['foot_l','Kaki','podiatry'],['heart','Jantung','favorite'],['brain_l','Otak','neurology'],['lung_r','Paru-paru','pulmonology'],['liver','Hati','gastroenterology'],['stomach','Lambung','gastroenterology'],['kidney_l','Ginjal','nephrology'],['jejunum','Usus kosong','gastroenterology'],['pancreas','Pankreas','endocrinology']].filter(([id])=>manifest.parts.some(p=>p.id===id));
 const selected=manifest.parts.find(p=>p.id===state.selectedId),heart=manifest.parts.find(p=>p.id==='heart')!;
 const done=useMemo(()=>new Set(activity.filter(a=>a.memberId===memberId&&a.toolId==='edukasi6'&&a.event==='material_complete').map(a=>a.partId)),[activity,memberId]);
 const duration=activity.filter(a=>a.memberId===memberId&&a.toolId==='edukasi6').reduce((n,a)=>n+a.durationSec,0);
 useEffect(()=>{const mq=window.matchMedia('(prefers-reduced-motion: reduce)');const update=()=>dispatch({type:'patch',patch:{reducedMotion:mq.matches,playing:false}});update();mq.addEventListener('change',update);return()=>mq.removeEventListener('change',update);},[]);
 useEffect(()=>{const changed=()=>setFullscreen(document.fullscreenElement===app.current);document.addEventListener('fullscreenchange',changed);return()=>document.removeEventListener('fullscreenchange',changed);},[]);
 const toggleFullscreen=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await app.current?.requestFullscreen();}catch{setNotice('Layar penuh belum didukung browser ini. Ruang model tetap bisa diperluas dengan menutup panel.');}};
 useEffect(()=>{if(!notice)return;const timer=window.setTimeout(()=>setNotice(''),6500);return()=>window.clearTimeout(timer);},[notice]);
 useEffect(()=>{if(guide)guideDialog.current?.showModal();else guideDialog.current?.close();},[guide]);
 useEffect(()=>{if(sources)sourceDialog.current?.showModal();else sourceDialog.current?.close();},[sources]);
 useEffect(()=>()=>{if('speechSynthesis' in window)window.speechSynthesis.cancel();},[]);
 const select=useCallback((id:string,reveal=false)=>{
  const part=manifest.parts.find(p=>p.id===id);if(!part)return;
  if('speechSynthesis' in window)window.speechSynthesis.cancel();setSpeaking(false);
  dispatch({type:'select',part,reveal});if(part.kind==='inset'){dispatch({type:'isolate',id:part.id,camera:state.snapshot?.camera??viewer.current?.camera()??{position:[0,.9,3.2],target:[0,.9,0]}});window.setTimeout(()=>viewer.current?.focus(part.id),30);}setPanel('medium');setDetailOpen(true);
  if(reveal){setMobileLayers(false);setNotice(`${part.nameId} dipilih. Lapisan ${LAYERS.find(l=>l.id===part.layer)?.name.toLowerCase()} ditampilkan; penghalang luar dibuka.`);}
  if(quiz!==null){const correct=id===QUESTIONS[quiz].answer;setQuizCorrect(correct);setFeedback(correct?'Tepat. '+QUESTIONS[quiz].explanation:'Belum cocok. '+part.nameId+': '+part.definitionSimple);}
 },[manifest,quiz,state.snapshot]);
 const isolate=(p:Part,interior=false)=>{
  dispatch({type:'isolate',id:p.id,camera:state.snapshot?.camera??viewer.current?.camera()??{position:[0,.9,3.2],target:[0,.9,0]}});
  dispatch({type:'select',part:p,reveal:true});
  if(p.kind==='assembly'||p.id.startsWith('eye_'))for(const layer of ['bone','organ','muscle','nerve'] as const)dispatch({type:'layer',id:layer,visible:true,opacity:1});
  if(p.id==='heart')dispatch({type:'layer',id:'vessel',visible:true,opacity:1});
  if(interior){dispatch({type:'patch',patch:{interior:p.id}});setTab('parts');}
  if(window.matchMedia('(max-width: 879px)').matches)setDetailOpen(false);
  window.setTimeout(()=>viewer.current?.focus(p.id),30);
 };
 const reset=()=>{dispatch({type:'reset'});setQuery('');setSystem('all');setTab('definition');setNotice('Model dan seluruh kontrol kembali ke kondisi awal.');setQuiz(null);setFeedback('');setQuizCorrect(false);if('speechSynthesis' in window)window.speechSynthesis.cancel();setSpeaking(false);};
 const speak=()=>{
  if(!selected)return;if(!('speechSynthesis' in window)){setNotice('Pembacaan suara belum didukung browser ini. Teks tetap tersedia.');return;}
  if(speaking){window.speechSynthesis.cancel();setSpeaking(false);return;}
  const voice=window.speechSynthesis.getVoices().find(v=>v.lang.toLowerCase().startsWith('id'));
  if(!voice){setNotice('Suara bahasa Indonesia belum tersedia di perangkat ini. Kamu tetap bisa membaca teks di panel.');return;}
  const utterance=new SpeechSynthesisUtterance(selected.nameId+'. '+selected.definitionSimple+' '+selected.functions.join(' '));utterance.lang='id-ID';utterance.voice=voice;utterance.rate=.9;utterance.onend=()=>setSpeaking(false);utterance.onerror=()=>{setSpeaking(false);setNotice('Suara belum dapat diputar. Teks tetap tersedia.');};setSpeaking(true);window.speechSynthesis.speak(utterance);
 };
 const list=useMemo(()=>manifest.parts.filter(p=>query?searchable(p,query):(state.region==='all'||p.regionId===state.region)&&(system==='all'||p.systemIds.includes(system))),[manifest,query,state.region,system]);
 const startQuiz=()=>{dispatch({type:'reset'});setQuiz(0);setQuizCorrect(false);setFeedback('');setMobileLayers(true);setQuery('');setSystem('all');};
 const layerPanel=<>
  <div className="anatomy-panel-title"><h2>Lapisan tubuh</h2><button className="anatomy-icon" aria-label="Tutup lapisan" onClick={()=>setMobileLayers(false)}><Icon name="close"/></button></div>
  <div className="anatomy-layer-list">{LAYERS.map(layer=><div className="anatomy-layer" key={layer.id}>
   <button role="switch" aria-checked={state.layers[layer.id].visible} aria-label={`Lapisan ${layer.name}`} onClick={()=>dispatch({type:'layer',id:layer.id,visible:!state.layers[layer.id].visible})}><span className="anatomy-layer-name"><Icon name={layer.icon} size={22}/>{layer.name}</span><Switch on={state.layers[layer.id].visible}/></button>
   {state.layers[layer.id].visible&&<label className="anatomy-opacity"><span>Opasitas {Math.round(state.layers[layer.id].opacity*100)}%</span><input aria-label={`Opasitas ${layer.name}`} type="range" min={0} max={100} value={Math.round(state.layers[layer.id].opacity*100)} onChange={e=>dispatch({type:'layer',id:layer.id,opacity:Number(e.target.value)/100})}/></label>}
  </div>)}</div>
  <div className="anatomy-divider"/><h2>Bagian tubuh</h2>
  <label className="anatomy-search"><Icon name="search" size={19}/><input ref={searchInput} type="search" value={query} placeholder="Cari bagian…" aria-label="Cari bagian tubuh" onChange={e=>setQuery(e.target.value)}/></label>
  <div className="anatomy-filter-row"><select aria-label="Wilayah tubuh" value={state.region} onChange={e=>{dispatch({type:'patch',patch:{region:e.target.value as RegionId|'all',explode:0}});setQuery('');}}><option value="all">Semua wilayah</option>{Object.entries(REGIONS).map(([id,name])=><option value={id} key={id}>{name}</option>)}</select>
   <select aria-label="Sistem tubuh" value={system} onChange={e=>{setSystem(e.target.value);setQuery('');}}><option value="all">Semua sistem</option>{Object.entries(SYSTEMS).map(([id,name])=><option value={id} key={id}>{name}</option>)}</select></div>
  <p className="anatomy-caption">{list.length} bagian dalam katalog pengembangan</p>
  <ul className="anatomy-parts-list" aria-label="Daftar bagian tubuh">{list.map(p=><li key={p.id}><button aria-pressed={selected?.id===p.id} onClick={()=>select(p.id,true)}><span className="anatomy-dot" style={{background:LAYERS.find(l=>l.id===p.layer)?.color}}/><span>{p.nameId}</span>{done.has(p.id)?<Icon name="check" size={16}/>:<Icon name="chevron_right" size={16}/>}</button></li>)}</ul>
  {list.length===0&&<p className="anatomy-empty">Belum ketemu. Coba nama lain, misalnya “bilik” atau “paru”.</p>}
 </>;
 return <main ref={app} className={'anatomy-app playful '+(fullscreen?'is-fullscreen':'')}>
  <header className="anatomy-header"><Link href="/beranda" className="anatomy-wordmark">RINOYA<span className="anatomy-logo-dot"/></Link><nav aria-label="Navigasi modul"><Link href="/beranda/edukasi">Edukasi</Link><Icon name="chevron_right" size={16}/><span aria-current="page">Tubuh Manusia</span></nav><div className="anatomy-header-actions"><button onClick={()=>setGuide(true)} className="anatomy-button quiet"><Icon name="help_outline" size={20}/><span>Panduan</span></button><button className="anatomy-profile" aria-label="Ganti profil" onClick={()=>openSheet({kind:'members'})}><Avatar name={me.name} c={me.c} size={30}/><span>{me.name}</span><Icon name="expand_more" size={18}/></button></div></header>
  <div className="anatomy-heading"><div><span className="anatomy-eyebrow">TUBUH MANUSIA · KENALI DIRIMU</span><h1>Jelajah Tubuh 3D</h1><p>Petualangan seru mengenal tubuh kita!</p></div><div className="anatomy-heading-right"><button className="anatomy-button" onClick={startQuiz}><Icon name="quiz" size={19}/>Cek pemahaman</button><button className="anatomy-caption anatomy-status" onClick={()=>setSources(true)}>Katalog pengembangan · belum ditinjau</button></div></div>
  <div className={"anatomy-workspace "+(mobileLayers?"layers-open ":"")+(detailOpen?"detail-open":"")}>
   <aside className={'anatomy-sidebar '+(mobileLayers?'is-open':'')} aria-label="Lapisan dan bagian tubuh">{layerPanel}</aside>
   <section className="anatomy-stage" aria-label="Ruang eksplorasi tubuh">
    <div className="anatomy-stage-top"><button className="anatomy-button anatomy-layer-toggle" aria-expanded={mobileLayers} onClick={()=>setMobileLayers(!mobileLayers)}><Icon name="layers" size={20}/>Lapisan & pencarian</button><div className="anatomy-breadcrumb"><button onClick={()=>state.isolation?dispatch({type:'back'}):reset()}><Icon name="accessibility_new" size={18}/>Tubuh</button>{selected&&<><span>/</span><span>{REGIONS[selected.regionId]}</span><span>/</span><strong>{selected.nameId}</strong></>}</div><div className="anatomy-stage-tools"><button className="anatomy-icon" aria-label={detailOpen?"Tutup informasi bagian":"Buka informasi bagian"} aria-expanded={detailOpen} onClick={()=>setDetailOpen(!detailOpen)}><Icon name="info"/></button><button className="anatomy-icon" aria-label={fullscreen?"Keluar layar penuh":"Layar penuh"} onClick={toggleFullscreen}><Icon name={fullscreen?"fullscreen_exit":"fullscreen"}/></button></div></div>
    {!mobileLayers&&<div className="anatomy-layer-dock anatomy-organ-dock" aria-label="Pilihan organ">{organShortcuts.map(([id,name,icon])=><button key={id} aria-label={'Pelajari '+name.toLowerCase()} aria-pressed={state.isolation===id} onClick={()=>{const p=manifest.parts.find(p=>p.id===id)!;select(id,true);isolate(p);}}><span><Icon name={icon}/></span><small>{name}</small></button>)}</div>}
    {!selected&&<div className="anatomy-start-card"><span className="anatomy-eyebrow">MISI PERTAMAMU</span><h2>Yuk, cari si pemompa darah!</h2><button className="anatomy-button primary" onClick={()=>{select('heart',true);isolate(heart);}}><Icon name="favorite" size={20}/>Jelajahi jantung</button></div>}
    {state.isolation&&<button className="anatomy-back anatomy-button" onClick={()=>{dispatch({type:'back'});setTab('definition');}}><Icon name="arrow_back" size={17}/>Kembali ke tubuh</button>}
    <Viewer ref={viewer} manifest={manifest} state={state} onSelect={id=>select(id)} onDetach={(id,amount)=>dispatch({type:'patch',patch:{detached:{...state.detached,[id]:amount}}})}/>
    {selected?.kind==='inset'&&<div className="anatomy-inset-note">Model diperbesar · skala tampilan, bukan ukuran asli</div>}
    <div className="anatomy-views" aria-label="Sudut pandang">{([['front','Depan'],['back','Belakang'],['left','Kiri'],['right','Kanan']] as const).map(([id,label])=><button key={id} onClick={()=>viewer.current?.preset(id)}>{label}</button>)}<button aria-label="Perbesar model" onClick={()=>viewer.current?.zoom(.8)}><Icon name="add" size={18}/></button><button aria-label="Perkecil model" onClick={()=>viewer.current?.zoom(1.25)}><Icon name="remove" size={18}/></button></div>
    {quiz!==null&&<div className="anatomy-quiz"><div><span className="anatomy-eyebrow">LATIHAN {quiz+1} DARI {QUESTIONS.length}</span><button aria-label="Tutup latihan" onClick={()=>{setQuiz(null);setFeedback('');}}><Icon name="close" size={19}/></button></div><p>{QUESTIONS[quiz].text}</p>{feedback&&<p role="status" className="anatomy-feedback">{feedback}</p>}{quizCorrect&&<button className="anatomy-button" onClick={()=>{complete(memberId,QUESTIONS[quiz].id,true);if(quiz===QUESTIONS.length-1){setQuiz(null);setNotice('Latihan selesai. Progres tersimpan untuk '+me.name+'.');}else {setQuiz(quiz+1);setQuizCorrect(false);setFeedback('');}}}>{quiz===QUESTIONS.length-1?'Selesaikan latihan':'Lanjut'}</button>}</div>}
    <div className="anatomy-stage-bottom">
     {state.mode==='explode'&&<label className="anatomy-slider"><span>Jarak pisah · {state.isolation?(manifest.parts.find(p=>p.id===state.isolation)?.nameId??'Bagian'):state.region==='all'?'Pilih wilayah dahulu':REGIONS[state.region]} <strong>{state.explode}%</strong></span><input aria-label="Jarak pisah" type="range" min={0} max={100} disabled={state.region==='all'&&!state.isolation} value={state.explode} onChange={e=>dispatch({type:'patch',patch:{explode:Number(e.target.value)}})}/></label>}
     {state.mode==='disassemble'&&<div className="anatomy-slider"><p>Geser bagian mengikuti jalurnya, atau pilih “Lepas / pasang” pada panel.</p></div>}
     {state.section&&<div className="anatomy-slider"><div className="anatomy-section-options"><label>Arah <select aria-label="Orientasi potongan" value={state.section.axis} onChange={e=>dispatch({type:'patch',patch:{section:{axis:e.target.value as 'axial'|'sagittal'|'coronal',position:state.section!.position}}})}><option value="axial">Axial / transversal</option><option value="sagittal">Sagittal · kanan–kiri</option><option value="coronal">Coronal · depan–belakang</option></select></label><strong>{state.section.position}%</strong></div><input aria-label="Posisi potongan" type="range" min={0} max={100} value={state.section.position} onChange={e=>dispatch({type:'patch',patch:{section:{...state.section!,position:Number(e.target.value)}}})}/><small>Potongan pengembangan: batas jaringan belum diberi permukaan irisan.</small></div>}
     <div className="anatomy-toolbar" aria-label="Kontrol model">
      <button aria-pressed={state.mode==='orbit'} onClick={()=>dispatch({type:'patch',patch:{mode:'orbit',section:null}})}><Icon name="360"/><span>Putar</span></button>
      <button aria-pressed={state.mode==='explode'} onClick={()=>{dispatch({type:'patch',patch:{mode:'explode',section:null}});if(state.region==='all')dispatch({type:'patch',patch:{region:'thorax'}});}}><Icon name="deployed_code"/><span>Pisahkan</span></button>
      <button aria-pressed={state.mode==='disassemble'} onClick={()=>dispatch({type:'patch',patch:{mode:'disassemble',section:null}})}><Icon name="pan_tool_alt"/><span>Bongkar</span></button>
      <button aria-pressed={state.mode==='section'} disabled={state.isolation!=='heart'} title={state.isolation!=='heart'?'Isolasi jantung untuk memeriksa potongan':'Potongan jantung'} onClick={()=>{dispatch({type:'reassemble'});dispatch({type:'patch',patch:{mode:'section',section:{axis:'coronal',position:50}}});}}><Icon name="content_cut"/><span>Potongan</span></button>
      <button onClick={reset}><Icon name="restart_alt"/><span>Reset</span></button>
     </div>
     <p className="anatomy-hint">Geser untuk memutar. Cubit untuk zoom. Ketuk bagian untuk belajar.</p>
    </div>
   </section>
   <aside className={'anatomy-detail '+panel+(detailOpen?' is-open':'')} aria-label="Informasi bagian">
    <button className="anatomy-detail-close anatomy-icon" aria-label="Tutup panel informasi" onClick={()=>setDetailOpen(false)}><Icon name="close"/></button>
    <div className="anatomy-sheet-controls anatomy-mobile-only"><button aria-label="Kecilkan informasi" onClick={()=>setPanel('compact')}><Icon name="keyboard_arrow_down"/></button><button onClick={()=>setPanel(panel==='full'?'medium':'full')}>{panel==='full'?'Ringkas':'Perluas informasi'}</button></div>
    {!selected?<div className="anatomy-welcome"><span className="anatomy-organ-icon"><Icon name="touch_app" size={36}/></span><h2>Mulai dari rasa ingin tahu.</h2><p>Ketuk bagian pada model atau cari namanya untuk mengenali fungsi dan letaknya.</p><button className="anatomy-button primary" onClick={()=>select('heart',true)}><Icon name="favorite" size={19}/>Kenali jantung</button><div className="anatomy-divider"/><span className="anatomy-eyebrow">JELAJAHI JUGA</span>{[['brain_l','Otak'],['lung_r','Paru-paru'],['stomach','Lambung'],['kidney_l','Ginjal']].map(([id,label])=><button key={id} className="anatomy-suggestion" onClick={()=>select(id,true)}>{label}<Icon name="arrow_outward" size={18}/></button>)}</div>:<>
     <div className="anatomy-detail-heading"><span className="anatomy-eyebrow">{selected.systemIds.map(s=>SYSTEMS[s]).join(' · ')}</span><h2>{selected.nameId}</h2><p>{selected.definitionSimple}</p>{!visiblePart(selected,state,manifest.parts)&&<p className="anatomy-caption">Bagian sedang tersembunyi. <button onClick={()=>select(selected.id,true)}>Tampilkan</button></p>}</div>
     <div className="anatomy-tabs" role="tablist" aria-label="Materi bagian">{([['definition','Definisi'],['parts','Bagian'],['function','Fungsi']] as const).map(([id,name])=><button key={id} role="tab" id={'tab-'+id} aria-controls="anatomy-tab-content" aria-selected={tab===id} onClick={()=>setTab(id)}>{name}</button>)}</div>
     <div className="anatomy-detail-content" role="tabpanel" id="anatomy-tab-content" aria-labelledby={'tab-'+tab}>
      {tab==='definition'&&<><h3>Di mana letaknya?</h3><p>{selected.locationText}</p><h3>Kenali lebih dekat</h3><p>{selected.definitionDetailed}</p><details><summary>Istilah anatomi & sumber</summary><p>{selected.anatomicalName}</p><p>{selected.sources.map(s=><a key={s.url} href={s.url} target="_blank" rel="noreferrer">{s.title} ↗</a>)}</p><small>Status materi: menunggu tinjauan anatomi.</small></details></>}
      {tab==='parts'&&<>{selected.childIds.length?<><p className="anatomy-caption">Pilih nama untuk menyorot jaringan yang terkait.</p>{selected.childIds.map(id=>{const p=manifest.parts.find(p=>p.id===id)!;return <button className="anatomy-suggestion" key={id} onClick={()=>{select(id,true);viewer.current?.focus(id);}}>{p.nameId}<Icon name="chevron_right" size={16}/></button>;})}</>:<><p>Ini adalah bagian bernama dalam katalog. Detail di bawah tingkat ini belum tersedia.</p>{selected.parentId&&<button className="anatomy-button" onClick={()=>select(selected.parentId!,true)}>{manifest.parts.find(p=>p.id===selected.parentId)?.nameId??'Kembali ke kelompok'}</button>}</>}</>}
      {tab==='function'&&<><h3>Apa tugasnya?</h3>{selected.functions.map(f=><p key={f}>{f}</p>)}{selected.capabilities.animation&&<div className="anatomy-simulation"><span className="anatomy-eyebrow">SIMULASI ALUR SEDERHANA</span><p>Serambi kanan → bilik kanan → paru → serambi kiri → bilik kiri → tubuh.</p><p className="anatomy-caption">Penanda menunjukkan urutan, bukan kecepatan darah atau detak tubuhmu. Jalur ke paru diringkas.</p><button className="anatomy-button primary" disabled={state.reducedMotion} onClick={()=>{if(state.isolation!=='heart'||state.interior!=='heart')isolate(heart,true);dispatch({type:'patch',patch:{playing:!state.playing}});setTab('function');}}><Icon name={state.playing?'pause':'play_arrow'}/>{state.playing?'Jeda':'Putar simulasi'}</button><label className="anatomy-speed">Kecepatan <select aria-label="Kecepatan simulasi" value={state.speed} onChange={e=>dispatch({type:'patch',patch:{speed:Number(e.target.value)}})}><option value={.5}>0,5×</option><option value={1}>1×</option><option value={2}>2×</option></select></label>{state.reducedMotion&&<p>Gerakan dikurangi. Urutan aliran tersedia dalam teks.</p>}</div>}</>}
     </div>
     <div className="anatomy-detail-actions">
      {selected.insetId&&<button className="anatomy-button primary" onClick={()=>{const p=manifest.parts.find(p=>p.id===selected.insetId)!;select(p.id,true);isolate(p);}}><Icon name="hearing" size={20}/>Jelajahi telinga dalam</button>}
      {selected.capabilities.interior&&<button className="anatomy-button primary" onClick={()=>isolate(selected,true)}><Icon name="visibility" size={20}/>Lihat bagian dalam</button>}
      <div className="anatomy-action-grid"><button className="anatomy-button" onClick={()=>{if(window.matchMedia('(max-width: 879px)').matches)setDetailOpen(false);viewer.current?.focus(selected.id);}}><Icon name="center_focus_strong" size={18}/>Fokus</button><button className="anatomy-button" onClick={()=>isolate(selected)}><Icon name="deployed_code" size={18}/>Isolasi</button><button className="anatomy-button" onClick={speak}><Icon name={speaking?'stop':'volume_up'} size={18}/>{speaking?'Hentikan':'Dengarkan'}</button><button className="anatomy-button" disabled={!selected.capabilities.disassemble||!!state.section} onClick={()=>dispatch({type:'patch',patch:{detached:{...state.detached,[selected.id]:(state.detached[selected.id]??state.explode)>0?0:100}}})}><Icon name="open_with" size={18}/>Lepas / pasang</button></div>
      <button className="anatomy-button quiet" onClick={()=>dispatch({type:'reassemble'})}><Icon name="restart_alt" size={18}/>Susun kembali</button>
      <button className="anatomy-complete" disabled={done.has(selected.id)} onClick={()=>complete(memberId,selected.id)}><Icon name={done.has(selected.id)?'check_circle':'check'} size={18}/>{done.has(selected.id)?'Sudah dipelajari':'Tandai sudah dipelajari'}</button>
     </div>
    </>}
   </aside>
  </div>
  {notice&&<div role="status" className="anatomy-notice"><span>{notice}</span><button aria-label="Tutup informasi" onClick={()=>setNotice('')}><Icon name="close" size={18}/></button></div>}
  <footer className="anatomy-footer"><span>{done.size} materi dipelajari · {Math.floor(duration/60)} menit aktif · {me.name}</span><div><label><input type="checkbox" checked={state.labels} onChange={e=>dispatch({type:'patch',patch:{labels:e.target.checked}})}/>Label</label><label><input type="checkbox" checked={state.reducedMotion} onChange={e=>dispatch({type:'patch',patch:{reducedMotion:e.target.checked,playing:false}})}/>Kurangi gerakan</label><button onClick={()=>setSources(true)}>Sumber & cakupan</button></div></footer>
  <dialog ref={guideDialog} className="anatomy-dialog" onCancel={()=>setGuide(false)} onClose={()=>setGuide(false)}><button className="anatomy-dialog-close" aria-label="Tutup panduan" onClick={()=>setGuide(false)}><Icon name="close"/></button><span className="anatomy-eyebrow">PANDUAN EKSPLORASI</span><h2>Kenali tubuh, selangkah demi selangkah.</h2><ol><li>Geser model untuk memutar. Cubit atau gunakan tombol + dan − untuk zoom.</li><li>Buka lapisan dan pilih organ. Kanan dan kiri mengikuti sisi tubuh model.</li><li>Pilih “Isolasi” untuk melihat satu bagian. “Kembali ke tubuh” mengembalikan konteks sebelumnya.</li><li>Jantung memiliki dinding yang dapat dibuka. Pilih struktur dalam melalui daftar.</li><li>Gunakan “Pisahkan”, lalu atur jaraknya. Semua gerakan bisa dikembalikan dengan “Susun kembali”.</li></ol><p>Keyboard: Tab berpindah kontrol, Enter memilih, tombol panah mengatur slider. Daftar bagian adalah alternatif memilih objek kecil.</p><p>Waktu aktif berhenti saat tab tersembunyi, tidak fokus, atau tidak ada interaksi selama satu menit.</p><button className="anatomy-button primary" onClick={()=>setGuide(false)}>Mulai menjelajah</button></dialog>
  <dialog ref={sourceDialog} className="anatomy-dialog" onCancel={()=>setSources(false)} onClose={()=>setSources(false)}><button className="anatomy-dialog-close" aria-label="Tutup sumber" onClick={()=>setSources(false)}><Icon name="close"/></button><span className="anatomy-eyebrow">SUMBER & CAKUPAN</span><h2>Katalog yang bisa diperiksa.</h2><p>{manifest.parts.length} struktur pada versi {manifest.version}. Model dan teks berstatus pengembangan, belum mendapat peninjauan anatomi manusia.</p><p>Model dasar menggunakan variasi anatomi dewasa laki-laki. Material organ memakai perkiraan warna jaringan alami, terpisah dari warna antarmuka. Tampilan jaringan dapat berbeda menurut kondisi dan pencahayaan. Bentuk dan pemisahan merupakan alat peraga belajar.</p><p><a href="/anatomy/ATTRIBUTION.md" target="_blank">Atribusi dan lisensi aset ↗</a> · <a href="/anatomy/manifest.json" target="_blank">Manifest lengkap ↗</a></p><h3>Yang masih perlu dilengkapi</h3><ul>{manifest.missing.map(m=><li key={m}>{m}</li>)}</ul><p>Progres mengikuti profil dan mekanisme penyimpanan Rinoya Academy.</p></dialog>
 </main>;
}
